performancecopilot/pcp

- qa/1069
- qa/1069.out
- src/pmrep/pmrep.py
https://groups.io/g/pcp/topic/pmrep_endtime_not_effective/4889031
Reported-by: Rares Vernica <rvernica@gmail.com>
> pmrep: correctly handle endtime in uninterpolated mode

- src/pmrep/pmrep.1
- src/pmrep/pmrep.py
With RHBZ#1289912 fixed we can drop the last BUGS item from pmrep(1).
Address the corner case issue with -c while at it.
Minor related cleanups, all QA still passing.
> pmrep: cmd line improvements

- README.osx
Details of the latest requirements and links are added.
> Readme.osx updated for packagemaker and links added for downloading..

- README.osx
Updated the latest versions of xz, libpng, pixman, cairo and libmicrohttpd. Some minor changes to terminal commands as well.
> Latest versions and some minor command changes

- .pylintrc
- .travis.yml
- qa/1124
- qa/1127
- qa/common.bcc
- src/pmdas/bcc/modules/pcpbcc.python
- src/pmdas/bcc/modules/sysfork.python
- src/pmdas/bcc/modules/tracepoint_hits.python
- src/pmdas/bcc/modules/uprobe_hits.python
using pylint from pip, as the version in ubuntu trusty (at travis) is outdated
if there are merge conflicts with pending patches from Marko, just ping me and I'll rebase
>  travis: add pylint for pmdabcc 

- qa/1154
check for zpool tool and presence of the ZFS kernel module
> qa: 1154: check for zpool tool and ZFS kernel module

- src/include/pcp/platform_defs.h.in
- src/libpcp/src/GNUmakefile
- src/libpcp/src/util.c
- src/newhelp/GNUmakefile
- src/pmcpp/GNUmakefile
Changes required by native build process on Windows
> Windows native build changes

- qa/1155
- qa/1156
- qa/1156.out
- qa/common.bcc
- qa/group
- src/pmdas/bcc/bcc.conf
- src/pmdas/bcc/modules/execsnoop.bpf
- src/pmdas/bcc/modules/execsnoop.python
- src/pmdas/bcc/modules/pcpbcc.python
- src/pmdas/bcc/modules/tcplife.python
execsnoop bcc tool + QA + some refactorings
> pmdabcc: execsnoop

- .pylintrc
- qa/1156
- qa/1157
- qa/1157.out
- qa/group
- src/pmdas/bcc/bcc.conf
- src/pmdas/bcc/modules/tcplife.python
- src/pmdas/bcc/modules/tcpretrans.python
- src/pmdas/bcc/modules/tcpretrans_count.bpf
>  pmdabcc: tcpretrans module + QA 

- src/pmdas/bcc/bcc.conf
- src/pmdas/bcc/modules/tcpperpid.python
restore old tcplife module as tcpperpid (count tcp tx/rx per pid and purges dead PIDs)
> pmdabcc: restore old tcplife module as tcpperpid

- .pylintrc
- qa/1170
- qa/1170.out
- qa/group
- src/pmdas/bcc/bcc.conf
- src/pmdas/bcc/modules/tcptop.bpf
- src/pmdas/bcc/modules/tcptop.python
adds the tcptop tool to the BCC PMDA
> pmdabcc: tcptop module + QA

- src/pmchart/GNUmakefile
- src/pmdumptext/GNUmakefile
- src/pmquery/GNUmakefile
- src/pmtime/GNUmakefile
Changes for a clean build of pmchart and pmtime.
> Fix for qt installation in MacOS

- src/pmchart/GNUmakefile
- src/pmquery/GNUmakefile
- src/pmtime/GNUmakefile
Edit in the directory of pmchart, pmtime and pmquery.
> Added PACKAGE_VERISON in PKG_MAC_DIR

- INSTALL.md
This is the basic layout of the steps to build and install on MacOS.
> Updated INSTALL.md for MacOS installation

- INSTALL.md
Detailed instructions for creating symlinks.
> Updated INSTALL.md with symlinks settings

- src/pcp/dstat/pcp-dstat.py
Add CSV output support for pcp-dstat, which is for backward compatibility with existing python2 dstat utility.
> pcp-dstat: add CSV output support for pcp-dstat

- qa/1399
- qa/1399.out
"Adding -z to test cases in qa/1399 so that report will use timezone of the test archive and not of the local timezone"
It is follow up commit related to pull request #534
> qa/1399: Adding -z to test cases

- src/pmwebd/pmgraphite.cxx
Previously, a hard-coded 0.5 epsilon squashed small near-zero time
series (seen on rate-converted counters) to wiggles, due to poor
vertical autoscaling.  Now we choose a relative epsilon that is
informed by the visual space / precision alotted to the drawn y axis
label (5 digits + exponent).  Eyeballing on a range of time series,
both near and far zero now results in more eye-pleasing graphs.  QA
not impacted, as these are purely visual artifacts.
> pmwebd graphite pngs: tweak y axis labeling

- qa/common.check
- src/pmie/GNUmakefile
- src/pmie/pmie_check.service.in
- src/pmie/pmie_daily.service.in
- src/pmie/pmie_timers.sysconfig
- src/pmlogger/.gitignore
- src/pmlogger/GNUmakefile
- src/pmlogger/pmlogger_check.service.in
- src/pmlogger/pmlogger_daily-poll.service.in
- src/pmlogger/pmlogger_daily.service.in
- src/pmlogger/pmlogger_daily_report-poll.service.in
- src/pmlogger/pmlogger_daily_report.service.in
- src/pmlogger/pmlogger_timers.sysconfig
A minor follow up to 7ca7595004c6c7b07deb1bd3a81958fb72c93458 .
Signed-off-by: David Disseldorp <ddiss@suse.de>
> systemd: pmlogger_daily_check -> pmlogger_check renames

- provisioning/release.sh
Should have added this awhile ago, oops!
> Add provisioning/release script to help with vagrant bintray uploads

- README.md
- azure-pipelines.yml
- build/containers/qa/Dockerfile.debian-stable
- build/containers/qa/Dockerfile.debian-testing
- build/containers/qa/Dockerfile.fedora-rawhide
- build/containers/qa/Dockerfile.fedora30
- build/containers/qa/gen_junit_report.py
- build/containers/qa/qa.yml
- src/pmrep/pmrep.py
Tests run in parallel in 4 docker containers (Fedora Rawhide + 30, Debian testing + stable), and produce test summaries: https://dev.azure.com/andreasgerstmayr/pcp/_build/results?buildId=9&view=ms.vss-test-web.build-test-results-tab
(Every QA test is run on every distribution/release, therefore the high total test count)
> Azure pipeline tests

- man/man1/sar2pcp.1
> Mention pcp archive support in sysstat 12.0.5 in sar2pcp manpage

- src/libpcp_web/src/exports
Adds some functions into exports of libpcp_web, which will be used in upcoming StatsD agent.
> modified exports in libpcp_web

- qa/600
qa/600: expand on the bizarre notes comment section
qa/600 |    7 ++++++-
1 file changed, 6 insertions(+), 1 deletion(-)
Details ...
commit 461b868457fed8c1e8e15cb463fcbfdbcac5c08f
Date:   Sun Jul 7 13:15:00 2019 +1000
qa/600: expand on the bizarre notes comment section
This test fails for a week and then recovers, twice per annum
... go figure!
> Changes committed to git@github.com:kmcdonell/pcp.git master

- src/libpcp_web/src/exports
I will need dictDelete function available in StatsD PMDA, therefore making it available.
> making dictDelete function available

- scripts/new-branch
- scripts/pcp-refresh
- src/pmdas/sample/src/GNUmakefile.install
Ken McDonell (3):
src/pmdas/sample/src/GNUmakefile.install: add dsohelp* files to LDIRT
scripts/new-branch: another helper for a github workflow
scripts/pcp-refresh: another helper scripts for the github workflow
scripts/new-branch                       |   90 +++++++++++++++++++++++++++++++
scripts/pcp-refresh                      |   90 +++++++++++++++++++++++++++++++
src/pmdas/sample/src/GNUmakefile.install |    2 
3 files changed, 181 insertions(+), 1 deletion(-)
Details ...
commit ba757749ce4c79e772e8c8fef2a863a678d0fc53
Date:   Sat Aug 10 17:55:51 2019 +1000
scripts/pcp-refresh: another helper scripts for the github workflow
commit 648e9800f9fb0fbf933fa2cf2b04397e42c94aa4
Date:   Sat Aug 10 07:25:31 2019 …
> small sample PMDA change, github helpeer scripts Changes committed to git@github.com:kmcdonell/pcp.git 20190802

- INSTALL.md
- src/pmdas/statsd/.dbpmdarc
- src/pmdas/statsd/README.md
- src/pmdas/statsd/src/aggregator-metric-counter.c
- src/pmdas/statsd/src/aggregator-metric-duration-exact.c
- src/pmdas/statsd/src/aggregator-metric-gauge.c
- src/pmdas/statsd/src/aggregator-metric-gauge.h
- src/pmdas/statsd/src/aggregator-metric-labels.c
- src/pmdas/statsd/src/aggregator-metrics.c
- src/pmdas/statsd/src/aggregator-metrics.h
- src/pmdas/statsd/src/aggregator-stats.c
- src/pmdas/statsd/src/aggregators.c
- src/pmdas/statsd/src/aggregators.h
- src/pmdas/statsd/src/config-reader.c
- src/pmdas/statsd/src/config-reader.h
- src/pmdas/statsd/src/dict-callbacks.c
- src/pmdas/statsd/src/network-listener.c
- src/pmdas/statsd/src/network-listener.h
- src/pmdas/statsd/src/parser-basic.c
- src/pmdas/statsd/src/parser-ragel.rl
- src/pmdas/statsd/src/parsers-utils.c
- src/pmdas/statsd/src/parsers-utils.h
- src/pmdas/statsd/src/parsers.c
- src/pmdas/statsd/src/parsers.h
- src/pmdas/statsd/src/pmda-callbacks.c
- src/pmdas/statsd/src/pmdastatsd.c
- src/pmdas/statsd/src/pmdastatsd.h
- src/pmdas/statsd/src/utils.c
- src/pmdas/statsd/src/utils.h
added last work from separate StatsD repo, cleaned up memory leaks/errors with Valgrind, small edits to .dbpmdarc
> StatsD update

- qa/1098
- qa/1110
- qa/1388
- qa/admin/other-packages/unavailable
qa/admin/other-packages/unavailable: rpm changes
qa/1098: better and earlier warning if test_python PMDA install goes badly
qa/1110: one-trip filter for empty indom cache file
qa/1388: remove the test_python PMDA at the end
qa/1098                             |   13 ++++++++++---
qa/1110                             |   12 +++++++++++-
qa/1388                             |    9 +++++++++
qa/admin/other-packages/unavailable |   10 ++++++----
4 files changed, 36 insertions(+), 8 deletions(-)
Details ...
commit 3d1912f82b4635b8170d20bacd4362ca0b4f0a53
Date:   Wed Oct 9 10:09:36 2019 +1100
qa/1388: remove the test_python PMDA at the end
Was causing a number of cascading QA failures when the test_python
PMDA was installed on random QA …
> small qa changes Changes committed to git@github.com:kmcdonell/pcp.git 20191009

- src/pmdas/nfsclient/pmdanfsclient.python
This adds a number of additional nfs client statistics that the kernel exports
> Update nfs client statistics

- man/man3i/__pmServerNotifyServiceManagerReady.3
- qa/1359.out
- qa/1566
- qa/1566.out
- qa/group
- qa/src/GNUlocaldefs
- qa/src/test_service_notify.c
- src/include/pcp/libpcp.h
- src/include/pcp/pmapi.h
- src/libpcp/src/GNUlibrarydefs
- src/libpcp/src/auxserver.c
- src/libpcp/src/exports.master
- src/pmcd/pmcd.service.in
- src/pmcd/src/pmcd.c
- src/pmproxy/pmproxy.service.in
- src/pmproxy/src/pmproxy.c
Ken, I've pushed this up to a branch and omitted (for now) any changes to pmlogger and the logutil scripts. Hopefully this will not clash with your changes, other than perhaps qa/group and we can reconcile.  Cheers
> add service manager notify API and change pmcd and pmproxy to type=notify, plus QA

- src/libpcp_web/src/schema.c
Check the redis server version when pmproxy first connect to redis server. If the server version is lower than 5.x, the error message will be printed into file pmproxy.log
> check redis server version

- src/pmdas/rabbitmq/GNUmakefile
- src/pmdas/rabbitmq/pmdarabbitmq.python
Handled edge case(len=0 issue) and cleaned up code using pylint.
> cleanup rabbitmq pmda 

- src/pmdas/rabbitmq/pmdarabbitmq.python
Added help text for all 57 metrics and corrected some metrics to float datatype instead of string.
> added help text for all metrics and corrected datatypes

- src/pmdas/openvswitch/pmdaopenvswitch.python
Added help text and resolved pmid issue for openvswitch pmda.
> Minor changes to openvswitch.

- src/pmdas/rabbitmq/pmdarabbitmq.python
- src/pmdas/rabbitmq/pmlogconf.summary
Added refresh and label functions to pmda and added a pmlogger configuration file.
> rabbitmq pmda: modifications

- src/pmdas/openvswitch/GNUmakefile
- src/pmdas/openvswitch/pmlogconf.summary
Added pmlogger configuration for openvswitch PMDA.
> Openvswitch pmda: addition

- qa/GNUmakefile.install
> build: Fix detection of pcp selinux modules during build of pcpqa.pp

- src/pmdas/openvswitch/pmdaopenvswitch.python
Added try catch block and logged error for the get_switch_info_json class function.
> Fixed openvswitch pmda issues.

- src/pmdas/rabbitmq/pmdarabbitmq.python
Gave a nasty stacktrace text when it was not able to fetch data from server. Caught exception and logged it.
> pmdarabbitmq: added try catch and logged error which resolves stacktrace problem while parsing

- man/man1/pmlogpaste.1
FIlled up the sparse man page with synopsis, description, options etc.
>  pmlogpaste: filled up the man page

- man/man1/pmlogpaste.1
- qa/1821
- src/pmlogpaste/pmlogpaste.c
added label support and updated man page for the same.
>  pmlogpaste: added label support and updated man page for the same

- src/pmdas/linux_proc/acct.c
- src/pmdas/linux_proc/acct.h
I've made some minor changes to pmdaproc(acct) based on the comments of #962.
> pmdaproc: make minor changes to acct

- src/pmcd/pmdaproc.sh
Changes committed to git@github.com:kmcdonell/pcp.git 20200714
sec/pmcd/pmdaproc.sh: silence derived metrics warnings from Remove
src/pmcd/pmdaproc.sh |    2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
Details ...
commit affcfacc1a84cd19a64f064fc915add0c21036c4
Date:   Tue Jul 14 16:30:09 2020 +1000
sec/pmcd/pmdaproc.sh: silence derived metrics warnings from Remove
> pmdaproc fix

- src/pmdas/linux_proc/help
Related to: https://github.com/performancecopilot/pcp/pull/962
> pmdaproc: acct: add help text for acct.control.*

- configure
- configure.ac
- qa/335.out
- qa/README.vm
- qa/admin/other-packages/manifest
- qa/admin/other-packages/skip
- qa/admin/other-packages/unavailable
- qa/common
- src/include/pcp/platform_defs.h.in
- src/libpcp/src/units.c
- src/libpcp_web/src/query.c
- src/pmdas/openbsd/disk.c
- src/pmdas/openbsd/filesys.c
- src/pmdas/sample/src/sample.c
- src/pmlogconf/pmlogconf.c
A bunch of OpenBSD 6.7 portability issues are fixed.
Some generic configure fixups for fallout from the recent "/var -> /usr/... for some folks" changes.
Miscellaneous QA amendments, including a code change for the sample PMDA to ensure pseudo random numbers are deterministic (!) across all platforms for QA.
> odds and sods

- qa/1251
- qa/1672
- qa/507
- qa/687
- qa/750
- qa/793
- qa/common.bpftrace
- qa/group
- src/pmdas/linux/proc_pressure.c
- src/pmdas/linux_proc/cgroups.c
- src/pmlogctl/pmlogctl.sh
Plus a couple of PMDA changes to make the last round of gcc #pragmas work with older gcc versions, like on CentOS 6.
> QA for CI (mostly)

- src/libpcp/src/auxconnect.c
Changes committed to git@github.com:kmcdonell/pcp.git 20200928
src/libpcp/src/auxconnect.c: handle EINPROGRESS from connect() in __pmConnect
src/libpcp/src/auxconnect.c |   53 +++++++++++++++++++++++++++++++++++++-------
1 file changed, 45 insertions(+), 8 deletions(-)
Details ...
commit adf7ea4bb4f2853ecb07f993031ec36be52fbbfb
Date:   Mon Sep 28 14:26:32 2020 +1000
src/libpcp/src/auxconnect.c: handle EINPROGRESS from connect() in __pmConnect
Give us a chance to succeed, even when connect() returns EINPROGRESS.
> fix for EINPROGRESS in __pmConnect()

- src/libpcp_web/src/query.c
updates in series_expr_canonical(), recovering a query statement from a parser tree.
Also fixed bugs in series_compatibility_convert(), make sure units of every series-id with same metric name will be converted to the largest one among them.
> libpcp_web: Keeping meta-data qualifiers in canonical expressions

- GNUmakefile
- build/tar/checkdirs
- build/tar/postinstall.tail
- build/tar/preinstall.tail
- man/man3/pmnotifyerr.3
- qa/025
- qa/1248.out
- qa/1249
- qa/1249.out
- qa/1763
- qa/1763.out
- qa/admin/show-me-all
- qa/group
- qa/src/pmcdgone.c
- src/libpcp_pmda/src/open.c
- src/pmdas/rpm/Install
- src/pmlogctl/pmlogctl.sh
- src/zabbix-agent/src/GNUmakefile
Lots of little stuff here.
I'd like to get the QA stuff in before tonight's CI QA run, so I plan to merge this once the CI builds are done and seek retrospective reviews for the code parts of this PR.
> qa, libpcp_pmda, pmlogctl, tarball builds

- src/pmdas/activemq/ActiveMQ.pm
- src/pmdas/activemq/ActiveMQTest.pl
- src/pmdas/activemq/CacheTest.pl
- src/pmdas/activemq/JVMGarbageCollectionTest.pl
- src/pmdas/activemq/JVMMemoryPoolTest.pl
- src/pmdas/activemq/JVMMemoryTest.pl
- src/pmdas/activemq/QueueTest.pl
- src/pmdas/activemq/RESTClient.pm
- src/pmdas/activemq/RESTClientTest.pl
When running the pdma we found a few issues.
* Invalid Header "http://localhost"
* Unable to load new from Queue ...
This PR resolves these issues.
> Fixing runtime and compile issues with the activemq pdma

- docs/index.rst
- docs/specs/openapi.yaml
This PR contains the following changes:
1. REST API Guide is added in toctree for easier navigation.
2. Description of API response is changed from `successful operation` to `OK`.
> [docs] Modifications in REST API

- src/libpcp_web/src/http_client.c
Added more detailed debugging for http based pdma's
> Add better http debugging

- src/pmdas/apache/apache.c
Increased the buffer size to allow for larger responses from apache.
> Increased buffer size to allow for multiple reads of the stream.

- src/libpcp_web/src/query.c
Fix multiple HMSET calls when querying time series expression.
TODO:
- set sources to all-zeros for expressions’ descs
- fix issue #1155
- Remove metric names requets
> Fix issue #1157 multiple HMSET calls

- docs/UAG/AboutUAGGuide.rst
- docs/UAG/TimeSeriesQuerying.rst
- docs/index.rst
Closes #1096.
This PR adds a new chapter - **Fast, Scalable Time Series Querying - pmseries** in the User's and Administrator's Guide book.
> [docs] pmseries(1) chapter added in UAG book

- src/pcp/atop/netproc.c
create a pid-indexed hash to avoid the O(n*m) nested loop
> atop: improve task/netproc instance matching algorithm

- qa/1530.out
- qa/1533.out
- src/pmdas/linux_zfs/help
> Linux zfs help text

- qa/1689.out
- src/libpcp_web/src/discover.c
- src/libpcp_web/src/discover.h
- src/libpcp_web/src/schema.c
- src/pmrep/conf/pmproxy.conf
see 7aed88c9dbb and fc246398ead for issue #1283
> pmproxy/libpcp_web: throttle discovery callbacks to improve scalability and other improvements

- debian/GNUmakefile
- debian/control.pcp
- debian/control.pcp2xlsx
- debian/fixcontrol
Resolves https://github.com/performancecopilot/pcp/issues/1288
> build: fix debian builds with missing openpyxl packages

- man/html/guide.html
See individual commits for details.
> Some fixes to the guide

- qa/1051.out.linux
- src/pmieconf/.gitignore
- src/pmieconf/GNUmakefile
- src/pmieconf/power/localdefs
- src/pmieconf/power/thermal_throttle
> pmieconf: detect sustained CPU thermal throttling

- src/libpcp_web/src/discover.c
- src/libpcp_web/src/maps.c
5e3b792d3 libpcp_web: plug mem leak in redisMapInsert during daily log-rolling
2a00a90b0 libpcp_web/discovery: improve lock handling and scalability
earlier related commits are already in main branch
> Improve pmproxy and libpcp_web scalability

- src/pmdas/statsd/README.md
- src/pmdas/statsd/pmdastatsd.1
Additionally, some minor edits so that man page doc and readme doc are more similar.
> fix(statsd): docs mentioned hardcoded agent stat that was not present and omitted few of those that present were

- configure
- configure.ac
- src/include/builddefs.in
Very handy for data race detection and much more, see
https://github.com/google/sanitizers/wiki
> build: optionally enable sanitizers

- qa/1434
- qa/1434.out
- qa/1435
- qa/1435.out
- qa/1436
- qa/1436.out
- src/pmdas/bcc/Upgrade
- src/pmdas/elasticsearch/Upgrade
- src/pmdas/mssql/Upgrade
- src/pmdas/nfsclient/Upgrade
- src/pmdas/openmetrics/Upgrade
- src/pmdas/postgresql/Upgrade
> Fix a PMDA upgrade issue relating to python vs python3 switch

- qa/1829
- qa/1829.out
- qa/group
- src/pmlogrewrite/label.c
- src/pmlogrewrite/logger.h
- src/pmlogrewrite/pmlogrewrite.c
- src/pmlogrewrite/result.c
Adds new test qa/1829 to exercise this functionality.
Resolves #1386
> pmlogrewrite: add support for producing version 3 archives

- src/pmdas/ds389/pmdads389.pl
Fix of a syntax error in pmdads389.pl .
This pull request partially fixes [bz1966122 ](https://bugzilla.redhat.com/show_bug.cgi?id=1966122).
> Fix of a syntax error in pmdads389.pl

- qa/1875
- qa/1875.out
- qa/group
- src/libpcp_web/src/slots.c
- src/pmproxy/pmproxy.conf
> libpcp_web: support Redis authentication with password and Redis ACL

- src/pmdas/bcc/modules/biotop.python
- src/pmdas/bcc/modules/execsnoop.python
- src/pmdas/bcc/modules/profile.python
- src/pmdas/bcc/modules/tcplife.python
- src/pmdas/bcc/modules/tcpperpid.python
- src/pmdas/bcc/modules/tcptop.python
- src/pmdas/bcc/pmdautil.python
- src/pmdas/netcheck/pmdautil.python
Fixes "W1505: Using deprecated method setDaemon()"
> qa: resolve new pylint warnings in f35 python

- qa/1355
- qa/1355.out
- qa/group
- qa/src/GNUlocaldefs
- qa/src/redis_proxy.python
- src/libpcp_web/src/exports
- src/libpcp_web/src/load.c
- src/libpcp_web/src/schema.c
- src/libpcp_web/src/schema.h
- src/libpcp_web/src/slots.c
- src/libpcp_web/src/slots.h
- src/pmproxy/src/redis.c
* switch from a boolean 'setup' to a state (connecting, connected,
ready, ...) for Redis connection state
* handle Redis disconnects in the async reply handler
* in a timer, check if the current state is disconnected and issue a
reconnect
> pmproxy: transparent Redis reconnect

- qa/1784
- qa/1784.out
- qa/894
- qa/group
- src/pmlogconf/pmlogconf.c
> pmlogconf: resolve issues in persisting changes to pmlogger config

- docs/QG/AddNewMetrics.rst
- docs/QG/ExportMetricValues.rst
- docs/QG/GraphPerformanceMetric.rst
- docs/QG/QuickGuides.rst
- docs/QG/RecordHistoricalValues.rst
- docs/QG/RecordMetricsFromRemoteSystem.rst
- docs/QG/RecordMetricsOnLocalSystem.rst
- docs/QG/SetupAutomatedRules.rst
This PR contains the Quick Guides (Ch. 1 to 9) in reStructured Text (rst) format.
> [docs] Quick Guides

- src/python/pmapi.c
- src/python/pmda.c
Removes use of (internal-only) libpcp.h and deprecated.h headers
from the python/C wrapper glue code.  Achieved via a combination
of dropping unused code (timevalSleep), local declarations of a
few (mainly options related) internal APIs, dropping a DBG_TRACE
macro usage, allowing use of system headers like <pcp/pmapi.h> &
<pcp/pmda.h> if local git copies not found, and use of the newer
pmID_item/pmID_cluster interfaces instead of __pmID_int.
Resolves https://github.com/performancecopilot/pcp/issues/1481
> python api: updates to allow building from outside git repo

- docs/QG/AutomateProblemDetection.rst
- docs/QG/QuickGuides.rst
This PR contains the Chapter-6 : Automate performance problem detection of Quick Guides in reStructured Text (rst) format.
> [docs] Quick Guides : Ch-6

- docs/QG/QuickGuides.rst
This PR removes the 'chapter' keyword from the Quick Guides main page.
> [docs] Improvements in docs

- src/pmdas/mmv/src/mmv.c
Update MMV to use the native filesystem mtime timestamp for the
directory modification checks.  This attempts to resolve a race
Ken is observing in qa/1626 where multiple pmproxy MMV mappings
are created in close succession.
> pmdammv: use highest available timestamp resolution for checks

- qa/455
- src/pmdas/rsyslog/pmdarsyslog.1
- src/pmdas/rsyslog/pmdarsyslog.pl
Based on work from Christian Horn (@christianhorn) at: https://fluxcoil.net/files/tmp/pmdarsyslog.pl.chorn.
> Add support for rsyslog resource, action, omfwd, imudp, and imptcp statistics

- src/libpcp_web/src/discover.c
Refactor and simplify pmDiscoverDecodeMetaInDom() to use __pmLogLoadInDom()
from libpcp with a NULL __pmArchCtl (i.e. pre-loaded buffer), instead of
open coding. The library function handles all three variants of indom
archive records - indom, indom_v2 and delta indom.
Do not free the resulting pmInResult in pmDiscoverInvokeInDomCallBacks()
because the buffer is managed (and re-used) by process_metadata().
qa for groups pmproxy and libpcp_web are passing and there is no
evidence of memory leaks. QA for v3 and delta indoms needs to be
checked too.
Resolves: https://github.com/performancecopilot/pcp/issues/1548
> libpcp_web: support v3 indom and indom_delta in discovery ingest

- INSTALL.md
Update INSTALL.md to add sudo su to prevent install from failing if the user is not root and tries to install via the sudo privilege.
> Update INSTALL.md to add sudo su

- qa/1900
- qa/1900.out
- qa/group
- qa/src/.gitignore
- qa/src/GNUlocaldefs
- qa/src/wait_for_values.c
> pmdabpf valgrind tests

- src/pmdas/denki/denki.c
Only consider a directory in /sys/class/power_supply as relevant, when one of charge_now, energy_now, power_now exists there.
With this change, directories there which have type=Battery (so far the only criteria), but do not report actual chargelevel or consumption, get now ignored.
> Better checks if we are really dealing with battery metrics

- build/ci/platforms/fedora36-container.yml
https://bugzilla.redhat.com/show_bug.cgi?id=2069189
> ci: revert workaround for pylint on F36 (BZ 2069189)

- qa/1856
- qa/1856.out
- qa/group
- src/pcp/dstat/pcp-dstat.1
- src/pcp/dstat/pcp-dstat.5
- src/pcp/dstat/pcp-dstat.py
- src/pcp/dstat/plugins/topbio
- src/pcp/dstat/plugins/topchildwait
- src/pcp/dstat/plugins/topcpu
- src/pcp/dstat/plugins/topio
- src/pcp/dstat/plugins/topmem
> pcp-dstat: implement support for the top-alike plugins

- Makepkgs
- configure
- configure.ac
- src/include/builddefs.in
- src/pmdas/bpf/modules/GNUmakefile
- src/pmdas/bpf/modules/common.h
- src/pmdas/bpf/modules/execsnoop.c
- src/pmdas/bpf/modules/execsnoop.h
and create symlinks for required source files only
> pmdabpf: check libbpf version before including execsnoop

- src/pmdas/openvswitch/pmdaopenvswitch.python
Added code to parse OVS Interface stats
> Changes to parse Interface stats

- build/rpm/pcp.spec.in
- build/rpm/redhat.spec
- src/pmdas/openvswitch/GNUmakefile
- src/pmdas/openvswitch/openvswitch.errors.pmie
- src/pmdas/openvswitch/openvswitch.rx_drops.pmie
- src/pmdas/openvswitch/openvswitch.tx_drops.pmie
From collaboration with Veda Barrenkala <vbarrenk@redhat.com>
> pmieconf: add drops/errors pmie rules for openvswitch metrics

- src/libpcp_web/src/GNUmakefile
Add query.o with its required files and remove query_parser.o (no such file)
> libpcp_web: modify libpcp_web make file

- qa/1691
- qa/1691.out
- qa/group
- src/libpcp_web/src/load.c
- src/libpcp_web/src/schema.h
> libpcp_web: honor exclude.metrics setting in pmseries --load

- .github/workflows/ci.yml
- .github/workflows/qa.yml
- .github/workflows/release.yml
- Vagrantfile
- build/ci/platforms/ubuntu2204-container.yml
- build/ci/platforms/ubuntu2204.yml
- qa/admin/package-lists/Ubuntu+22.04+x86_64
- qa/admin/qa-summary
Addresses most of #1609.
The main thing here is the package list.
The remainder will require some review and testing in proper CI environment.
Open issues are mentioned in #1609.
> Ubuntu 22.04 (jammy) support

- src/pmdas/openvswitch/GNUmakefile
- src/pmdas/openvswitch/openvswitch.mtu_exceeded_drops.pmie
- src/pmdas/openvswitch/openvswitch.rx_qos_drops.pmie
- src/pmdas/openvswitch/openvswitch.tx_failure_drops.pmie
- src/pmdas/openvswitch/openvswitch.tx_qos_drops.pmie
- src/pmdas/openvswitch/openvswitch.tx_retries.pmie
- src/pmdas/openvswitch/openvswitch.vhost_notification.pmie
- src/pmdas/openvswitch/openvswitch.vhost_tx_contention.pmie
Ovs pmie rules provide rules that track various ovs counters.
> Ovs pmie rules

- src/libpcp_web/src/discover.c
Related to a qa/1662 failure observed on several hosts where
the context baton is not being cleaned up successfully.
> libpcp_web: add missing discovery code on_closed callback

- build/rpm/GNUmakefile
- build/rpm/pcp.spec.in
- build/rpm/redhat.spec
- configure
- configure.ac
- debian/GNUmakefile
- debian/pcp-testsuite.install
- debian/pcp-testsuite.sysusers
- debian/pcp.sysusers
- qa/.gitignore
- qa/GNUmakefile
- qa/pcpqa.user.in
- src/include/.gitignore
- src/include/GNUmakefile
- src/include/pcp.conf.in
- src/include/pcp.user.in
> packaging: support dynamic systemd allocation of system uid/gid

- src/pmdas/linux_sockets/ss_parse.c
fixed some indents so that its easy to read the codes
> ss_parse: indentation and white space changes

- src/pcp/GNUmakefile
- src/pcp/ps/pcp-ps.1
- src/pcp/ps/pcp-ps.py
1 Cleaned up the code which was troubling in pylint
2 Removed the handing for -s/-a option entirely now this will be handled by pcp infra 
3 Reworked to through only one instance of data like ps(1) and tried to match colums with ps.
4 Cleaned up man page for pcp-ps
> pcp-ps: Merge request comment rework

- src/pmdas/openvswitch/openvswitch.rx_qos_drops.pmie
Signed-off-by: Veda Barrenkala <vedabarrenkala@gmail.com>
> Open vSwitch spelling correction

- src/pcp/ps/pcp-ps.py
As extraoption arguments we incorrect so it as not able to override.
> Fixed pcp-ps -o option working

- configure
- configure.ac
close #1701
Fixes: a29b96855 ("pmdabpf: add CO-RE biosnoop")
> pmdabpf: fixup: add biosnoop into $(PMDABPF_MODULES)

- qa/1810
- qa/1810.out
> pmdabpf: fix qa/1810 (oomkill) to run in limited memory footprint

- src/pcp/ps/pcp-ps.py
- src/pcp/ps/test/process_state_util_reporter_test.py
- src/pcp/ps/test/process_statusutil_test.py
pcp-ps might report an Exception ignored in <_io.TextIOWrapper due to the python flush calls in destructor for more info check this python issue:-
https://bugs.python.org/issue11380
fixed several automated test in process_state_util_reporter_test.py and process_state_util_reporter_test.py due to the output mismatch in assertEqual function
> pcp-ps:fix exception ignored and automated functionality tests errors

- src/pcp/dstat/pcp-dstat.py
> Fixed dstat CSV output process.

- build/rpm/redhat.spec
- qa/admin/package-lists/Fedora+39+x86_64
Related to Red Hat BZ #2155256
> build: temporarily workaround pyodbc failure with latest python

- src/pmlogredact/pmlogredact.sh
> Fix of missing exit code setup in pmlogredact

- src/pmdas/bpftrace/bpftrace/process_manager.py
Resolves an issue Ken noticed in the bpftrace PMDA during shutdown - reproducible via regression test qa/1700 ...
```
File "/usr/libexec/pcp/pmdas/bpftrace/bpftrace/process_manager.py", line 84, in stop_bpftrace_process
_done, pending = await asyncio.wait({process.wait()}, timeout=5)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/asyncio/tasks.py", line 415, in wait
raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```
> pmdabpftrace: rework exit/wait handling to avoid errors

- configure
- configure.ac
- src/include/buildrules
- src/perl/LogImport/Makefile.PL
- src/perl/MMV/Makefile.PL
- src/perl/PMDA/Makefile.PL
- src/python/GNUmakefile
Attempting to get a clean build across both x86_64 (GH CI) and Mac M1 laptops.
> build: drop MacOS universal binaries, too complicated now (with arm64 also)

- .github/workflows/main.yml
Added "file:" to main.yaml to fix the error where the Dockerfile could not be found.
> Fix unresolved dockerfile in main.yaml

- qa/1921
- qa/1921.out
- qa/group
- src/pcp/ss/pcp-ss.1
- src/pcp/ss/pcp-ss.py
Minor updates to the documentation of -r/-n options as well.
Resolves Red Hat bug RHEL-17335
> pcp-ss: fix handling of listening state sockets to match ss(1)

- build/rpm/redhat.spec
> build: post-el9 systemd-presets manages pmcd/pmie/pmlogger enabling

- configure
- qa/1264
- qa/1264.out
- qa/group
- src/pcp/atop/atopsar.c
- src/pcp/atop/drawbar.c
- src/pcp/atop/parseable.c
- src/pmdas/bpf/bpf.conf
- src/pmdas/bpf/modules/GNUmakefile
- src/pmdas/bpf/modules/module.h
- src/pmdas/bpf/modules/netatop.bpf.c
- src/pmdas/bpf/modules/netatop.c
- src/pmdas/bpf/modules/netatop.h
Add a bpf per process network metric PMDA which exposes per process network metrics using netatop-bpf.c. Add display of metrics to atop. Add test for network metrics.
> Add PCP netatop BPF PMDA to extract per process network statistic.

- build/ci/test-report.py
The 'Parse test results' phase of CI is sometimes failing with
File "/home/runner/work/pcp/pcp/build/ci/test-report.py", line 83, in read_testlog
with open(os.path.join(qa_dir, test_no), encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './qa/4334'
I suspect this maybe a variant on the case handled at the end of read_testlog, where we matched something in a failed tests output. Handle this new scenario too and continue bravely on...
> build: handle missing test file in test-report.py read_testlog()

- build/rpm/pcp.spec.in
- build/rpm/redhat.spec
Updated spec files to allow for the generating of new pcp-export-pcp2openmetrics packages
> updated spec files to accomodate addition of pcp2openmetrics tool

- qa/821.out
- src/pmdas/linux/help
- src/pmdas/linux/pmda.c
- src/pmdas/linux/proc_vmstat.h
- src/pmdas/linux/root_linux
> pmdalinux: two additional /proc/vmstat khugepaged metrics

- build/rpm/pcp.spec.in
- build/rpm/redhat.spec
> build: add missing python rpms to pcp-testsuite deps

- src/pmlogdump/pmlogdump.c
> pmlogdump: fix -V/--version option handling

- .gitignore
- GNUmakefile
- tmpfiles.init.setup.in
- tmpfiles.run.setup.in
> tmpfiles.d: extend the tmpfiles.d directory set to logdirs

- src/pcp2openmetrics/pcp2openmetrics.1
added missing hypen to pcp2openmetrics man page
> added missing hypen to pcp2openmetrics man page

- qa/1619
- qa/1619.out
- qa/group
- src/pmdas/bcc/Upgrade
- src/pmdas/elasticsearch/Upgrade
- src/pmdas/mssql/Upgrade
- src/pmdas/nfsclient/Upgrade
- src/pmdas/openmetrics/Upgrade
- src/pmdas/postgresql/Upgrade
Resolves Red Hat issue RHEL-40631
> pmcd scripts: ensure pmcd.conf not rewritten on every restart

- build/rpm/pcp.spec.in
- build/rpm/redhat.spec
- qa/1564
- qa/1564.out
- qa/group
- src/pcp/GNUmakefile
- src/pcp/xsos/.gitignore
- src/pcp/xsos/GNUmakefile
- vendor/github.com/performancecopilot/xsos-pcp/README.md
- vendor/github.com/performancecopilot/xsos-pcp/pcp-xsos
- vendor/github.com/performancecopilot/xsos-pcp/pcp-xsos.1
Tool and docs here, QA to follow shortly.
> Add pcp-xsos utility for Red Hat customer support

- src/pmdas/bpf/bpf.c
On older Linux kernels (pre 5.11) running multiple BPF applications may exceed the locked pages limit (RLIMIT_MEMLOCK) imposed in pmdabpf and prevent additional BPF applications from starting.  The pmdabpf has been changed to remove any locked page limit to elimitate this arbitrary limit interferring with BPF application startup.  This patch is based on the proposed patch from Nathan Scott in the issue.
Resolves: https://github.com/performancecopilot/pcp/issues/1915
> Avoid too-low rlimit limit for pmdabpf

- src/selinux/pcp.te
There were some selinux AVCs observed when testing ansible-pcp that this commit resolves.
> Fix selinux AVC denials

- src/libpcp_web/src/schema.c
Fix a situation where we were logging the last seen instance values more often than we need to in pmproxy log discovery - resolved by honouring the existing flags for values updating on the previous observed sample.
> pmproxy, libpcp_web: restrict values cached to latest changes

- qa/744
- qa/744.out
- src/pmdas/nvidia/localnvml.c
Resolves Red Hat issue RHEL-80722
> pmdanvidia: if present, use dso from the libnvidia-ml runtime package

- src/pcp/atop/netprocmetrics.map
- src/pmlogconf/networking/perprocess-linux
> BCC vs bpf proc net metrics

- qa/src/.gitignore
- qa/src/GNUlocaldefs
- qa/src/sha1ext2int.c
- src/libpcp_web/src/discover.c
- src/libpcp_web/src/schema.c
Resolves a corner case where some instances names and labels could not be looked up by Grafana.
> Improve pmseries handling of hotproc instances

- qa/1585
- qa/1585.out
- qa/group
- src/pcp2arrow/pcp2arrow.1
- src/pcp2elasticsearch/pcp2elasticsearch.1
- src/pcp2graphite/pcp2graphite.1
- src/pcp2influxdb/pcp2influxdb.1
- src/pcp2json/pcp2json.1
- src/pcp2openmetrics/pcp2openmetrics.1
- src/pcp2spark/pcp2spark.1
- src/pcp2template/pcp2template.1
- src/pcp2xml/pcp2xml.1
- src/pcp2zabbix/pcp2zabbix.1
- src/pmrep/pmrep.1
> Add qa, man for the pmfg discrete change

- src/derived/iostat.conf
Resolves Red Hat issue RHEL-85451
> pmdalinux: improve helptext for disk util metrics reporting >100%

- qa/1569.out
As new pcp-meminfo qa archive has been checked in by [pull request 158](https://github.com/performancecopilot/pcp/pull/2180)
> QA: updated 1569 test result 

- debian/changelog
- src/pcp/htop/GNUmakefile
- src/pminfo/GNUmakefile
> build: fixes for reverse makefile target prereq resolution

- src/python/pmda.c
Fix of a (de)reference of a tuple in python/pmda.c
Resolves bz2371769
> Fix of python3-pcp issue on Python-3.14

- src/pmdas/hdb/pmdahdb.python
- src/pmdas/hdb/pmlogconf.summary
This PR looks to improve the efficiency of fetching metrics using pmdahdb by batching sql queries together for metrics from the same table rather than running a new query for each metric.
> batch sql statements to improve efficiency

- qa/archives/GNUmakefile
- qa/archives/mk.amdgpu
> qa: add a script to generate an archive with AMD GPU metrics

- qa/archives/GNUmakefile
- qa/archives/mk.nvidiagpu
> qa: add a script to generate an archive with NVIDIA GPU metrics

- src/pmdas/hacluster/pacemaker.c
Fix potential buffer overflow condition in when collecting node type in hacluster_refresh_pacemaker_nodes()
> pmdahacluster: Fix potential buffer overflow condition in pacemaker.c

- src/libpcp_web/src/discover.c
- src/libpcp_web/src/load.c
- src/libpcp_web/src/query.c
- src/libpcp_web/src/schema.c
- src/libpcp_web/src/search.c
- src/libpcp_web/src/slots.c
- src/libpcp_web/src/util.h
- src/libpcp_web/src/webgroup.c
> libpcp_web memory leak fixes on error paths

- src/pmdas/bpftrace/bpftrace/process_manager.py
- src/pmdas/bpftrace/bpftrace/service.py
> pmdabpftrace: adjust asyncio code to work on rawhide python 3.14

- src/dbpmda/src/dso.c
- src/libpcp/src/access.c
- src/libpcp3/src/access.c
- src/pmcd/src/config.c
Took  look at the these Coverity issues and they look to be relatively safe to quiet.
> Some minor fixes to eliminate some Coverity warnings
