src/pmlogger/pmlogger.service.in

When pmlogger and pmcd are started at the same time by systemd (as
happens during system boot), we need to make sure that pmlogger is not
activated before pmcd is ready to accept connections from clients.

pmlogger: Ensure that pmlogger starts after pmcd.

---

man/man1/pcp2graphite.1

Signed-off-by: Luca Miccini lmiccini@redhat.com

[pcp2graphite] document systemd service file template in manpage

---

src/python/pcp/pmsubsys.py

Found memory leaks in python pmsubsys module. pmFreeResult needs to be called to release metric_result previously allocated by pmFetch.

Fixed memory leak in python module pmsubsys.py

---

src/pmdas/linux/help
src/pmdas/linux/pmda.c
src/pmdas/linux/proc_partitions.c
src/pmdas/linux/root_linux

Linux pmda reports less disk IO stats for disk.partitions comparing to disk.dev and disk.dm. Added the following metrics which are currently missing for kernel 2.6.25 and above:
disk.partitions.read_merge
disk.partitions.write_merge
disk.partitions.avactive
disk.partitions.aveq
disk.partitions.read_rawactive
disk.partitions.write_rawactive 
Reference: 
https://www.kernel.org/doc/Documentation/iostats.txt (Disks vs Partitions)

[linux_pmda] Added extended disk partition stats for kernel 2.6.25 and above

---

src/python/pcp/pmapi.py

When calling Python pmapi functions such as ```pmGetChildren```, ```pmGetInDom```, etc. these functions internally allocate resources using ```malloc```. Unfortunately the current code on Windows crashes when ```free```'ing these resources because the ```free``` function used doesn't always belong to the correct ```msvcrt.dll``` version.
AFAIK artifacts (.exe's, .dll's, etc) compiled using mingw64 are always linked with ```\Windows\System32\msvcrt.dll```, but Python is not necessarily. E.g:
```
C:\>\Python27\python
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import CDLL
>>> from ctypes.util import find_library
>>> LIBC_OK = CDLL(find_library("msvcrt"))
>>> …
```

mingw64: Python pmapi on Windows - prevent crash when free()'ing resources

---

src/pmdas/windows/pmda.c

The ```mem.cache.bytes``` metric is collecting data from an incorrect Performance Counter: ```\Memory\Pages Faults/sec```. This patch fixes that by pointing to ```\Memory\Cache Bytes```. Also fixed the data types (U32 -> U64) and semantic interpretation (COUNTER -> INSTANT). For consistency, changed ```\Metric\Cache Bytes Peak``` data type (64 -> U64) as well.

Windows: Fix Performance Counter for mem.cache.bytes

---

src/pmdas/dm/GNUmakefile
src/pmdas/dm/dmthin.data_high_util.pmie
src/pmdas/dm/dmthin.metadata_high_util.pmie

dmthin pool data and metadata high utilization pmieconf scripts.

dmthin pmieconf scripts

---

scripts/bintray-upload

Bintray provide a "Set Me Up" button which provides copy-paste commands to install a Debian repo into apt.
However, the current instructions don't work, they currently suggest to paste "deb https://dl.bintray.com/pcp/trusty {distribution} {components}" but apt requires the last to fields to be something like "trusty main" or "jessie main".
This patch sets the "distribution" and "components" Debian repo properties using the Bintray HTTP headers as documented at https://bintray.com/docs/api/#_debian_upload and so should correct the "Set Me Up" commands so users can copy-paste the provided instructions.

[bintray] add Debian repo HTTP headers

---

src/pcp2graphite/pcp2graphite.py

Before this change "pickled_input" variable was appended and metrics send over and over again.
Time to send metrics to graphite dropped for me from 6 minutes to 2 seconds.

pcp2graphite improvement: send all metrics at once in pickled mode

---

src/pcp/dmcache/pcp-dmcache.py

small patch making the lvname column width dynamic, so names aren't truncated. This truncation was becoming more of a problem with thinpools, since adding a cache to a thinpool has been introduced which adds _tdata to the end of the LV name

Pcp dmcache fix

---

man/html/guide.html

The docs were telling users to write to /etc/pcp/pmmgr/target-discover
Signed-off-by: Zack Cerza <zack@redhat.com>

Fix typo: /etc/pcp/pmmgr/target-discovery

---

src/python/pcp/mmv.py

@fche and I were able to fix issues with the Python bindings.  These patches fixed the problems on my end.

Fixes crashes and problems updating metrics

---

man/man1/pmwebd.1

The default pmwebd context timeout of 300 seconds is not documented in the manpage.

Document default pmwebd context timeout

---

src/pcp/pidstat/pcp-pidstat.py

Fixed floating point precision for total_percent()
Fixed argument parsing for -P
Changed `-P` to `-p` to match with the original pidstat :)

pcp pidstat fixes

---

qa/883.out
src/pcp/mpstat/pcp-mpstat.1
src/pcp/mpstat/pcp-mpstat.py

Use '%x' format with strftime to display date, add documentation to override this setting and fix qa

pcp-mpstat: change machine info header

---

src/GNUmakefile
src/python/GNUmakefile
src/python/pcp/pmapi.py
src/python/test/pmerr_test.py

Exposes the error code that the exception was raised with via the `errno` attribute. This follows the convention of Python built-in exceptions.

python: add errno attribute to pmErr class

---

src/pmdas/libvirt/pmdalibvirt.python

... considering that it's likely in error in the libvirt upstream.

relaxing the specificity of the cpu_cycle metric's documentation

---

src/perl/MMV/GNUmakefile

server.pl has executable permission, so there is no need to keep this line.

this line break building on macOS

---

build/containers/pcp-go-app/Dockerfile

@natoscott I have added a simple container that installs speed and builds all examples.
Go installation is from the official library image.

initial implementation of speed container

---

man/man1/pmdaperfevent.1
qa/perfevent/GNUmakefile
qa/perfevent/config/test_dynamic_counters.txt
qa/perfevent/perf_event_test.c
src/pmdas/perfevent/GNUmakefile
src/pmdas/perfevent/architecture.c
src/pmdas/perfevent/architecture.h
src/pmdas/perfevent/configparser.h
src/pmdas/perfevent/configparser.l
src/pmdas/perfevent/parse_events.c
src/pmdas/perfevent/parse_events.h
src/pmdas/perfevent/perfevent.conf
src/pmdas/perfevent/perfinterface.c
src/pmdas/perfevent/perfinterface.h
src/pmdas/perfevent/pmda.c

The perfevent pmda gets the event definitions from the libpfm
library. So, to add a new platform counter, we need to add its
definition to the libpfm library and use it here. This patch is the
first step towards removing that dependency. It parses the kernel
exported PMUs and their events from /sys/bus/event_source/devices, and
calculates the config values for each of these events. However, we don't
want to open all the events at once. Only the events which are mentioned
in perfevent.conf under [dynamic] section will be opened. But, all the
dynamic events will be listed with pminfo.
For e.g. :
$ pminfo
[...]
perfevent.hwcounters.software.context-switches.dutycycle
perfevent.hwcounters.software.context-switches.value
perfevent.hwcounters.software.page-faults.dutycycle …

perfevent_pmda: Add PMU events exported from kernel

---

src/pmdas/perfevent/parse_events.c
src/pmdas/perfevent/parse_events.h
src/pmdas/perfevent/perfinterface.c

The perfevent pmda code initializes/parses a cpumask for each
PMU. Previously, it used to allocate a memory block with max available
cpus from archinfo->cpulist. And, then, it finds out the list of
allowable cpus on which events of a certain PMU can be monitored. That
causes an issue with the test case test_dynamic_events_config, in which,
the archinfo->cpulist initialized (from the system) may be less than the
cpumask available for a pmu in this test case. If that's the case, it
will cause a sigsegv, since, it tries to parse more cpus than the
allocated space.
This PR fixes this issue by allocating the appropriate space by first
looking at the cpumask and then parsing it.

perfevent_pmda: Fixes a sigsegv for test_dynamic_events_config

---

src/pmrep/pmrep.py

654d0c0 addressed this properly in libpcp so drop the Python workaround.

pmrep: fix now unneeded workaround

---

src/pmdas/libvirt/pmdalibvirt.python

For an overview, see
https://groups.io/g/pcp/message/15733
For more details on the new perf metrics, see
https://libvirt.org/formatdomain.html
For explanation on some of the block metrics, see
https://www.berrange.com/posts/2017/02/10/the-surprisingly-complicated-world-of-disk-image-sizes/

libvirt pmda: add new block, perf, vcpu metrics

---

src/pmmgr/pmmgr.cxx

Fix a scoping issue in one of my recent commits.  Thanks to Frank for pointing this out.

Fix conditional scope for pmlogger-timefmt change

---

src/pmdas/mysql/pmdamysql.pl

Corresponding lines from SHOW SLAVE STATUS:
```
SQL_Delay: 0
SQL_Remaining_Delay: NULL
```
One problem i noticed is that SQL_Delay and SQL_Remaining_Delay can be both int and NULL.
This also applies to Seconds_Behind_Master which is PM_TYPE_U32 right now.

Additional slave metrics for MySQL PMDA

---

qa/1192
qa/1192.out
qa/GNUmakefile
qa/GNUmakefile.install
qa/prometheus/GNUmakefile
qa/prometheus/GNUmakefile.install
qa/prometheus/prometheus_client_server.python
src/pmdas/prometheus/acme.py
src/pmdas/prometheus/pmdaprometheus.python
src/python/pcp/pmda.py
src/python/pmda.c

For parallel http fetches, multiple threads are used when the context is with the python interpreter, which I believe fixes #313. Sub-process watches for any changes in the endpoint metrics metadata and uses diffing strategy to add/remove only changed metrics, which fixes #308. 
Thanks!

Prometheus: add auto metadata refresh and indom cache fixes

---

src/pcp/pidstat/pcp-pidstat.py
src/pcp/pidstat/test/cpu_usage_reporter_test.py
src/pcp/pidstat/test/process_memory_util_reporter_test.py
src/pcp/pidstat/test/process_priority_reporter_test.py
src/pcp/pidstat/test/process_stack_util_reporter_test.py

As per #blockprocs channel, fix for the unit tests. Don't worry about merging the PR through the github workflow (assuming thats still the case), just grab the branch from our fork.

pidstat: fix failing unit tests

---

src/pmdas/perfevent/parse_events.c

I noticed these two errors while inspecting the code to track down the
cause of the problem in #331.
The real question is why valgrind didn't find the uninitialised *line. I (temporarily) changed the compiler flags to -O2 for the test harness and low-and-behold valgrind noticed the uninitialized variable in the original code:
```
==28987== Conditional jump or move depends on uninitialised value(s)
==28987==    at 0x51ABF32: getdelim (iogetdelim.c:63)
==28987==    by 0x40AFF6: getline (stdio.h:117)
==28987==    by 0x40AFF6: setup_cpu_config (parse_events.c:743)
==28987==    by 0x4087ED: perf_setup_dynamic_events (perfinterface.c:714)
==28987==    by 0x40A030: perf_event_create (perfinterface.c:1236)
==28987==    by 0x40445B: test_dynamic_events_config (perf_event_test.c:822)
==28987== …
```

Uninitialised variable & resource leak.

---

qa/perfevent/config/test_only_dynamic_events.txt
qa/perfevent/perf_event_test.c
src/pmdas/perfevent/configparser.l

When the entire perfevent.conf file is empty and only the
[dynamic] section is present, configparser.l doesn't parse
this section because of the given check for pmc settings.
This patch moves the parsing before the check.

pmda_perfevent: Fix non-showup of dynamic events

---

qa/1068
qa/1068.out
src/GNUmakefile
src/pcp2elasticsearch/GNUmakefile
src/pcp2elasticsearch/pcp2elasticsearch.py
src/pcp2json/GNUmakefile
src/pcp2json/pcp2json.py
src/pcp2xlsx/GNUmakefile
src/pcp2xlsx/pcp2xlsx.py
src/pcp2xml/GNUmakefile
src/pcp2xml/pcp2xml.py
src/pcp2zabbix/GNUmakefile
src/pcp2zabbix/pcp2zabbix.py
src/pmrep/pmrep.1
src/pmrep/pmrep.conf
src/pmrep/pmrep.conf.5
src/pmrep/pmrep.py
src/python/pcp/__init__.py
src/python/pcp/pmapi.py
src/python/pcp/pmconfig.py

A new tightly coupled PMConfig class for Python utilities is introduced (perhaps think of C++ friend classes) which will take care of reading the configuration file, populating the metrics data for the utility, reading command line (remember that this required quite some effort earlier to get it right for all cases), registering derived metrics, and validating the metrics in the PMNS. Utilities will use the "standard" pmrep config file format and remain mostly compatible with pmrep and each other (utility specific options are of course not recognized by other tools, e.g., zabbix_port makes only sense with pcp2zabbix).
Another module with methods that can be called directly is added to set timezone, step mode, and PMAPI context connection. There seems to be little in this area which would …

pmrep modularization, add pcp2{es,json,xml,xlsx,zabbix}

---

qa/1069
qa/1069.out
src/python/pcp/pmconfig.py

Make sure command line options always override config file values.
Fixes #357.

pmconfig.py: handle option priorities correctly

---

src/pcp2zabbix/pcp2zabbix.py

stderr.write takes ("foo %s" % bar)  rather than ("foo %s", bar).

pcp2zabbix: fix python typo for formatting zabbix server error

---

man/man1/pmmgr.1
src/pmmgr/pmmgr.cxx

An assertion failure was formerly triggered, possibly by pmcds
advertising a blank hostname.  This code now assigns them a
hostid of "-".

pmmgr: tolerate pmcds with empty hostname

---

src/pmdas/perfevent/configparser.l

Fixes segfaults in case of empty pmc_settings.

pmda_perfevent: Add null checks for pmc_settings

---

src/pmdas/perfevent/configparser.l

setting_lists has to be assigned before the NULL check.

Rearrange pmcsetting list check

---

src/pmrep/pmrep.conf

Add a equivalent configuration for pmrep for "sar -n SOCK".  The "pmrep :sar-n-SOCK" metrics output matches up with the sar command that it modeled after.

pmrep.conf: Add sar-n-SOCK config

---

src/pmdas/json/Install
src/pmdas/json/config.json

To make it easier to use the PMDA JSON for dynamically created metrics
it creates a default directory ($PCP_TMP_DIR/json) for other
applications to place their metrics coded as json files in.  PMDA JSON
scans that directory for json files and it will pick up any new
metrics in the default directory automatically.

Have the PMDA JSON create a default place for json metrics

---

src/pmdas/dm/vdo.c

Updated vdo volume detection to be all subdirectories of /sys/kvdo/ which contain an 'instance' file. VDO volumes can have arbitrary names, causing the existence of the directory /sys/kvdo/[name], but all running VDO volumes have an 'instance' file in that subdirectory.

Recognize all VDO volumes

---

src/pmrep/pmrep.conf

PCP metrics were recently added for numa_hint_faults and
numa_hint_faults_local information from /proc/vmstat.  This pmrep
configuration computes a derived metric numa_hint_faults_remote. The
three numa hint fault metrics are displayed with percentages for the
local and remote faults to provide an indicatation whether there is a
problem with page locality on NUMA machines.

Add a pmrep configuration for numa hint faults metrics

---

man/man1/pmwebd.1
src/pmwebapi/pmgraphite.cxx

It was reported that on a large collection of pcp archives, which
included a number of corrupt (0-byte ones), the graphite
metric-enumeration query took too long.  One source of this was
excessive effort on
- frequently retrying opening corrupt archives, and
- fstat'ing all files under -A $DIR
We no longer do either.  Corrupt archives are treated as though they
were fresh at the moment of pmwebd startup, but containing no content.
The -A directory's transitive contents are no longer routinely
fstat()d, only readdir() enumerated.  This costs us the ability to
follow subdirectory symlinks, but it's a pretty big win otherwise.
No QA impact, only performance.

pmwebd: improve graphite archive-cache performance w.r.t. syscalls

---

src/pmdas/bcc/modules/biotop.python

updates for the BCC PMDA biotop tool: This patch ignores unnamed devices (device major number = 0, see https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/devices.txt) and logs traced devices which are not available in the `/proc/diskstats` file

BCC PMDA: biotop: ignore unnamed devices, log unknown devices

---

debian/pcp-manager.postinst
debian/pcp-webapi.postinst
debian/pcp.postinst.tail

On debian based systems, update-rc.d has different behavior for unit files generated via the sysv-generator versus native systemd units. As a result, PCP daemons are not enabled automatically. With this patch, deb-systemd-helper is used instead of update-rc.d, if it exists.

Fixes #454 - Enable daemons on debian based systems

---

.travis.yml
README.md
build/containers/travis-ci/Dockerfile

This PR integrates Travis CI.
It builds the PCP rpm packages inside a Docker image (Fedora 27) and executes the testsuite (with the `sanity` group).
Reason for using Docker inside the Travis CI VM is independence over the Travis CI VM image (at the moment Ubuntu 12.04 and Ubuntu 14.04 are available) and reproducibility.
Example build: https://travis-ci.org/andihit/pcp/builds/354788103
To enable the build on Travis CI, somebody with enough privileges of the GitHub pcp repo has to enable it on Travis CI.
The part where the generated RPM filenames is determined is a bit hacky, maybe somebody has a better idea?

integrate Travis CI

---

qa/661
qa/661.out
src/pmwebapi/pmresapi.cxx

When pmwebd is used for ordinary file service, it's desirable to allow
web browsers to cache those files.  This patch introduces simple
tagging of these files with the ETag: header (with some readily
available fstat(2) values as keys).  It now sends a 304 result code
instead of a 200 and a whole new copy of unmodified files.

pmwebd file service: add/check ETag header for 304 Not Modified results

---

qa/1116
qa/1116.out
qa/group

this test writes a testfile to `/var/tmp/pcp_qa_1116`, because a block device is required for the bcc tool (`/tmp` is tmpfs)
is this ok, or should I use another location for the testfile?

qa: add test 1116 for BCC PMDA biotop tool

---

man/man3/pmfetchgroup.3
qa/1069
qa/1069.out
src/libpcp/src/fetchgroup.c

The fetchgroup facility tries to optimize the instance profile to
minimize fetching of unnecessary instances.  The presence of
derived metrics (with opaque indom requirements of their own)
makes this optimization harmful.  New code disables it when
an IS_DERIVED() metric is added to the fetchgroup.  qa/1069 tests.

GH#451: fix fetchgroup vs derivedmetric instance profile kumite

---

qa/1068
qa/1068.out
src/pcp2zabbix/pcp2zabbix.1
src/pcp2zabbix/pcp2zabbix.py

Add new option --ldd = -l, to set a mode whereby pcp2zabbix
sends zabbix lld metrics for each pcp metric that has an indom.
This lld metric allows zabbix admins to configure templates
that grow automatically with pcp instance domains.  doc, qa++.

GH#439: add low-level-discovery support to pcp2zabbix

---

src/include/pcp/series.h

On C < ISO 2011, the repeated typedef of the same identifier is invalid.
To make series.h compilable on pre-std=c11 such as rhel6, add a 
#include "sds.h" and drop the duplicate typedef.

series.h: avoid redefining sds type

---

qa/common.bcc

python BCC module doesn't have a `__version__` attribute, therefore check for the DEBUG_BPF_REGISTER_STATE attribute (added in version 0.5.0)

qa: check if bcc module is version 0.5.0+

---

src/pmdas/bcc/modules/pcpbcc.python

cosmetic change to get ascending sorted histogram buckets:
```
ext4 open latency distribution
inst [0 or "0-1"] value 140636
inst [1 or "2-3"] value 15512
inst [2 or "4-7"] value 696
inst [3 or "8-15"] value 106
inst [4 or "16-31"] value 285
inst [5 or "32-63"] value 87
inst [6 or "64-127"] value 27
inst [7 or "128-255"] value 11
inst [8 or "256-511"] value 11
```

pmdabcc: order histogram instances ascending

---

qa/1118
src/pmdas/bcc/modules/runqlat.python

as `bcc.kernel.all.runnable` is inconsistent with the current `kernel.all.runnable` metric from PCP, I renamed it.
@natoscott do you have any better suggestions for the name?
The tool 
> measures the time a task spends waiting on a run queue for a turn on-CPU, and shows this time as a histogram. This time should be small, but a task may need to wait its turn due to CPU load.
(https://github.com/iovisor/bcc/blob/master/tools/runqlat.py)

pmdabcc: rename runqlat metric name

---

src/pmdas/bcc/bcc.conf
src/pmdas/bcc/modules/usdt_jvm_threads.python

ext4dist, xfsdist and zfsdist modules only work if the respective
filesystem kernel module is loaded, therefore disable all fs modules
per default

pmdabcc: disable ext4dist per default, add xfsdist and zfsdist sections

---

src/pmdas/linux/pmda.c

The proc_fs_nfsd.th_cnt and proc_fs_nfsd.pool_cnt were incorrectly
configured with counter semantics.  Both of the metrics should have
instanteneous semantics.

Correct the semantics for proc_fs_nfsd.th_cnt and proc_fs_nfsd.pool_cnt

---

qa/1155
qa/1155.out
qa/group
src/pmdas/bcc/bcc.conf
src/pmdas/bcc/modules/tcplife.python
src/pmdas/bcc/modules/tcplife_old_kb.bpf

Updated tcplife to track each TCP session independently of the process and export all metrics visible in the BCC tcplife tool. The session_count configuration option controls how many TCP sessions should be stored in the cache.
@natoscott all instance values will never change, as they show information from already closed TCP sessions, therefore PM_SEM_DISCRETE is the correct semantic for all metric values I assume?
Screenshot of the corresponding vector widget:
(I'll rename RADDR/RPORT to DADDR/DPORT in the vector widget to keep it consistent with the BPF code and manpage of tcplife)

pmdabcc: tcplife: track sessions independently, add more metrics + QA

---

src/pmdas/bcc/modules/tcplife.python
src/pmdas/bcc/modules/tcplife_old_kb.bpf
src/pmdas/bcc/modules/usdt_jvm_alloc.python

correct fix for the destination port (see https://github.com/iovisor/bcc/pull/1813), buffer_page_count power of 2 check and styling updates
recycle old instances by using the row number as instance key (0 = most recent TCP session)
example:
```
bcc.proc.io.net.tcp.comm PMID: 149.3.1 [command]
Data Type: string  InDom: 149.3 0x25400003
Semantics: instant  Units: none
Help:
command
inst [0 or "0"] value "code"
inst [1 or "1"] value "code"
inst [2 or "2"] value "NetworkManager"
inst [3 or "3"] value "curl"
inst [4 or "4"] value "curl"
bcc.proc.io.net.tcp.pid PMID: 149.3.0 [PID]
Data Type: 32-bit unsigned int  InDom: 149.3 0x25400003
Semantics: instant  Units: none
Help:
PID
inst [0 or "0"] value 8621
inst [1 or "1"] value 8621
inst [2 or "2"] value 1247
inst [3 or "3"] value 3850
inst [4 or …
```

pmdabcc: fix tcplife dport, styling, recycle old instances

---

src/libpcp_web/src/GNUmakefile

Changed GNUmakefile for libpcp_web to fix file name.

Fixed file name for libpcp_web

---

.pylintrc
qa/1116
qa/1116.out
qa/1117
qa/1158
qa/1158.out
qa/common.bcc
qa/group
src/pmdas/bcc/bcc.conf
src/pmdas/bcc/modules/bioperpid.python
src/pmdas/bcc/modules/biotop.python

bioperpid: cumulates block I/O per pid
biotop: fetches block device I/O activity every X seconds and sorts it (useful for displaying in Vector)

pmdabcc: renamed old biotop to bioperpid, add new biotop tool

---

qa/admin/check-vm

qa/admin/check-vm assumes python3-bcc is not installed, even though it is installed.
$ qa/admin/check-vm
Missing: /usr/lib*/python3.*/*-packages/bcc.py [python3-bcc or python3-bpfcc (build optional)]
$ rpm -ql python3-bcc
/usr/lib/python3.6/site-packages/bcc
/usr/lib/python3.6/site-packages/bcc-0.6.0-py3.6.egg-info
/usr/lib/python3.6/site-packages/bcc/__init__.py
/usr/lib/python3.6/site-packages/bcc/__pycache__
/usr/lib/python3.6/site-packages/bcc/__pycache__/__init__.cpython-36.opt-1.pyc
/usr/lib/python3.6/site-packages/bcc/__pycache__/__init__.cpython-36.pyc
Updated the previous file name to existing one, and deleted python3-bpfcc
because there seems to be no such RPM package.

qa: check-vm: update file name of python3 bcc RPM package

---

src/pmdas/bcc/modules/biolatency.python
src/pmdas/bcc/modules/bioperpid.python
src/pmdas/bcc/modules/biotop.python
src/pmdas/bcc/modules/execsnoop.python
src/pmdas/bcc/modules/fs/ext4dist.python
src/pmdas/bcc/modules/fs/xfsdist.python
src/pmdas/bcc/modules/fs/zfsdist.python
src/pmdas/bcc/modules/runqlat.python
src/pmdas/bcc/modules/sysfork.python
src/pmdas/bcc/modules/tcplife.python
src/pmdas/bcc/modules/tcpperpid.python
src/pmdas/bcc/modules/tcpretrans.python
src/pmdas/bcc/modules/tcptop.python

imho we should also include attribution to the original author in the header of each BCC PMDA module (where appropriate), as quite a few lines of python code are copied and adapted from the original BCC tool

pmdabcc: add attribution to the author of each BCC tool

---

src/pmdas/bcc/bcc.conf
src/pmdas/bcc/modules/biolatency.python
src/pmdas/bcc/modules/biotop.python
src/pmdas/bcc/modules/execsnoop.python
src/pmdas/bcc/modules/tcplife.python
src/pmdas/bcc/modules/tcpperpid.python
src/pmdas/bcc/modules/tcpretrans.python
src/pmdas/bcc/modules/tcptop.python
src/pmdas/bcc/modules/tracepoint_hits.python
src/pmdas/bcc/modules/uprobe_hits.python
src/pmdas/bcc/modules/usdt_hits.python
src/pmdas/bcc/modules/usdt_jvm_alloc.python
src/pmdas/bcc/modules/usdt_jvm_threads.python

Users shouldn't have to look into the source code of each module to get a description of the configuration options - therefore I moved them to `bcc.conf` (and grouped the modules + added a short description to each module as suggested by @myllynen)

pmdabcc: move module options description to bcc.conf, add short description of each module

---

src/libpcp_web/src/discover.c

It's a simple typo I guess. This change helps to build libpcp_web.

libpcp_web: fix MAXNAMLEN -> MAXNAMELEN

---

src/pcp/dstat/pcp-dstat.py

pcp-dstat: use PMAPI context to get hostname

---

.pylintrc
qa/1171
qa/1171.out
qa/group
qa/src/.gitignore
qa/src/GNUlocaldefs
qa/src/bcc_profile.c
src/pmdas/bcc/bcc.conf
src/pmdas/bcc/modules/pcpbcc.python
src/pmdas/bcc/modules/profile.bpf
src/pmdas/bcc/modules/profile.python
src/pmdas/bcc/pmdabcc.python
src/python/pmda.c

The profile module records stack traces at a specific interval. It should be used in combination with Vector, which will display them as flame graphs:
This PR also includes a commit which releases the GIL while the PMDA is waiting for new PDUs, otherwise the GIL would lock out background threads.

pmdabcc: profile module and store callback, python: release GIL

---

man/html/cpuperf/GNUmakefile
man/html/diskmodel/GNUmakefile
man/html/diskperf/GNUmakefile
man/html/pmie/GNUmakefile
man/html/pmview/GNUmakefile

tar's default pax/posix format stores ctime and atime that vary across builds.
ustar format works everywhere and creates more reproducible output.
gzip --no-name causes it to not store a 4-byte UNIX timestamp in .gz header (actually it stores 0)

create reproducible tarballs

---

man/man3/mmv_stats_init.3
man/man3/mmv_stats_registry.3

In this new manpage, it is explained the new functions to add metrics, instances, indoms, and labels. There is also a small note in mmv_stats_init  saying is deprecated and also it is fixed a small typo when showing the struct mmv_metrics_t instead of mmv_metrics2_t .

Add documentation: manpage mmv_stats_registry

---

src/pmdas/trivial/GNUmakefile
src/pmdas/trivial/Install
src/pmdas/trivial/README
src/pmdas/trivial/pmdatrivial.perl

The trivial-pmda is currently the most simple pmda implementation, provided in C. Adding a perl variant which provides the same functionality.

 Implement the trivial-pmda also as perl daemon 

---

src/selinux/pcpupstream.te.in

allow pcp_pmcd_t domain to read all dirs,files and fifo_file in attribute file_type
allow pcp_pmcd_t domain to read shared memory and semaphores of all domain on system
allow pcp_pmcd_t domain stream connect to all domains
allow pcp_pmcd_t domain to connect to all ports.

[SELinux] Add generic policy rules to allow pcp_pmcd process to read system objects

---

qa/1389
qa/1389.out
qa/group
src/pmwebd/pmgraphite.cxx

Prior to this patch, it was observed that in a live (being written-to)
multi-volume archive, pmwebd would stop looking for the last volume#
too early.  The timestamp on that wrong "last" volume is used in a
subsequent freshness heuristic.  Because the actual last volume file
may not be found during the search, pmwebd could be temporarily blind
to newer data available in newer volumes of the same archive,
returning falsely empty results.  This patch improves this volume
enumeration logic to find the last one, via an explicit loop.  This
leaves pmwebd with a max-60-second blind spot for fresh values.
qa/1389 tests with a pmlogger with HUP-triggered volume switching, and
an explicit /bin/touch to simulate longer-running previous volumes.

pmwebd: tolerate live archives with multi-hour-old volumes

---

qa/756.out
qa/perfevent/config/test_raw_events.txt
qa/perfevent/perf_event_test.c
src/pmdas/perfevent/configparser.h
src/pmdas/perfevent/configparser.l
src/pmdas/perfevent/perfevent.conf
src/pmdas/perfevent/perfinterface.c

This adds support for using perf events which might not be exposed via standard mechanisms such as `sysfs` or `libpfm`. The alternative way to access these hardware counters is by using the architecture
dependent raw event codes directly.
Raw events can be specified in the perfevent configuration using the following syntax:
```
RAW:[EVENT_NAME] rawcode=[RAW_EVENT_CODE]
```
E.g.
```
$ tail -n 1 /var/lib/pcp/pmdas/perfevent/perfevent.conf
RAW:foo rawcode=0x1e
$ pminfo | grep foo
perfevent.hwcounters.RAW_foo.dutycycle
perfevent.hwcounters.RAW_foo.value
```

pmda: perfevent: Add support for raw perf events

---

src/pmchart/pmchart.desktop

Merging Frank's XDG desktop categories fix

pmchart.desktop: standards require a ";" at end of Categories field

---

books/PCP_PG/pcp-programmers-guide.xml

"pmgui" is incorrectly written as "ppmgui" in programmers guide.
https://pcp.io/books/PCP_PG/html/ch03s07s02.html
https://pcp.io/books/PCP_PG/pdf/pcp-programmers-guide.pdf

programmers guide: fix typo in sample code

---

src/pmwebd/pmwebapi.cxx

Previous code could crash on http://localhost:PORT/pmapi/1/metrics
sans the ?target=FOO querystrings.

pmwebd issues/580: tolerate empty prometheus metrics query

---

src/pmwebd/main.cxx
src/pmwebd/pmwebd.1

Disable pmwebd -x option.
issue #412

pmwebd: drop /dev/tty diagnostics copying from pmwebd

---

configure
configure.ac
src/pmns/GNUmakefile

.NeedRebuild creation is handled by rpm scripts.
This change also fixes the target_distro configure check for modern
[open]SUSE distros, which only include /etc/os-release.
Signed-off-by: David Disseldorp <ddiss@suse.de>

pmns: don't package .NeedRebuild for SUSE distros

---

qa/255
qa/common.check
src/pmie/.gitignore
src/pmie/GNUmakefile
src/pmie/pmie_check.service.in
src/pmie/pmie_check.timer
src/pmie/pmie_daily.service.in
src/pmie/pmie_daily.timer
src/pmie/pmie_timers.sysconfig
src/pmlogger/.gitignore
src/pmlogger/GNUmakefile
src/pmlogger/pmlogger_daily.service.in
src/pmlogger/pmlogger_daily.timer
src/pmlogger/pmlogger_daily_check.service.in
src/pmlogger/pmlogger_daily_check.timer
src/pmlogger/pmlogger_daily_poll.service.in
src/pmlogger/pmlogger_daily_poll.timer
src/pmlogger/pmlogger_daily_report.service.in
src/pmlogger/pmlogger_daily_report.timer
src/pmlogger/pmlogger_daily_report_poll.service.in
src/pmlogger/pmlogger_daily_report_poll.timer
src/pmlogger/pmlogger_timers.sysconfig

This patchset converts (non-docker) pmie and pmlogger crontab entries to systemd timer + service files, which are installed when ENABLE_SYSTEMD is configured.

offer systemd timers as an alternative to crontab

---

src/include/builddefs.in

Fix an invalid shell variable reference in builddefs.in which
accidentally works when the DIST_ROOT variable is not empty, but causes
installation of Python modules to fail when DIST_ROOT is empty.  The
Homebrew packaging system for MacOS uses an empty DIST_ROOT to build and
install directly into a user-writable directory under /usr/local/Cellar.

Fix Python install flags for DIST_ROOT=

---

configure
configure.ac

The configure script cannot be given a value for the QT installation
directory except by setting the environment variable QTDIR.  There is a
--with-qt option but you cannot pass it a directory, the only valid
values are "yes" "no" and "check".
Regrettably Homebrew makes it super hard to set an environment variable
during build, and really wants you to do everything with commandline
options to configure.
This change extends the syntax of the --with-qt option by allowing its
value to be the absolute path of the QT installation directory.  This is
consistent with many open source users of autoconf.

Allow --with-qt=DIR to specify QT installation dir

---

src/pcp/dstat/pcp-dstat.py

the two characters get implicitly concatenated if the comma is missing, but `printtype` is always a single character

pcp-dstat: fix typo in printtype detection

---

src/pmdas/bcc/GNUmakefile

I really should get the azure pipelines integrated soon, that would have catched this bug

pmdabcc: fix install (due to README rename)

---

qa/1173

test fails with kernel `4.15 `, but works with `4.18+`

qa: increase min kernel version for ucalls qa test 1173

---

qa/1187.out
src/pcp/dstat/pcp-dstat.py

The number of commas in title and sub-title headers were more than expected.
Resolves github issue #639.

pcp-dstat: fix misaligned headers in CSV output

---

src/pcp/dstat/pcp-dstat.py

The first sample for counter metrics returns value None. When all
metrics we are displaying are counter metrics, a comma-only line
appears in csv output. This commit prevents such comma-only lines
from being displayed to csv output.

pcp-dstat: prevent comma-only lines from being added to csv output

---

qa/1369
qa/1369.out
scripts/pcp-push

qa/1369: tweak filter
scripts/pcp-push: another attempt at a revised github workflow
qa/1369          |    4 +
qa/1369.out      |   20 +++---
scripts/pcp-push |  168 +++++++++++++++++++++++++++++++++++--------------------
3 files changed, 122 insertions(+), 70 deletions(-)
Details ...
commit b692f293aa54aae0b8f7b585d32959411c374bb1
Date:   Wed Jul 17 14:36:38 2019 +1000
scripts/pcp-push: another attempt at a revised github workflow
More changes aimed at making commits and merges flow via github
pull requests.
commit ff5678b8453bb72baa22c56a0daf2b864cb53e47
Date:   Wed Jul 17 14:34:33 2019 +1000
qa/1369: tweak filter
context label length depends on the length of the hostname and/or
the length of …

qa/1369 and scripts/pcp-push Changes committed to git@github.com:kmcdonell/pcp.git 20190717

---

src/pmproxy/src/webapi.c

Fix consequential double-free corruption in pmwebapi_done() due to the
baton reverse pointer in client->u.http.data pointing back to a free'd
batton. Also dont bother zeroing any baton fields since the entire baton
will be memset to zero just prior to being free'd in pmwebapi_free_baton().
Also only sdsfree the baton->clientid if it is not NULL (this is benign
since sdsfree() handles a NULL pointer anyway).

pmproxy: fix double-free memory corruption

---

src/pcp/atop/ifprop.c
src/pcp2elasticsearch/pcp2elasticsearch.py
src/pcp2graphite/pcp2graphite.py
src/pcp2influxdb/pcp2influxdb.py
src/pcp2spark/pcp2spark.py
src/pmdas/linux_proc/proc_pid.c
src/pmdas/linux_proc/proc_pid.h
src/pmdas/mmv/src/mmv.c

RHBZ #1721107
The pidlist refresh function was leaking instance name buffers for
processes that had exited between refreshes. Fix this by storing the
instance name (truncated psargs) in a new field of the hash table
entry, and harvest them correctly if they've exited after each refresh.
The indom table instance names now share a pointer to the new field
in the hash table entry so they dont need to be separately free'd.
This similifies the code and memory management.
Also put a 4K cap on the maximum length of a psargs string for the
unlikely scenario of a psargs string that is not NULL terminated,
i.e. use strndup() rather than strdup(). This may be possible if
a rogue process modified it's argv[0] at run-time.
For testing, the recipe in RHBZ#1721107 was repro'd using valgind
and a …

pmdaproc: fix memory leak in pidlist refresh

---

qa/1266
qa/1266.out
qa/group
src/pcp/atop/various.c

This resolves Red Hat BZ #1733866.

pcp-atop: fix write mode (-w) handling of proc vs hotproc metrics

---

qa/README
src/bashrc/pcp_completion.sh
src/zshrc/_pcp

qa/README: add notes for ssh access to pcpqa login with selinux
qa/README |   30 +++++++++++++++++++++---------
1 file changed, 21 insertions(+), 9 deletions(-)
Details ...
commit a995f2f27c2f318eca4328a400baf8c6c9895021
Date:   Wed Jul 31 06:20:08 2019 +1000
qa/README: add notes for ssh access to pcpqa login with selinux
Thanks to Mark for diagnosing this issue that surfaced recently
when vm03 moved to Fedora 30.

shell completion changes for pmlogextract -x and qa notes Changes committed to git@github.com:kmcdonell/pcp.git 20190730

---

src/pmlogger/pmlogger.service.in
src/pmlogger/pmlogger_check.service.in
src/pmlogger/pmlogger_daily.service.in
src/pmlogger/pmlogger_daily_report.service.in

The pmlogger_check service is not required by pmlogger.service. This was causing them to run in parallel. Also, add a 120s timeout in all service scripts for both start and stop to avoid timeouts in Azure CI checks.

tweak systemd service scripts

---

qa/412
qa/798.out.32
qa/new-seqs

Ken McDonell (3):
qa/412: refactor arithmetic
qa/798: 32-bit version of .out apparently not updated
qa/new-seqs: small cosmetic change to output order
qa/412        |   93 ++-
qa/798.out.32 | 1442 ++++++++++++++++++++++++++++++++++++++++++++++++++++++----
qa/new-seqs   |    5 
3 files changed, 1413 insertions(+), 127 deletions(-)
Details ...
commit c99bd7025e0839305b2fabc4a37c7e301dd16b6f
Date:   Mon Sep 2 17:28:30 2019 +1000
qa/new-seqs: small cosmetic change to output order
commit 5456d5b6af69b7520b54b5ffe3ff77da20db80e7
Date:   Mon Sep 2 17:24:25 2019 +1000
qa/798: 32-bit version of .out apparently not updated
64-bit version was updated in commit c81f8ee0.
Hope this is OK ...
commit …

small qa changes Changes committed to git@github.com:kmcdonell/pcp.git 20190902

---

src/pmdas/statsd/README.md
src/pmdas/statsd/src/aggregator-metric-gauge.c
src/pmdas/statsd/src/parser-basic.c
src/pmdas/statsd/src/parser-ragel.rl
src/pmdas/statsd/src/pmda-callbacks.c
src/pmdas/statsd/src/pmdastatsd.c

+ ...and small fix for underflow detection
Payloads with values such as these are valid:
:+1:
```
test:1e1|g
test:+1e+1|g
test:-1e-1|g
test:1.1e1|g
```
These are not:
:-1:
```
test:-.2e2|g
test:.2e2|g
test:e2|g
test:2e2.2|g
```

Added support for scientific notation for metric values in StatsD payloads

---

qa/1100.out
qa/1671
qa/1671.out
qa/915
qa/953
qa/967
qa/967.out
qa/group
src/pmdas/trace/GNUmakefile
src/pmdas/trace/Makefile.proto

qa/1671: separate stderr and stdio from pmrep
src/pmdas/trace: makefile fixes for netbsd
qa/953: map errno 61 (Connection refused) -> NETERROR (for *BSD systems)
qa/915: really only makes sense to run this if systemctl is present
qa/1100: split into 1100 (bash) and 967 (new, zsh)
qa/1100                        |   86 -------------------
qa/1100.out                    |    3 
qa/1671                        |    3 
qa/1671.out                    |   12 +-
qa/915                         |    8 +
qa/953                         |    3 
qa/967                         |  182 +++++++++++++++++++++++++++++++++++++++++
qa/967.out                     |    5 +
qa/group                       |    3 
src/pmdas/trace/GNUmakefile    |   26 +++++
src/pmdas/trace/Makefile.proto |   12 +- …

qa + trace PMDA for *BSD Changes committed to git@github.com:kmcdonell/pcp.git 20190903

---

qa/1152
qa/1152.out
src/libpcp/src/instance.c
src/libpcp_pmda/src/cache.c

A while back Marko reported pminfo segfaults involving bcc metrics
when used to instrument Java12. This turned out to be NULL instance
names being stored in the pmdaCache file (which is actually a bug
in pmdabcc).
In defense of that scenario, fortify libpcp_pmda and libpcp
against NULL instance names being read in from the indom cache;
rather than segfault, return an appropriate error.
Also update qa/1152 to test and verify the fix. The pmdabcc bug
will be fixed separately now that it's easier to debug.

libpcp,libpcp_pmda: fortify pmdaCache against NULL instance names

---

qa/1146
qa/660
qa/870
src/external/dict.c
src/libpcp/src/events.c
src/libpcp_gui/src/timestate.c
src/libpcp_mmv/src/mmv_stats.c
src/libpcp_qmc/src/qmc_metric.cpp
src/pcp/atop/atopsar.c
src/pcp/atop/showgeneric.c
src/pmdas/weblog/check_match.c

Ken McDonell (11):
qa/1146: add $seq arg for ./870 --check call
qa/870: relax checks for pmlogger control files
qa/660: tweak filter
misc: pander to gcc warning insanity
external/dict.c: fix coverity CID 287860 Division or modulo by float zero
src/pcp/atop/atopsar.c: fix coverity CID 288176 Division or modulo by float zero
src/pmdas/weblog/check_match.c: fix coverity CID 341701 Division or modulo by float zero
src/libpcp_gui/src/timestate.c: fix coverity CID 288030 Pointer to local outside scope
src/libpcp_qmc/src/qmc_metric.cpp: coverity fix CID 288108 Resource leak
Revert "qa/660: tweak filter"
src/libpcp/src/events.c: fix a couple of Coverity reported issues
qa/1146                           |    2 +-
qa/660                            |    6 +++---
qa/870                            | …

qa and small coverity-driven fixes Changes committed to git@github.com:kmcdonell/pcp.git 20190910

---

qa/1098
qa/1098.out
qa/group
qa/pmdas/test_python/pmdatest_python.python
src/python/pcp/pmda.py

- removed early return in set_list_instances: we need to set it_numinst
to 0, and should also set the it_set to an empty array - otherwise the
old instance list will persist
- updated qa/1098: updated test pmda - the first and last round should
return an indom with empty instances
- added 1098 to the sanity QA group, as it's base functionality for
Python PMDAs

python: fix uncached instances with empty list

---

qa/GNUmakefile
qa/group
scripts/new-branch

scripts/new-branch: add optional branch "suffix" argument
qa/group: put back the deleted pmwebd tests, but mark as retired
qa/GNUmakefile: don't package retired: tests
qa/GNUmakefile: don't package retired: tests (do it properly this time)
Nathan Scott (1):
selinux: build fix for platforms without map for class file
qa/GNUmakefile                |    4 ++--
qa/group                      |    8 ++++++++
scripts/new-branch            |   12 ++++++++++--
src/selinux/pcpupstream.te.in |    2 +-
4 files changed, 21 insertions(+), 5 deletions(-)
Details ...
commit c88247a65c3d96a2b0cd2af26ddc50d7a81495b3
Date:   Thu Oct 3 06:16:42 2019 +1000
qa/GNUmakefile: don't package retired: tests (do it properly this time)
commit …

qa and misc Changes committed to git@github.com:kmcdonell/pcp.git 20191002a

---

debian/control.master
qa/.gitignore

Ken McDonell (3):
qa/.gitignore: remove 662.out (now checked in)
debian/control.master: add Breaks pcp-webapi for libpcp3-dev
debian/control.master: changes for libpcp3-dev
debian/control.master |    6 +++---
qa/.gitignore         |    1 -
2 files changed, 3 insertions(+), 4 deletions(-)
Details ...
commit ea9890a331d82c71d96b24ee26638102cd76cd0a
Date:   Thu Oct 3 13:23:32 2019 +1000
debian/control.master: changes for libpcp3-dev
Need to tweak the transition with the demise of pcp-webapi.
commit eb836213a322faf0f6faf77f9ec9fa30aa4840aa
Date:   Thu Oct 3 10:27:15 2019 +1000
debian/control.master: add Breaks pcp-webapi for libpcp3-dev
commit f6d29f7f6a0209c325225ecd8efb2b3ebe84023d
Author: Ken McDonell …

debian packaging Changes committed to git@github.com:kmcdonell/pcp.git 20191003a

---

build/rpm/fedora.spec
build/rpm/pcp.spec.in
configure
configure.ac
debian/rules
src/include/builddefs.in
src/python/GNUmakefile

Revert "build: when calling 'python' prefer a 2/3-versioned binary if available"
build/rpm/fedora.spec    |    2 +-
build/rpm/pcp.spec.in    |    2 +-
configure                |   44 ++++++++++++++++++++++----------------------
configure.ac             |   22 +++++++++++-----------
debian/rules             |    4 ++--
src/include/builddefs.in |   22 +++++++++++-----------
src/python/GNUmakefile   |   14 +++++++-------
7 files changed, 55 insertions(+), 55 deletions(-)
Details ...
commit d095412fe71ccc5917448f18b194de729fd1ee4a
Date:   Sat Oct 5 06:41:01 2019 +1000
Revert "build: when calling 'python' prefer a 2/3-versioned binary if available"
This reverts commit 6635e2ee08e37e3e90cf9e6651e2cad3ec0b7582.
This commit was addressing a …

revert python2 build change Changes committed to git@github.com:kmcdonell/pcp.git 20191005

---

qa/1149
qa/1149.out
qa/878
qa/group
src/pmlogrewrite/pmlogrewrite.c
src/pmlogrewrite/result.c

pmlogrewrite: plug major memory leak
qa/878: separate stdout and stderr in the .full file
qa/1149                         |   64 ++++++++++++++++++++++++++++++++++++++++
qa/1149.out                     |    3 +
qa/878                          |    4 ++
qa/group                        |    1 
src/pmlogrewrite/pmlogrewrite.c |    5 +++
src/pmlogrewrite/result.c       |    7 +++-
6 files changed, 83 insertions(+), 1 deletion(-)
Details ...
commit 84121693f6024bf3c73a19784d67bd70bbd043a1
Date:   Thu Oct 10 06:39:10 2019 +1100
qa/878: separate stdout and stderr in the .full file
Debugging aid.
commit 10309b15f3520f3e6857a8a7c0dad333348b460d
Date:   Thu Oct 10 06:33:13 2019 +1100
pmlogrewrite: plug …

IMPORTANT pmlogrewrite mem leak fix Changes committed to git@github.com:kmcdonell/pcp.git 20191010

---

qa/src/pmproxy_load_test.python
src/libpcp_web/src/webgroup.c

pmWebGroupFetch() calls webgroup_fetch_names() which calls
webgroup_fetch() which calls on_pmwebapi_done()
However, at the end of pmWebGroupFetch(), on_pmwebapi_done() is called
also.
This results in (trying to) send the actual fetch response *and* a
generic {context:XXX, success:true} response, and for HTTP/1.0 clients to
close the connection twice, which results in a libuv assert.
This commit removes the call to on_pmwebapi_done in the webgroup_fetch()
function, and instead returns the error message and status code via
a parameter and return value (like the other webgroup_* functions).

pmproxy: send only one fetch response

---

src/pmproxy/src/server.c

This prevents the case where an earlier-than-expected socket close destroys
the data structures that are still in use handling a fetch query.
Fixes #772

Ensure that client data structures are freed only after not in use

---

build/ci/containers/Dockerfile.fedora-rawhide
build/ci/containers/Dockerfile.fedora30
build/ci/containers/Dockerfile.fedora31
src/external/uv_callback.c
src/external/uv_callback.h
src/pmproxy/src/.gitignore
src/pmproxy/src/GNUmakefile
src/pmproxy/src/server.c
src/pmproxy/src/server.h

All uv_write calls should occur via main thread according to libuv API documentation.
Include external uv_callback external dependency (MIT license).
https://github.com/litesync/uv_callback
Use uv_callback library to schedule uv_write calls onto the main thread instead of from the worker thread.
http://docs.libuv.org/en/v1.x/guide/threads.html
Fixes #774

Ensure uv_write happens from main thread

---

src/pmdas/statsd/src/GNUmakefile
src/pmdas/statsd/src/parser-ragel.rl

Should address issues regarding building pmdastatsd on Fedora Rawhide caused by new Ragel version.

Fedora rawhide fix pmdastatsd

---

qa/1155
qa/1157
qa/1170
qa/1178

qa/1155,1157,1170,1178: notrun on Linux 5.2 kernels
qa/1155 |    6 ++++++
qa/1157 |    6 ++++++
qa/1170 |    6 ++++++
qa/1178 |    6 ++++++
4 files changed, 24 insertions(+)
Details ...
commit 1f21bedebbb44bf61abcd8a1ea3b92e144fa85db
Date:   Thu Nov 7 06:50:43 2019 +1100
qa/1155,1157,1170,1178: notrun on Linux 5.2 kernels
The Linux 5.2 kernel headers, BPF and some of the PCP BCC modules are
not good friends, so don't run these tests on just this kernel version.
Thanks Marko.

qa - BCC PMDA Changes committed to git@github.com:kmcdonell/pcp.git 20191107

---

qa/756
qa/756.out
qa/886

qa/756: add filter to handle filesystem directory order non-determinism
qa/886: repeat slowly after me ... do NOT use == with test(1)
qa/756     |   37 ++++++++++++++++++++++++++++++---
qa/756.out |   68 ++++++++++++++++++++++++++++++-------------------------------
qa/886     |    4 +--
3 files changed, 70 insertions(+), 39 deletions(-)
Details ...
commit 9bb95b6ffe645b290b79e951d7295c572c3d4b70
Date:   Thu Nov 21 10:51:42 2019 +1100
qa/886: repeat slowly after me ... do NOT use == with test(1)
commit 9caf4ac481f345c03abadd2bc36456d5610ae685
Date:   Thu Nov 21 10:43:57 2019 +1100
qa/756: add filter to handle filesystem directory order non-determinism
Was failing on more than half my QA …

misc qa Changes committed to git@github.com:kmcdonell/pcp.git 20191121

---

configure
configure.ac

pcp.lsm embeds the build date which makes the package un reproducible,
use SOURCE_DATE_EPOCH to always generate a deterministic builddate when
reproducing pcp.
Motiviation: https://reproducible-builds.org/
Signed-off-by: Jelle van der Waa <jelle@archlinux.org>

configure: make build reproducible

---

src/libpcp_pmda/src/callback.c
src/pmdas/bpftrace/bpftrace/cluster.py
src/pmdas/bpftrace/bpftrace/pmda.py

* implement (empty) label callback (hides `[Mon Dec  9 11:43:43] pmdabpftrace(3898) Debug: pmdaLabel: InDom 151.104010[16]: Missing metric value(s)`)
* don't log PM_ERR_VALUE errors (log only if libpmda debug flag is set), hides `[Mon Dec  9 11:43:54] pmdabpftrace(4533) Error: pmdaFetch: Fetch callback error from metric PMID 151.102.12[-1]: Missing metric value(s)`
* these "errors" are normal, occurs when Grafana is querying data but the bpftrace script didn't collect any data yet

pmdabpftrace: don't show errors in logs which are due to normal operation

---

build/rpm/pcp.spec.in

build/rpm/pcp.spec.in: hostname change
build/rpm/pcp.spec.in |    4 ++--
1 file changed, 2 insertions(+), 2 deletions(-)
Details ...
commit c0c0c6e0968ce760093fc00c92ada3223f582984
Date:   Sun Dec 29 07:01:37 2019 +1100
build/rpm/pcp.spec.in: hostname change
Requires: and BuildRequires: clauses need /bin/hostname not hostname
(need the executable and the associated package is not hostname).
Tracks changes in fedora.spec.
Without this change the build is broken on RHEL6 and CentOS 6.

fix rhel6 build breakage Changes committed to git@github.com:kmcdonell/pcp.git 20191229

---

src/external/sds.h
src/pmdas/cifs/pmda.c

As described in https://bugzilla.opensuse.org/show_bug.cgi?id=1160244
---
Starting from the upcoming GCC release 10, the default of -fcommon option will change to -fno-common:
In C, global variables with multiple tentative definitions will result in linker errors. Global variable accesses are also more efficient on various targets.
Porting advice:
A common mistake in C is omitting <code>extern</code> when declaring a global variable in a header file.  If the header is included by several files it 
results in multiple definitions of the same variable.  In previous GCC versions this error is ignored.  GCC 10 defaults to <code>-fno-common</code>, 
which means a linker error will now be reported. To fix this, use <code>extern</code> in header files when declaring global variables, and ensure …

Fix compilation with -fno-common (new GCC 10 default)

---

src/pcp/pidstat/pcp-pidstat.py

pcp pidstat fails with IndexError when proc.psinfo.utime metric is found prior to
kernel.uname.* or hinv.ncpu metrics.
Check whether those metrics exist before starting to show process information.
Resolves: https://github.com/performancecopilot/pcp/issues/625
The error in my environment is as follows.
```
File "/usr/libexec/pcp/bin/pcp-pidstat", line 916, in <module>
sts = manager.run()
File "/usr/lib64/python3.6/site-packages/pcp/pmcc.py", line 665, in run
self._printer.report(self)
File "/usr/libexec/pcp/bin/pcp-pidstat", line 838, in report
self.print_machine_info(group, manager)
File "/usr/libexec/pcp/bin/pcp-pidstat", line 820, in print_machine_info
header_string += group['kernel.uname.sysname'].netValues[0][2] + '  '
IndexError: list index out of …
```

pcp-pidstat: fix out of range error when reading metrics from an archive

---

src/pmdas/freebsd/freebsd.c

Changes committed to git@github.com:kmcdonell/pcp.git 20200125
src/pmdas/freebsd/freebsd.c: rework last 32->64 bit change
src/pmdas/freebsd/freebsd.c |    2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
Details ...
commit ef11d7d50b1d576e2250d6cc8f4bde66e730000e
Date:   Sat Jan 25 20:23:53 2020 +1100
src/pmdas/freebsd/freebsd.c: rework last 32->64 bit change
Botched the second argument to do_sysctl(), so it worked on newer
platforms where the metrics are 64-bit in the kernel, but was failing
on the older platforms where the metrics are 32-bit in the kernel.
Fixed now.

freebsd PMDA (take 2)

---

src/pcp/atop/atop.c
src/pcp/atop/pcp-atop.1

It seems from the documents that these arguments are not available for pcp-atop -r although they works.

docs: add interval and samples arguments to usage of pcp-atop -r

---

qa/1599
qa/statsd/src/utils/pmdastatsd_test_utils.py

Prefixed python scripts with `$sudo` and removed some artifacts from the time when the pmdastatsd configs were not hardcoded in tests.

Fix for EPERM when running pmdastatsd qa 1599

---

qa/1359.out
qa/1457
src/pmdas/linux/mk.rewrite

Changes committed to git@github.com:kmcdonell/pcp.git 20200219
Ken McDonell (3):
qa/1359.out: remade after -Dalloc addition to debug flags
qa/1457: don't run on Ubuntu 19.10
src/pmdas/linux/mk.rewrite: fix a bunch of KERNEL_ULONG errors
Details ...
commit 567d089eea08cb15b9764c8f7935bdedf732ac54
Date:   Wed Feb 19 11:40:01 2020 +1100
src/pmdas/linux/mk.rewrite: fix a bunch of KERNEL_ULONG errors
This file had diverged from the PMDA, so the type rewriting rules
for KERNEL_ULONG (U32 or U64) were wrong in a number of places.
commit 45d3edbe8a32fe8ada44a6bda67a5b26caa98d4a
Date:   Wed Feb 19 07:14:30 2020 +1100
qa/1457: don't run on Ubuntu 19.10
There is some fatal issue here with libuv, libssl, libcrypto and …

linux pmda + logrewrite, qa

---

src/pmlogger/pmlogger_daily_report.sh

Fix for BZ1805146 - pmlogger_daily_report causing PCP upstream testsuite to fail
This fix makes sure a newly created $REPORTDIR has the expected permissions.

Fix for BZ1805146 (pmlogger_daily_report)

---

src/pcp/atop/atopsar.c

pcp-atop displays pid with "%5d".
However, since the pid is 2^22(approximately 4 million) at the maximum,
it is necessary to handle up to 7-digits.
Resolves https://github.com/performancecopilot/pcp/issues/850

pcp-atop: fix upper limit of output pid to 7-digits

---

src/pmcd/rc_pcp
src/pmcd/rc_pmcd
src/pmie/rc_pmie
src/pmlogger/rc_pmlogger
src/pmmgr/rc_pmmgr
src/pmproxy/rc_pmproxy

Changes committed to git@github.com:kmcdonell/pcp.git 20200220
qa: add _notrun checks for pmda.bcc tests that need __version__
Revert "qa: add _notrun checks for pmda.bcc tests that need __version__"
qa: redo the __version__ test for pmda.bcc tests
rc scripts: small changes to make things work better for FreeBSD
*/rc_*: rework the arg logging
Details ...
commit c1aafead6f3cad97b873f699fc0df41437013255
Date:   Wed Feb 26 17:08:47 2020 +1100
*/rc_*: rework the arg logging
1. comment it out by default (to avoid AVC warnings/errors)
2. add for all rc scripts
3. logs got to $PCP_LOG_DIR/rc_foo.log for the foo service
4. log all args, not just $1
commit 748019dd3d7f0b1f98ca6eb72f3c750ee1f97c01
Date: …

rc scripts rework (freebsd) and qa changes

---

src/pcp/atop/atop.c
src/pcp/atop/atop.h
src/pcp/atop/photosyst.c
src/pcp/atop/photosyst.h
src/pcp/atop/showprocs.c
src/pcp/atop/systmetrics.map
src/pmdas/linux/help
src/pmdas/linux/pmda.c
src/pmdas/linux/root_linux
src/pmlogconf/platform/linux

STDATE/STTIME of pcp atop -v was wrong (e.g. STDATE=1970/01/01).
A new metric kernel.all.btime is added and used to fix the issue.
Note:
- This may not be best but I defined a new global function set_system_btime to pass btime to showprocs.c.
- ENDATE/ENTIME are also modified but not be tested because curstat->gen.elaps seems not to be implemented yet.

pcp-atop: fix STDATE/STTIME in -v output

---

build/rpm/fedora.spec

The `pcp-pmda-redis` package is not depending on `perl-Data-Dumper` as it should.
Data-Dumper is being using by pmdaredis.pl https://github.com/performancecopilot/pcp/blob/0ab16a9017a1a0b56fbb969bec659be258234dc5/src/pmdas/redis/pmdaredis.pl#L72
This PR adds it to the specfile as requested [here](https://bugzilla.redhat.com/show_bug.cgi?id=1788519#c3).

Add perl-Data-Dumper dependency for pcp-pmda-redis

---

build/rpm/do-maybe-requires

If we have a
Maybe-Requires: perl(Net::SNMP)
line in pcp.spec.in, the do-maybe-requires script calls
rpm -q "perl(Net::SNMP)"
which exits with status 1, because no package with this name is
installed (however, perl-Net-SNMP is installed!).
Therefore rpm needs to check the Provides: metadata of installed
packages as well, which is accomplished with the --whatprovides argument.

build: update do-maybe-requires script to check provides metadata

---

src/libpcp_qwt/src/qwt_compass_rose.cpp
src/libpcp_qwt/src/qwt_dial_needle.cpp
src/libpcp_qwt/src/qwt_null_paintdevice.cpp
src/libpcp_qwt/src/qwt_painter.cpp
src/libpcp_qwt/src/qwt_painter_command.h
src/libpcp_qwt/src/qwt_plot_panner.cpp
src/libpcp_qwt/src/qwt_plot_renderer.cpp
src/libpcp_qwt/src/qwt_widget_overlay.cpp

The definition of QPainterPath is not pulled in anymore from Qt headers that included it indirectly in previous releases so it has to be included explicitly.

Add missing includes in Qt 5.15 beta2

---

build/tar/postinstall.tail
qa/1190
qa/294
qa/915
qa/check.callback.sample
src/pmcd/rc_pcp
src/pmcd/rc_pmcd
src/pmie/rc_pmie
src/pmlogger/rc_pmlogger
src/pmmgr/rc_pmmgr
src/pmproxy/rc_pmproxy
src/pmproxy/src/pmproxy.c

Changes committed to git@github.com:kmcdonell/pcp.git 20200409
src/pmproxy/src/pmproxy.c: fix strncpy() compilation warning
qa/915: stop pmproxy if it was not running when the test started
qa/915                    |    3 +++
src/pmproxy/src/pmproxy.c |    2 +-
2 files changed, 4 insertions(+), 1 deletion(-)
Details ...
commit 39aa1ad1cffd6abb9a9cc4ad4fa1d0ecb1a2c702
Date:   Thu Apr 9 07:35:06 2020 +1000
qa/915: stop pmproxy if it was not running when the test started
commit aa01bb9e992532715c3e015bb174030cd618df45
Date:   Thu Apr 9 07:25:31 2020 +1000
src/pmproxy/src/pmproxy.c: fix strncpy() compilation warning
gcc 9.2.1 seems more pedantic.

qa (small), pmproxy compilation warning fix

---

build/tar/postinstall.tail
qa/1190
qa/294
qa/915
qa/check.callback.sample
src/pmcd/rc_pcp
src/pmcd/rc_pmcd
src/pmie/rc_pmie
src/pmlogger/rc_pmlogger
src/pmmgr/rc_pmmgr
src/pmproxy/rc_pmproxy
src/pmproxy/src/pmproxy.c

Changes committed to git@github.com:kmcdonell/pcp.git 20200407
Ken McDonell (8):
build/tar/postinstall.tail: fix (misleading) error in comment
qa/1190: important --check fix
qa/294: wait for pmproxy to start
qa/check.callback.sample: tweak PMNS check
rc scripts: add "env" to the #debug# lines
src/pmproxy/src/pmproxy.c: make logfile name unique with -Dappl1
qa/1190: fix botch in last commit
qa/915: taking more control of the environment
build/tar/postinstall.tail |    4 +++-
qa/1190                    |   28 ++++++++++++++++++++--------
qa/294                     |    4 ++++
qa/915                     |   29 ++++++++++++++++++++++++++---
qa/check.callback.sample   |    7 +++++--
src/pmcd/rc_pcp            |    1 +
src/pmcd/rc_pmcd           |    1 +
src/pmie/rc_pmie           |    1 + …

qa, rc scripts (cosmetic), pmproxy

---

qa/1388
qa/1388.out
qa/pmdas/test_python/pmdatest_python.python
src/include/pcp/pmapi.h
src/libpcp/src/context.c
src/libpcp/src/exports.master
src/libpcp_web/src/util.c
src/pmproxy/src/webapi.c

somehow I messed up the last PR (#879) and set the base branch of that PR to the master branch of my fork, instead of the `auth-changes` feature branch of my fork... here is it again:
Looks like after creating a new context (`pmwebapi_new_context`) the first PDU pmproxy sends to the PMCD with authentication credentials comes from the `pmGetContextHostName_r` function (`pmLookupName_ctx` inside this function), which gets called from `pmwebapi_new_context` -> `pmwebapi_source_meta`.
Unfortunately this function doesn't return the `sts`, so pmproxy doesn't know about any authentication errors. This PR introduces `pmGetContextHostName_rr` which returns the `sts`, and fixes QA 1388.
Another issue remains however, valgrind reports the following when the authentication is unsuccessful:
``` …
```

pmproxy: return authentication errors

---

qa/1672
qa/1672.out
qa/group
src/libpcp/src/secureconnect.c
src/pmcd/sasl2.conf

fixes auth for login & digest-md5 methods, and removes gssapi from the default auth methods

libpcp: fix authentication for multi-step auth methods

---

src/pmdas/activemq/RESTClient.pm

In the new version of AcrtiveMQ (5.12+), when sending REST request through Jolokia API, it requires an 'Origin' value in HTTP request header(https://activemq.apache.org/rest) otherwise it will fail.
$ curl -u admin:admin http://localhost:8161/api/jolokia/read/org.apache.activemq:brokerName=localhost,destinationName=NOTIFICATIONS,destinationType=Queue,type=Broker
{"error_type":"java.lang.Exception","error":"java.lang.Exception : Origin null is not allowed to call this agent","status":403}

Fix for new version of ActiveMQ broker

---

man/html/guide.html

Fixes: [performancecopilot/pcp#916](https://github.com/performancecopilot/pcp/issues/916)

Fix for broken link to installation guide

---

man/html/lab.secureclient.html
src/libpcp/src/secureconnect.c

I ran the tests from the secure group, they all pass.
The code doesn't change the pmproxy part (with the comment regarding read/write), which is in `secureserver.c`.

libpcp: open NSSDB readonly for clients

---

qa/1198
qa/check.callback.sample
qa/src/pmcdgone.c
src/pmdas/linux/.gitignore
src/pmdas/linux/GNUmakefile
src/pmdas/linux/kernel_fixups.conf
src/pmdas/linux/mk.rewrite
src/pmdas/linux/proc_fs_nfsd_fixups.conf
src/pmdas/linux/proc_net_sockstat_deprecate.conf
src/pmlogconf/pmlogconf.c
src/python/pmapi.c

Changes committed to git@github.com:kmcdonell/pcp.git 20200523
linux pmda: rework the pmlogrewrite conf file handling
src/pmlogconf/pmlogconf.c: fix a couple of compilation warnings
qa/check.callback.sample: fix misleading typo in name of pmlogger_daily
qa/src/pmcdgone.c: remove one last system() compilation warning
src/python/pmapi.c: remove (scary) compilation warning
qa/1198                                          |    2 
qa/check.callback.sample                         |    4 -
qa/src/pmcdgone.c                                |    5 +
src/pmdas/linux/.gitignore                       |    5 -
src/pmdas/linux/GNUmakefile                      |   13 +--
src/pmdas/linux/kernel_fixups.conf               |   45 ++++++++++++
src/pmdas/linux/mk.rewrite …

refactor pmlogrewrite rules for linux pmda, qa, compilation warnings

---

Makepkgs
configure
configure.ac
debian/GNUmakefile
qa/admin/myconfigure
src/pmie/rc_pmie
src/pmlogger/rc_pmlogger

Changes committed to git@github.com:kmcdonell/pcp.git 20200607
Makepkgs: default configure --without-python for Ubuntu 20.04 (and later)
configure.ac: Force man pages for Debian-style builds
debian/GNUmakefile: fix cut-n-paste botch for ganglia2pcp packaging
pmie/rc_pmie & pmlogger/rc_pmlogger: fix trap snarfoo
Makepkgs                 |   17 ++++++++
configure                |   99 ++++++++++++-----------------------------------
configure.ac             |   18 ++++++++
debian/GNUmakefile       |   15 +++++--
qa/admin/myconfigure     |   17 ++++++++
src/pmie/rc_pmie         |    2 
src/pmlogger/rc_pmlogger |    2 
7 files changed, 91 insertions(+), 79 deletions(-)
Details ...
commit 18d428197f23fac1cbdc546a0bfca3e4f9730585
Date: …

build & configure

---

src/pmlogconf/pmlogconf.c

Variable `i` is compared with `vsp->numval` in iterrations of `evaluate_number_values`, `evaluate_string_values` and `evaluate_string_regexp` functions. As `vsp->numval` can have a negative value (an error code), the comparison if `i`is less then `vsp->numval` needs to use signed integers instead of unsigned ones.

Fix of 1845241 - Intermittent pmlogconf core dumps

---

src/libpcp/src/derive_parser.y.in

This is a follow up of f8b0886ba5027d29aeec5223da7866c62084cb2b commit.
The commit above delivered initialization of hash structure for a node. Unfortunately
hsize field was not set during the initialization. The unset hsize is causing intermittent
crashes of pminfo when the hash table is walked through.
This fix delivers initialization of the hsize field.

fix of incomplete initialization of __pmHashCtl struct of F_REGEX node

---

src/pmdas/statsd/src/parser-basic.c

Incorrectly checking/setting variable used as bit map could cause memory leak.

pmdastatsd: fixed an issue that could cause memory leak when parsing invalid datagrams using 'basic' parser

---

qa/1204
qa/1205
qa/1206
qa/1208
qa/1209
qa/1210
qa/1213
qa/1215
qa/1216
qa/1223
qa/1223.out
qa/admin/pcp-daily
qa/group
src/pmlogctl/pmlogctl.sh

Changes committed to git@github.com:kmcdonell/pcp.git 20200701
qa/1223: (new) pmlogctl tests with multile pmloggers per control file
qa/group: add 1204 to sanity, add 1223 (new)
qa/admin/pcp-daily: remove a couple of references to pmmgr
qa: pmlogctl tests - extend filter to remove any non-qa pmloggers
src/pmlogctl/pmlogctl.sh: more small changes
qa/1204                  |   13 +++
qa/1205                  |   13 +++
qa/1206                  |   13 +++
qa/1208                  |   13 +++
qa/1209                  |   13 +++
qa/1210                  |   13 +++
qa/1213                  |   13 +++
qa/1215                  |   13 +++
qa/1216                  |   13 +++
qa/1223                  |  160 +++++++++++++++++++++++++++++++++++++++++++++++
qa/1223.out              | …

small pmlogctl changes

---

man/man1/pmlogger_check.1
qa/119
qa/1232
qa/1232.out
qa/151
qa/151.out
qa/338
qa/338.out
qa/530
qa/530.out
qa/532
qa/532.out
qa/679.out
qa/793.out
qa/925.out
qa/group
src/pmlogger/pmlogger_daily.sh

Changes committed to git@github.com:kmcdonell/pcp.git 20200706
qa/119: re-order setup
pmlogger_daily: -k 0 fixes
qa/1232: (new) check pmlogger_daily -k 0
qa: assorted changes/remakes to match changed pmlogger_daily -k semantics
man/man1/pmlogger_check.1      |  168 ++++++++++++++++++++--------
qa/119                         |   30 ++---
qa/1232                        |  107 +++++++++++++++++
qa/1232.out                    |   36 ++++++
qa/151                         |    6 -
qa/151.out                     |    2 
qa/338                         |    6 -
qa/338.out                     |    6 -
qa/530                         |    6 -
qa/530.out                     |    6 -
qa/532                         |    4 
qa/532.out                     |    2 
qa/679.out …

pmlogger_daily -k 0 fixes

---

qa/031.out.linux
src/libpcp/src/hash.c
src/pmdas/linux_proc/GNUmakefile
src/pmdas/linux_proc/acct.c
src/pmdas/linux_proc/acct.h
src/pmdas/linux_proc/clusters.h
src/pmdas/linux_proc/help
src/pmdas/linux_proc/indom.h
src/pmdas/linux_proc/pmda.c
src/pmdas/linux_proc/root_proc

Collect accounting information from process accounting file (see acct(5)).
pmdaproc(acct) will try to read data from /var/account/pacct if it is effective,
or use private accounting file (/tmp/pcp-pacct).
Currently version 3 format (struct acct_v3) is available.
Related to https://github.com/performancecopilot/pcp/issues/922

pmdaproc: add acct metrics

---

src/pcp/atop/showprocs.c

Remove superfuous breaks, as there is a 'return' before them.
Signed-off-by: Liao Pingfang <liao.pingfang@zte.com.cn>

pcp-atop: Remove superfluous breaks

---

src/libpcp/src/derive_fetch.c

Remove superfuous breaks, as there is a 'return' before them.
Signed-off-by: Liao Pingfang <liao.pingfang@zte.com.cn>

src/libpcp/src/derive_fetch.c: Remove superfluous breaks

---

src/pmdas/linux_proc/pmda.c

Remove the superfuous break, as there is a 'return' before it.
Signed-off-by: Liao Pingfang <liao.pingfang@zte.com.cn>

pmdaproc: Remove the superfluous break

---

qa/check

Changes committed to git@github.com:kmcdonell/pcp.git 20200714
Mark Goodwin (3):
qa/group: mark 1886 reserved until new code merged
selinux: allow pmdaxfs quotaget permissions
qa/917: update 917.out.in for new pmcd quotaget rule
sec/pmcd/pmdaproc.sh: silence derived metrics warnings from Remove
qa/check: make exit status 1 if the run is aborted
Andreas Gerstmayr (1):
ci: add debug info for flaky centos8 build
build/ci/platforms/centos8.yml |    3 +++
qa/917.out.in                  |    1 +
qa/check                       |    1 +
qa/group                       |    2 +-
src/pmcd/pmdaproc.sh           |    2 +-
src/selinux/pcpupstream.te.in  |    6 +++++-
6 files changed, 12 insertions(+), 3 deletions(-)
Details ...
commit d5a53b5b4519b43d192c2c8e28d35ba61b9b7a71
Author: …

check exit status

---

configure
configure.ac
src/include/pcp.conf.in
src/pmdas/linux_proc/acct.c

Related to: 
- https://github.com/performancecopilot/pcp/pull/962
- https://github.com/performancecopilot/pcp/issues/969

pmdaproc: acct: initialize acct file path with PCP_* variable and implement cleanup

---

qa/730.out
qa/731.out
src/pmdas/linux_proc/cgroups.c
src/pmdas/linux_proc/cgroups.h
src/pmdas/linux_proc/help
src/pmdas/linux_proc/pmda.c
src/pmdas/linux_proc/root_proc

I wasn't sure about the numbering - in the `cgroups.h` there are cgroup v2 metrics with a lower number than some cgroup v1 metrics - how did you know 5 years back that 8 months back you will add some other cgroup v2 metrics there? :open_mouth: [1]
I gave it the number 90 now and a new block, but can change that if there's a system which I should follow.
[1] https://github.com/performancecopilot/pcp/commit/e3c7ea17b68854f7c098003bb4537e13aa65dad7#diff-23194b027d3722a739170dfbb2f9d940R117

pmdaproc: add cgroup.memory.current metric (cgroup v2)

---

qa/1768
qa/1768.out
src/pmlogctl/pmlogctl.sh

Changes committed to git@github.com:kmcdonell/pcp.git 20200730
qa/1768: new filter and remade after pmfind_check changes
src/pmlogctl/pmlogctl.sh: fix sed botch
qa/1768                  |    7 +--
qa/1768.out              |   96 +++++++++++++++++++++++++++++++++++++++++++----
src/pmlogctl/pmlogctl.sh |    6 +-
3 files changed, 95 insertions(+), 14 deletions(-)
Details ...
commit 90e8fcea1512e236afb9a16b4ee4f6379375811f
Date:   Thu Jul 30 16:49:29 2020 +1000
src/pmlogctl/pmlogctl.sh: fix sed botch
hostspecs like pcp://slick:44321 were tripping up the %h expansion
because of the embedded / ... changed the sed pattern delimiter from
/ to ; (; seems unlikely in a hostspec, but if it can occur I'll
need some additional embedded escaping …

pmlogctl & qa/1768

---

qa/003
qa/069
qa/069.out.ipv6
qa/069.out.nonipv6
qa/115
qa/115.out
qa/common.check
src/pmie/pmie_check.service.in
src/pmie/pmie_check.sh
src/pmie/pmie_check.timer

Changes committed to git@github.com:kmcdonell/pcp.git 20200730
Miroslav Foltýn (14):
libpcp_web: fixed redis search text endpoint handler, now correctly returns response
pmproxy: correctly handling /search/text type params, updated response model for /search/suggest; libpcp_web: bunch of heuristics around querying Redisearch in /search related endpoints
libpcp_web: search, updated minimum token length for querying RediSearch
pmwebapi: extended pmSearchTextType, pmSearchTextRequest, /search corrected Redisearch query handling; pmproxy: reverted /search/suggest response model, updated /search/text response model, made all search result item fields optional, updated /search/text defaults
libpcp_web: search: handling of some edge cases
pmproxy: new /search/indom endpoint, simple response …

qa, pmie&systemd, pmie_check

---

man/man3/pmwebapi.3
qa/1872
qa/1872.out
qa/group
src/include/pcp/pmwebapi.h
src/libpcp_web/src/search.c
src/pmproxy/src/search.c

pmproxy: 
- /search/* - removed client param from all endpoints
- /search/text - query params are now in singular form
- /search/info - removed ?key param as it did nothing anyway, all RediSearch stuff is in single index
- /search/text - removed indom opts for ?field and ?highlight params as RediSearch indom field is no longer fulltext searchable
- /search/text - made search query look for tokens in index in order (helps with some heuristics for fetching helptexts)
man:
- updated search related docs
qa:
- /search endpoints request->response test 1872

pmproxy: /search/* endpoints tweaks; man: pmwebapi.3; qa: simple pmproxy /search/* test

---

man/Check
man/man1/pmdacisco.1
qa/1251
qa/1251.out
qa/group
src/include/builddefs.in

Changes committed to git@github.com:kmcdonell/pcp.git 20200803
qa/1251: (new) basic checkout for man(1) plumbing for PCP man pages
qa/1251: tweaks after *BSD adventure
src/include/builddefs.in: tweak INSTALL_MAN
man/man1/pmdacisco.1: remove the probe.1 and parse.1 aliases
man/Check                |   21 ++---
man/man1/pmdacisco.1     |    4 
qa/1251                  |  192 ++++++++++++++++++++++++++++++++++++++---------
qa/1251.out              |   74 +++++++++++++++++-
qa/group                 |    1 
src/include/builddefs.in |    1 
6 files changed, 240 insertions(+), 53 deletions(-)
Details ...
commit e406df38def9b3994c7b4e7bb7e07364c76b4d02
Date:   Tue Aug 4 08:06:02 2020 +1000
man/man1/pmdacisco.1: remove the probe.1 and …

man pages and man page build

---

src/libpcp_web/src/search.c

Handles edge case, when multiple word queries seemed to be handled / parsed differently by RediSearch based on order of query parts.
Before:
```
127.0.0.1:6379> ft.explain pcp:text '(kernel)=>{$inorder:true} @TYPE:{indom|metric}'
INTERSECT {
UNION {
kernel
+kernel(expanded)
}
TAG:@TYPE {
indom
metric
}
}
127.0.0.1:6379> ft.explain pcp:text '(kernel cpu)=>{$inorder:true} @TYPE:{indom|metric}'
INTERSECT {
UNION {
kernel
+kernel(expanded)
}
UNION {
cpu
+cpu(expanded)
}
TAG:@TYPE {
indom
metric
}
} => { $inorder: true; }
```
After:
```
127.0.0.1:6379>  ft.explain pcp:text '@TYPE:{indom|metric} (kernel)=>{$inorder:true}'
INTERSECT {
TAG:@TYPE {
indom
metric
}
UNION {
kernel
+kernel(expanded)
}
}
127.0.0.1:6379>  ft.explain pcp:text '@TYPE:{indom|metric} (kernel cpu)=>{$inorder:true}'
INTERSECT …
```

libpcp_web: search edge case fix

---

man/man3/pmregisterderived.3
qa/1886
src/libpcp_web/src/query.c
src/libpcp_web/src/query.h

**Check compatibility between series**
For those metric name with multiple SIDs, check the units' compatibility between them and if three dimensions are identical but scales are different, use the larger scale and convert the values with the smaller scale. Data type is promoted to type PM_TYPE_DOUBLE. Otherwise, report an error and do not store descriptors of them.
**Update query expressions' descriptor**
- Store the computed semantics, type, and units into Redis
- Keep indom unchanged
- Set pmid to 511.0.0
- Leave source unchanged (should we change this field?)
**TODO**
- ~~expression of two "discrete" metrics give an "instant" result --> should be discrete~~
- ~~Fix: division seems to be giving an negative unsigned result:~~
> $ pmseries 'hinv.ncpu{hostname == "goblin"}[samples:1] / …

HMSET timeseries query expressions descriptor

---

qa/061.out
src/libpcp/src/optfetch.c
src/pmlogger/src/checks.c
src/pmlogger/src/fetch.c
src/pmlogger/src/gram.y

Changes committed to git@github.com:kmcdonell/pcp.git 20200904
src/libpcp/src/optfetch.c: improve diagnositics
src/pmlogger/src/fetch.c: improve -Dfetch diagnostics
src/pmlogger/src/gram.y: fix for repeated metric problem
src/pmlogger/src/checks.c: fix for repeated metric problem
qa/061.out: remade after opFetch diagnostic change in libpcp
qa/061.out                |   40 +++++++++++++++
src/libpcp/src/optfetch.c |   22 +++++---
src/pmlogger/src/checks.c |  122 ++++++++++++++++++++++++++++++++++++----------
src/pmlogger/src/fetch.c  |   97 ++++++++++++++++++++++++++++++++++++
src/pmlogger/src/gram.y   |    7 ++
5 files changed, 255 insertions(+), 33 deletions(-)
Details ...
commit 7deb4e7a980384286a04a178fda1d32388d537f8
Date:   Fri …

pmlogger fix for repeated metric

---

src/pmcd/pmcd.service.in
src/pmproxy/pmproxy.service.in

Resolves [bug 1876452](https://bugzilla.redhat.com/show_bug.cgi?id=1876452).

Fix of typos when referencing man pages in systemd unit files

---

src/pcp/dstat/pcp-dstat.1
src/pcp/dstat/plugins/gpfs

Gives GPFS throughput and file operation stats.
Output looks like this:         
```
> # pcp dstat  --gpfs
> -fs/total
> read writ
> 156M 155M
> 227M 228M
> 232M 232M
> 153M 153M
> 72M  72M
> 70M  70M
> 75M  75M^C
```
>  
```
> # pcp dstat  --gpfs-ops
> -----------------------gpfs-ops/total----------------------
>   opens     reads     writes  inode_upd  readdir    closes
>        0         0         0         0         0         0
>        0         0         0         0         0         0
>        0         0         0         0         0         0
>        0         0         0         0         0         0
>       17        49         0         0         0        16
>       99       297         0         0         0        99
>       91       274         0         0         0 …
```

Add dstat plugin for GPFS. Requires the GPFS PMDA.

---

.github/workflows/ci.yml
Makepkgs
configure
configure.ac
debian/fixcontrol.master
qa/admin/check-vm
qa/admin/myconfigure
qa/admin/other-packages/manifest

Debian bullseye removed the python-dev package. python2-dev also exists
on Debian buster, therefore use this instead of python-dev.

build: rename python-dev to python2-dev

---

qa/1061

The run of 1061 test sometimes takes longer than 1s.
This commit allows run of the test to take 0-9.999s

The run of 1061 test sometimes takes longer than 1s

---

src/pmdas/mssql/pmdamssql.python

Improved exception handling when a connection of mssql PMDA to MSSQL server fails.
The pyodbc module seems to use InterfaceError exception when username/password authentication is used.
When trusted connection is used, then pyodbc seems to use just Error exception.

Improved exception handling of mssql PMDA connection

---

src/pcp/atop/.gitignore
src/pcp/atop/GNUmakefile
src/pcp/atop/acctmetrics.map
src/pcp/atop/atop.c
src/pcp/atop/atop.h
src/pcp/atop/modules.c

Resolves: https://github.com/performancecopilot/pcp/issues/922
Note that process accounting is available if psacct service is running or acct.control.enable_acct is set to non-zero.

pcp-atop: add support for process accounting

---

qa/1160.out
src/pmdas/netcheck/modules/pcpnetcheck.python
src/pmdas/netcheck/modules/ping.python
src/pmdas/netcheck/modules/ping_latency.python
src/pmdas/netcheck/modules/ping_loss.python
src/pmdas/netcheck/netcheck.conf

Changes committed to git@github.com:kmcdonell/pcp.git 20201020
src/pmdas/netcheck: rework to accommodate some QA failures
qa/1160.out                                    |   14 +++++-----
src/pmdas/netcheck/modules/pcpnetcheck.python  |   35 +++++++++++++++----------
src/pmdas/netcheck/modules/ping.python         |   35 ++++++++++++++++++-------
src/pmdas/netcheck/modules/ping_latency.python |   33 +++++++++++++++++------
src/pmdas/netcheck/modules/ping_loss.python    |   33 +++++++++++++++++------
src/pmdas/netcheck/netcheck.conf               |   22 ++++++++++++---
6 files changed, 121 insertions(+), 51 deletions(-)
Details ...
commit 4986a0c3ea45240b3202de4674a61451c879c347
Date:   Tue Oct 20 07:11:49 2020 +1100 …

netcheck PMDA fixes

---

docs/specs/openapi.yaml

This PR adds the remaining and last part of the REST API documentation, i.e, PMAPI HOST SERVICES.
PMAPI HOST SERVICES covers the following:
- `GET /pmapi/context`
- `GET /pmapi/metric`
- `GET /pmapi/fetch`
- `GET /pmapi/children`
- `GET /pmapi/indom`
- `GET /pmapi/profile`
- `GET /pmapi/store`
- `GET /pmapi/derive`
- `GET /pmapi/metrics `

[docs] REST API documentation - PMAPI HOST SERVICES

---

src/pmdas/linux/proc_partitions.c

They are declared with KERNEL_ULONG, so they should be using
_pm_assign_ulong.

pmdas/linux: Use _pm_assign_ulong for disk.dev.read_bytes etc

---

src/pmns/Make.stdpmid

As of 029add427a42344ea7129452c9e0fb286d3cf881, both the if and else
branches here match. Restoration of the previous build-time logic is
tracked via https://github.com/performancecopilot/pcp/issues/1140 and
will affect more scripts than just this one.
Signed-off-by: David Disseldorp <ddiss@suse.de>

pmns/Make: drop duplicate if/else

---

docs/UAG/InstallingAndConfiguringPcp.rst
docs/_static/theme_overrides.css
docs/conf.py

Currently, the text in table cells are not wrapped, due to which the tables are very wide with horizontal scroll bars. This PR resolves this issue by wrapping the text and spreading it over multiple lines.

[docs] Text in table cells wrapped

---

.editorconfig
qa/1286
qa/1286.out
qa/group
src/pcp/atop/.gitignore
src/pcp/atop/GNUmakefile
src/pcp/atop/atop.h
src/pcp/atop/modules.c
src/pcp/atop/netproc.c
src/pcp/atop/netprocmetrics.map
src/pcp/atop/photoproc.c
src/pcp/atop/showgeneric.c
src/pmdas/bcc/bcc.conf
src/pmdas/bcc/modules/netproc.bpf
src/pmdas/bcc/modules/netproc.python

first version of the BCC netproc module, which provides data for the pcp atop per-process bandwidth statistics
I'm open to changes of the name (`netproc` was the best I could come up with) and metric names
```
bcc.proc.io.net.perpid.tcp.in.packets
bcc.proc.io.net.perpid.tcp.in.bytes
bcc.proc.io.net.perpid.tcp.out.packets
bcc.proc.io.net.perpid.tcp.out.bytes
bcc.proc.io.net.perpid.udp.in.packets
bcc.proc.io.net.perpid.udp.in.bytes
bcc.proc.io.net.perpid.udp.out.packets
bcc.proc.io.net.perpid.udp.out.bytes
```
(`bcc.proc.io.net.tcp.*` is already in use by the `tcplife` BCC module)

pmdabcc: netproc module + atop per-process network statistics

---

src/pcp/atop/modules.c
src/pmdas/linux_proc/acct.c

Previously pcp-atop force pmdaproc to disable process accounting state
when it exits regardless of what the original state was.
pcp-atop will control the state regarding acct.control.enable_acct as
a reference count to make sure to restore the original state after
all pcp-atop instances exit.

pcp-atop: restore an original state of process accounting when pcp-atop exits

---

qa/1700
qa/common.bpftrace
scripts/pcp-refresh
src/libpcp/src/logutil.c

Actually in logutil.c when an archive context is closed and the new "trim" indom data structures are freed.

libpcp fix for recent interp.c changes

---

src/pmie/pmie.service.in
src/pmlogger/pmlogger.service.in

Rationale: pmlogger and pmie should not always start pmcd as a dependency,
because a local pmcd is not required if pmlogger or pmie is connecting to a
remote pmcd.
Resolves #1200

systemd: remove Wants=pmcd from pmlogger and pmie

---

build/rpm/pcp.spec.in

same changes and reason as in 9dc78f07ddbcff75697662ea03671a5a094e34d5

build: add versioned rpm spec dependencies for pcp-zeroconf to pcp.spec.in

---

GNUmakefile

Like Debian, SUSE based distributions have lint checks to block packages
carrying [/var]/run/ install paths.
Signed-off-by: David Disseldorp <ddiss@suse.de>

build: avoid packaging rundir on [open]SUSE distros

---

src/pcp/htop/pcp/Platform.c

If ZramMeter does not exist in the machine for any reason, pcp-htop will
panic. This condition prevents this case.

pcp-htop: fix ZramMeter, Handle missing condition

---

src/pmdas/openmetrics/pmdaopenmetrics.1

https://prometheus.io/docs/concepts/metric_types/ seems to make most sense.
https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md looks like a more upstream definition, but it refers to types which openmetrics seems to not support currently.

fix no longer working link

---

src/pmlogconf/tools/sar
src/pmlogconf/zeroconf/pidstat

There are two intervals (10 sec, 30 sec) to collect kernel.all.cpu.*
metrics if zeroconf is enabled.
In this case, the metrics can be collected twice in a very short period
of time. Due to the short sampling interval, large error values may be
output in rate calculation.
To resolve the issue, remove the metrics from 30-second sampling setting.
At the same time, we'll add kernel.all.cpu.vuser to tools/sar to make
sure we don't lose the metric.
modified: src/pmlogconf/zeroconf/pidstat
modified: src/pmlogconf/tools/sar

zeroconf: remove duplicate metrics from 30-second sampling setting.

---

src/pmdas/bcc/modules/netproc.python
src/pmdas/bcc/modules/pcpbcc.python

Mimics proc PMDA's logic to cut the cmdline.
Resolves #1233

pmdabcc: netproc: add command name to instance names

---

qa/1286
qa/1286.out
src/derived/proc.conf
src/pcp/atop/netprocmetrics.map
src/pmdas/bcc/GNUmakefile
src/pmdas/bcc/migrate.conf
src/pmdas/bcc/modules/netproc.python
src/pmlogconf/networking/localdefs
src/pmlogconf/networking/perprocess-linux
src/pmrep/pmrep.conf

afaics I've covered all usages of the netproc PMDA and renamed the metric in all places. Can you please double-check?
I've also added a pmlogconf rule to log the metric if it's available (note: the BCC PMDA is *not* installed by default).

rename netproc metrics and add pmlogconf rule

---

src/libpcp_web/src/discover.c

The initial directories and archive are registered twice:
pmDiscoverMonitor: added event for /var/log/pcp/pmlogger (flags: 0x0011 |new|directory|)
pmDiscoverMonitor: added event for /var/log/pcp/pmlogger/agerstmayr-thinkpad (flags: 0x0011 |new|directory|)
pmDiscoverMonitor: added event for /var/log/pcp/pmlogger/agerstmayr-thinkpad/20210421.14.42.meta (flags: 0x00a1 |new|datavol|metavol|)
fs_change_callBack: event on /var/log/pcp/pmlogger/agerstmayr-thinkpad - changed
pmDiscoverMonitor: added event for /var/log/pcp/pmlogger/agerstmayr-thinkpad/20210421.14.42.meta (flags: 0x00a1 |new|datavol|metavol|)
pmDiscoverMonitor: added event for /var/log/pcp/pmlogger (flags: 0x0011 |new|directory|)
pmDiscoverMonitor: added event for /var/log/pcp/pmlogger/agerstmayr-thinkpad (flags: 0x0011 …

discovery: do not register callback twice for initial directories

---

src/pmrep/conf/sar_v11.conf

The output format of some metricsets has been changed to
follow the changes in sysstat v12. Leave the old sar-v11 output
format as well for RHEL8 users.

pmrep: add RHEL8 compatible sar metricsets to default pmrep conf directory

---

src/pmproxy/pmproxy.service.in

If pmproxy starts before Redis, it will disable time-series
functionality. This update makes sure that pmproxy starts after Redis
(only if Redis is available, otherwise there is no change in behavior).
Related: #1296

pmproxy: start pmproxy after Redis (if available)

---

qa/1901
qa/1901.out
qa/group
src/pmlogger/src/ports.c

Set FD_CLOEXEC flag on the pmlogger control sockets so they are
closed when pmlogger reexecs. Add new test qa/1901 to verify.

pmlogger: fix FD leak on reexec, plus QA

---

configure
configure.ac
src/include/builddefs.in
src/selinux/GNUlocaldefs
src/selinux/GNUmakefile
src/selinux/pcpupstream.te.in

Allow PMDAs that access log files to do so when latest versions
of the kernel and selinux-policy is installed.
This resolves a new qa/652 (pmdasystemd) failure amongst others.

selinux: use new logging_watch_all_log_dirs_path macro

---

configure
configure.ac

After some recent problems and temporary workarounds, we
resolved to drop python2 on old platforms (RHEL6 vintage)
- this ups the minimum version from 2.6 to 2.7.

Change the minimum python2 version to be 2.7

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec

The pcp-system-tools package does not require python,
some tools are written in C as well so we can deliver
that subset still.

build: fix rpm build on el6 relating to python

---

qa/src/parsehostattrs.c
qa/src/parsehostspec.c
src/include/pcp/libpcp.h
src/libpcp/src/connect.c
src/libpcp/src/context.c
src/libpcp/src/internal.h
src/libpcp/src/spec.c
src/libpcp_web/src/webgroup.c

Resolve the two remaining "pm" vs "__pm" structure names that
were called out in the TODO near the head of libpcp.h.  After
auditing code, pmTimeZone is unused so just drop it.  Renamed
pmHostSpec to __pmHostSpec - used in libraries and QA only.

libpcp: complete remaining libpcp.h internal struct renaming

---

qa/1457
qa/1457.out
qa/group
src/libpcp_web/src/webgroup.c
src/pmproxy/src/secure.c
src/pmproxy/src/server.c
src/pmproxy/src/server.h

```
3f5ba221842e6 libpcp_web: add mutex to struct webgroup protecting the context dict
2bad6aef10339 pmproxy: add mutex for client req lists, fix https/tls support, QA
```
Resolves BZ 1947989 - pmproxy hangs and consume 100% cpu if the redis datasource is configured with TLS
Resolves #1311
Related #1203, qa/297 and qa/1290
Tested with updates to qa/1457

pmproxy / libpcp_web multithreading, http and https/tls fixes, QA

---

src/libpcp_web/src/schema.c

Set slots->setup to zero if the Redis version check fails,
indicating Redis is too old (< V5) on this platform.
If the Redis version check fails, "redis-cli monitor" shows
the version request but no further activity.  qa/1543 passes
as do QA groups pmproxy, libpcp_web, redis and pmseries.

libpcp_web: disable Redis connection if version check fails

---

src/pmdas/hacluster/pmda.c

Update instance refresh code for the label supported metrics to remove the
superfluous pmdaCacheLookupName() calls.
We update the label supported indoms in mirror to the non-label indoms
and in turn don't require re-checking instance updates immediately again
(after doing so for the non-label indoms).
This also fixes the Coverity defects reported by Nathan for unchecked returns
on these calls.

pmdahacluster: Remove un-needed pmdaCacheLookupName() calls

---

debian/fixcontrol

See https://packages.debian.org/sid/libbpfcc for supported architectures
of libbpfcc

build: mark python3-bpfcc dependency as architecture specific

---

qa/1653
src/pmdas/denki/Install
src/pmdas/denki/denki.c

- remove command line option for cpus
- autodetect for up to 4096 cores, current linux kernel limit
- "intel rapl" -> "rapl", as also newer AMD cpus support it

Automatic cpu core detection for pmda-denki

---

configure
configure.ac
src/include/builddefs.in

defaults to no, i.e. should not change anything unless explicitly enabled.

build: conditionally enable gperftools (default is no)

---

qa/1599
qa/1708
qa/1709
qa/1710
qa/1711
qa/1712
qa/1713
qa/1714
qa/1715
qa/1716
qa/1717
qa/1718
qa/1719

See title, was trying to run tests on a clean system, that's how I found out.

qa: remove valgrind requirements from statsd tests that don't actually use it

---

src/libpcp_web/src/load.c
src/libpcp_web/src/query.c
src/libpcp_web/src/query.c.orig
src/libpcp_web/src/slots.c
src/libpcp_web/src/util.c

```
fdd2eda72 libpcp_web: fix compilation error in series_node_prepare_time
ad75163ca libpcp_web: err handling in series_expr_query_desc(), CID366098
938607ee6 libpcp_web: fix err handling in initSeriesQueryBaton(), Coverity CID341677
9bee6e9b6 libpcp_web: fix null check in pmSeriesDiscoverValues, Coverity CID353645
9a0eec3dd libpcp_web: fix null check, Coverity CID353502.
1cb3fe3c7 libpcp_web: check err in query functions. Coverity CID366058,366064,366088
057ffc30d libpcp_web: check ret value from pmParseUnitsStr in series_redis_hash_expression
6c6aebf0f libpcp_web: fix resource leak in redisSlotsInit CID370634
c0f3ad57f libpcp_web: fix resource leak in series_redis_hash_expression CID366094
bb71b0943 libpcp_web: fix resource leak in node_pattern_reply Coverity CID328038
```
Have checked …

libpcp_web coverity fixes

---

man/man3/pmwebapi.3

Added (almost) the same doc text as in the PMAPI section.

docs: document hostspec parameter functionality for openmetrics endpoint

---

src/libpcp_web/src/load.c
src/libpcp_web/src/query.c
src/libpcp_web/src/query_parser.y
src/libpcp_web/src/search.c
src/libpcp_web/src/slots.c
src/libpcp_web/src/util.c

Still have CID 341699 Use-after-free in libpcp_web/src/load.c when connect_pmapi_source_service() fails., which is giving me trouble with qa/1211 hanging. And probably a new resource leak due to changed error handling in an ENOMEM path (this will need to be ignored if it occurs).
```
6b6f36b49 libpcp_web: fix resource leak when default_labelset fails, CID340558
3f2b486fe libpcp_web: improve err handling in pmSeriesDiscoverInDom, CID328046
b824f69f6 libpcp_web: fix read overrun in series_lex, CID287946
8ea559f3d libpcp_web: add null check in series_solve, CID366052
a09855144 libpcp_web: check sdssplitlen in redis_search_text_prep, CID370640
84fd38401 libpcp_web: check async context init in redisSlotsInit, CID370635
b6c2c914b libpcp_web: imrpove ENOMEM err handling, CID366063
21642c00f …
```

libpcp_web coverity round2

---

src/libpcp_web/src/load.c
src/libpcp_web/src/query_parser.y
src/libpcp_web/src/schema.h

Should be all done for libpcp_web now.
```
8c7680feb libpcp_web: split pmapi and redis setup into separate phases, CID341699
eb3d17c7a libpcp_web: fix another read overrun in series_lex, CID287946
```

Libpcp web coverity round3

---

man/man1/pmseries.1

The explanation seems to be incorrect.
I checked the followings:
```
65a90920c72e890bd50333fa73cf23fd757d6377
65a90920c72e890bd50333fa73cf23fd757d6377
65a90920c72e890bd50333fa73cf23fd757d6377
pmseries: [Bad request] invalid regular expression "*"
```

man/man1/pmseries.1: fix ":" operator description

---

debian/libpcp3-dev.install
man/man3/pmwebtimerregister.3
qa/1626
qa/1626.out
qa/1689
qa/1689.out
qa/group
src/include/pcp/pmwebapi.h
src/libpcp_web/src/GNUmakefile
src/libpcp_web/src/exports
src/libpcp_web/src/nowebgroup.c
src/libpcp_web/src/timer.c
src/libpcp_web/src/webgroup.c
src/pmproxy/src/server.c
src/pmproxy/src/server.h
src/pmrep/conf/pmproxy.conf

Add new thread-safe timer registeration API to libpcp_web. Also
add generic CPU and mem server metrics to libpcp_web using an
mmv_registry that is set up and passed in by the calling server.
Switch pmproxy to use this interface, replacing server_metrics_init().
Add new pmrep config for :pmproxy-resource. Remake qa/1689 with new
metrics for pmproxy.mem.datasz/maxrss and pmproxy.cpu.total/sys/user.
Still TODO doc/man updates and a bit more QA.

pmproxy/libpcp_web: add generic timer API, add generic server metrics

---

src/pmdas/bcc/modules/pcpbcc.python

reduces RSS footprint slightly (180 -> 140MB) for ~40MB savings on pmdabcc after load

pmdabcc: free BPF memory after module setup completes

---

src/include/pcp/libpcp.h
src/include/pcp/pmapi.h
src/libpcp/src/exports.in
src/libpcp/src/logutil.c
src/libpcp/src/util.c
src/pmdumplog/pmdumplog.c
src/pmlogcheck/pass1.c
src/pmlogrewrite/pmlogrewrite.c

Adds important macros and data structures we anticipate needing
for version 3 of the PCP archive format.  Code to read, write,
and make use of the new temporal index format is included here.
There should effectively be no change (yet) from this commit as
new code is added under the __PCP_EXPERIMENTAL_ARCHIVE_VERSION3
macro (which is unset) for the most part.

libpcp: initial data structures, macros and TI for v3 archives

---

qa/022.out.linux
qa/1222.out
qa/974.out
src/pmdas/linux_proc/clusters.h
src/pmdas/linux_proc/help_text.h
src/pmdas/linux_proc/pmda.c
src/pmdas/linux_proc/proc_dynamic.c
src/pmdas/linux_proc/proc_pid.c
src/pmdas/linux_proc/proc_pid.h
src/pmdas/linux_proc/root_proc

Two new metrics to help with tracking current the current
process prioritization with the Linux CFS implementation,
using /proc/PID/autogroup.
Internally in pmdaproc this new cluster bumped us over the
32bit boundary on the per-process flags field, so I split
that into two separate fields now (actually makes managing
the FLAG macros simpler).

pmdaproc: add proc.autogroup scheduling metrics

---

qa/327.out
qa/src/checkstructs.c
qa/src/chkputlogresult.c
src/include/pcp/libpcp.h
src/include/pcp/pmapi.h
src/libpcp/src/context.c
src/libpcp/src/e_index.c
src/libpcp/src/exports.in
src/libpcp/src/internal.h
src/libpcp/src/logmeta.c
src/libpcp/src/logutil.c
src/libpcp/src/strings.c
src/libpcp_import/src/archive.c
src/pmdumplog/pmdumplog.c
src/pmlogcheck/pass1.c
src/pmlogextract/pmlogextract.c
src/pmlogger/src/callback.c
src/pmlogger/src/logue.c
src/pmlogger/src/pmlogger.c
src/pmloglabel/pmloglabel.c
src/pmlogreduce/logio.c
src/pmlogrewrite/pmlogrewrite.c

For simplicity, sanity and things like pmloglabel(1) that
want to change label hostnames/timezones (without redoing
all following result records), switch to a fixed size v3
label.  This label still has larger start timestamp field
of course, as well as larger hostname, timezone, zoneinfo
fields compared to v2.

__pmLogLabel: move to fixed-sized v3 log file labels

---

configure
configure.ac
src/include/builddefs.in
src/pmfind/GNUmakefile
src/pmfind/pmfind.service.in
src/pmie/GNUmakefile
src/pmie/pmie_check.service.in
src/pmie/pmie_daily.service.in
src/pmlogger/GNUmakefile
src/pmlogger/pmlogger_check.service.in
src/pmlogger/pmlogger_daily-poll.service.in
src/pmlogger/pmlogger_daily.service.in
src/pmlogger/pmlogger_daily_report-poll.service.in
src/pmlogger/pmlogger_daily_report.service.in

Switches the "daily" and "check" and related services from Type=oneshot
to Type=exec (or Type=simple for older versions of systemd that do
not support Type=exec) and nuke KillMode=none. Explicitly specify
Restart=none, even though it's the default, to be clear that these
timer invoked service scripts are not long running service daemons
and are expected to exit normally.
These changes are a precursor to further improvements to the long
running PCP services and systemd integration.
All tests in the logutil and pmieutil QA groups are passing and soak
testing on several platforms has not shown any new issues (and the
systemd warnings about "Support for KillMode=none is deprecated" are
gone).
Resolves: RHBZ#1942844
Resolves: Fedora BZ#1897945
Resolves: …

services: switch logutil and pmieutil scripts from type oneshot to exec

---

src/pmieconf/percpu/many_util
src/pmieconf/percpu/some_util

Resolves some formatting issues with the many_util pmie rule.
The back-quoting was incorrect, resulting in quotes appearing
in the syslog message strings.  The message accidentally used
the %c (source) pmie formatting string in %cpus as well.  One
other change here is to refactor the many_util rule so that a
singelton metric is the first part of the expression, not the
per-CPU metrics, so that the %h pmie format expansion gives a
single string when the rule evaluates to true.
Finally, bump up the min/max CPU count threshold that we use
to indicate a small/moderate-sized server (from 4 to 12) - we
use this to transition between different rules' effeciveness.

pmieconf: improve the CPU saturation rules

---

qa/1051.out.linux
src/pmieconf/.gitignore
src/pmieconf/GNUmakefile
src/pmieconf/perdisk/average_queue_length
src/pmieconf/perdisk/average_wait_time
src/pmieconf/perdisk/bandwidth
src/pmieconf/perdisk/iops
src/pmieconf/perdisk/localdefs

New rules to detect several scenarios:
- high device utilization and increasing queue length (mgoodwin)
- high device utilization and increasing avg wait time (mgoodwin)
- high system device utilization and high bandwidth (pportante)
- high system device utilization and high iops (pportante)
The latter two require explict enabling in pmieconf as well as
customization per host to set the bandwidth/iops thresholds to
use for each host (and possibly system device name if not sda).

pmieconf: add several per-disk pmie rule templates

---

man/man1/pmdakernel.1
qa/1956
qa/1956.out
qa/group
src/pmdas/linux/linux.h
src/pmdas/linux/pmda.c
src/pmdas/linux/proc_interrupts.c
src/pmdas/linux/proc_meminfo.c

The mem.slabinfo metrics enforce by default the same access
requirements of the kernel when sampling /proc/slabinfo i.e.
only root users have access.  This change provides the same
mechanism pmdaproc(1) has for overriding these changes, i.e.
an opt-in, security-override command line option for folks
who want to open up access.  This is important when logging
these metrics, for example, as pmlogger runs unprivileged -
but the same rule applies to all other PMAPI client tools.
A brief man page note and new test 1956 to exercise the code
are added as well.
Resolves Red Hat BZ #1962902

pmdalinux: add -A option for overriding permissions checks

---

debian/libpcp-mmv1-dev.install
man/man3/mmv_inc_value.3
man/man3/mmv_set_value.3
qa/src/mmv3_labels.c
src/include/pcp/mmv_stats.h
src/libpcp_mmv/src/exports
src/libpcp_mmv/src/mmv_stats.c
src/perl/MMV/MMV.pm
src/perl/MMV/MMV.xs
src/python/pcp/mmv.py

Adds two new convenience routines that allow direct value
setting in MMV client libraries instead of casting values
to double first.
A missing man page is added - mmv_set_value(3) - and both
this and an existing mmv_inc_value(3) page are updated to
document the new API variants.

libpcp_mmv: add new convenience routines for value set/inc

---

qa/1191.out
qa/1221.out
qa/openmetrics/samples/duplicate_hostname_label.txt
src/pmproxy/src/webapi.c

If a PMDA already returns instname and instid labels for a
non-singular metric, don't insert them again in the /metrics
webscrape response because they will be duplicates. Duplicate
labels are not OpenMetrics compliant and break some downstream
consumers of the /metrics end-point, e.g. prometheus.
qa/1191 and 1221 are remade with duplicate_hostname_label.txt,
which tickles this bug. An additional QA test to exercise the
updated webapi /metrics code is still coming.

libpcp_web: avoid duplicate instname labels in /metrics response

---

qa/1543.out
qa/662.out
src/include/pcp/pmwebapi.h
src/libpcp_web/src/webgroup.c
src/pmproxy/src/openmetrics.c
src/pmproxy/src/webapi.c

Reworks the previous change to ensure duplicate labels for
openmetrics scraping are not created, for the special case
of the instname and instid pseudo-labels.
This removes the use of strstr to detect instname inside the
JSON label string as this approach produces false positives
when instname= is embedded within a label value or simply a
similar label name like myinstname.  The approach now makes
use of the pmLabelSet information before merging it to form
the final combined labels string.
Related to #1407

pmproxy: more robust fix for instname/instid duplicates

---

src/pmdas/linux_sockets/metrictab.c

On s390x arch I was observing some unexpected values in the output of the 'sockets' pmda. A deeper analysis shows, there is a copy&paste issue in the source code, replacing the 'busy' value with a value from 'reord_seen' metric, while the 'reord_seen' metric is left unset.
The issue is also present on other arches (x86_64, ppc64le, aarch64) , however for some reason (probably memory alignment or big/little endian, etc.) the values of 'reord_seen' and 'busy' metrics are somehow meaningful, so it did not catch my attention.

Fix of parsing 'reord_seen' and 'busy' values in sockets pmda

---

src/pmdas/bpf/GNUmakefile
src/pmdas/bpf/bpf.c
src/pmdas/bpf/help

Help text is generated dynamically by pmdabpf nowadays so
pass NULL to interfaces setting up static help text files
used by other PMDAs.
Fixes: #1419

pmdabpf: resolve help text warning from pmdaInit

---

qa/1978
qa/1978.out
qa/group
src/pcp/atop/photosyst.c
src/pcp/atop/systmetrics.map
src/pmlogconf/tools/atop-perfevent

The ix86arch PMU, and hence [ix86arch] section of perfevent.conf,
uses a different (singular form) name for INSTRUCTIONS_RETIRED to
everyone else.  Deal with this quirk such that we fallback to the
alternate name if the regular plural form cannot be found.
New test qa/1978 emulates this scenario using pmlogrewrite.
Resolves Red Hat BZ #1986264

pcp-atop: handle different event naming of ix86arch PMUs

---

man/man1/pmlogger_check.1
src/pmlogger/pmlogger.service.in
src/pmlogger/pmlogger_check.sh

Logical opposite of pmlogger_check --skip-primary. Will be used (in subsequent commits) by pmlogger.service to start only the primary logger. Man page for pmlogger_check(1) is also updated.

Add pmlogger_check --only-primary option flag

---

debian/pcp-zeroconf.dirs
debian/pcp-zeroconf.install
debian/pcp-zeroconf.postinst
src/pmlogger/GNUmakefile
src/pmlogger/pmlogger_service_zeroconf.conf

On Debian, a package may not modify configuration files of other packages in
maintainer scripts. This fails the puiparts test[1] will result in eventual
removal[2] of the package and its dependents from Debian.
10.7.3: "[...] The easy way to achieve this behavior is to make the
configuration file a conffile. [...] This implies that the default
version will be part of the package distribution, and must not be
modified by the maintainer scripts during installation (or at any
other time)."
On systemd systems, avoid editing the configuration file installed by the pcp
package from pcp-zeroconf. Ship a systemd service drop-in configuration file
with the pcp-zeroconf which adds an extra environmental variable when running
pmlogger. This can be overridden by a user by creating a file in …

pmlogger: install a zeroconf file for setting interval

---

src/pcp/atop/atop.h
src/pcp/atop/photoproc.c
src/pcp/atop/procmetrics.map
src/pcp/atop/showprocs.c
src/pcp/atop/various.c

This tackles a failure in CI of test qa/1978 due to different
user and group names being reported on test systems.  The root
cause turned out to be use of getpwuid and getgrgid inside the
atop printing routines.  These map IDs to localhost names - we
can do better and use the names from the archive or (possibly
remote) pmcd, which contains the actual map from the collector
host.

pcp-atop: report user and group names using PMAPI calls

---

src/pmcd/pmcd.options
src/pmcd/pmcd.service.in
src/pmproxy/pmproxy.options
src/pmproxy/pmproxy.service.in

Tweak pmcd.options and pmproxy.options to set -A by default. The -A
flag disables service advertising, which is otherwise enabled by
default. With hindsight, -A should have had the opposite semantics,
i.e. -A should have enabled service advertising .. but we can't
change that retrospectfully. Since pmcd.options and pmproxy.options
are config files, the existing settings (if altered from default)
will be retained on upgrade.
Also tweak systemd unit configs to remove Wants=avahi-daemon.service.
This was causing pmcd's systemd deps to trigger Insights warnings,
see BZ1899625 - "Enabling pmcd leads to Insights warning about avahi".
We retain the After=avahi-daemon.service setting in pmcd and add it
to pmproxy service units to ensure avahi starts before the PCP daemons.
This is not a hard …

services: disable service advertising by default in pmcd and pmproxy

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec
debian/pcp-zeroconf.dirs
debian/pcp-zeroconf.install
debian/pcp-zeroconf.postinst
src/pmlogger/GNUmakefile
src/pmlogger/pmlogger_check.sh
src/pmlogger/pmlogger_service_zeroconf.conf
src/pmlogger/pmlogger_zeroconf.defaults

Earlier, a new way provide zeroconf values for pmlogger was implemented in
d19714e27677e3148bb0d1ed113ca719a7459044 and
985920112a56ac4506ccc82b4033f745aedebeaf. This solution worked on systems with
systemd but not others. This caused problem for the piuparts test which
apparently does not start under systemd during the test[1].
To implement the solution in a more consistent way across all systems (with and
without systemd), the earlier solution is reverted with a new solution that
drops an additional defaults file with pcp-zeroconf package.
Tests:
- Install on a machine with non-systemd Debian based distribution. When pmlogger
is started, the PMLOGGER_INTERNAL is part in the pmlogger process environment
with value 10.
- Install on a Debian machine with systemd. When pmlogger is started, …

pmlogger: Implement zeroconf defaults using an additional env file

---

src/pmproxy/src/redis.c

only connect to Redis if one of the following is enabled
* Redis proxying
* pmseries REST API
* pmsearch REST API
* archive discovery

pmproxy: don't connect to Redis if it's not required

---

qa/1355
qa/1355.out
src/libpcp_web/src/slots.c
src/libpcp_web/src/slots.h
src/pmproxy/src/redis.c

* do not log more than one failed Redis connection attempt in a row
* show "trying to reconnect" message only if logging is set to desperate
* track Redis connection sequence numbers
* reduce check interval to 2s
See #1464 for details.

redis reconnect improvements

---

src/libpcp_web/src/slots.c
src/pmproxy/src/redis.c

and show "trying to reconnect" message only if logging is set to desperate

libpcp_web: do not log more than one failed Redis connection attempt in a row

---

qa/368.out
src/pmlogconf/pmlogconf.c

In testing an earlier persistance fix it was discovered
that reprobe was inadvertently overwriting user requests
for changes interactively.
Related to Red Hat BZ #2017632

pmlogconf: fix reprobing with interactive changes

---

src/libpcp_pmda/src/cache.c

We encountered a situation where indom cache loading consumed vast
CPU resources for an indom of size ~150k instances.  Profiling was
used to identify the insert loop that ensures the inst linked list
within the cache hash tables is sorted - this loop is O(N*2) as we
potentially walk this list from the start on every insert during a
cache load.  Because cache loading happens from a sorted file, the
worst-case scenario happened every time - each new instance insert
occurs beyond the current maximum.  Fortunately we maintain a last
entry pointer, so the new fast path uses that first and falls back
to the original behaviour for an out-of-order insertion.
A second opportunity for the same optimization was identified when
auditing the rest of cache.c - in the find_inst() routine for inst …

libpcp_pmda: add indom cache fast-paths for inst lookup beyond max

---

qa/1458
qa/group
src/pmproxy/src/secure.c
src/pmproxy/src/server.c

pmproxy: when secure.enabled is false, do not attempt to init ssl context even for https requests

---

src/pmie/GNUmakefile
src/pmie/pmie_farm.service.in
src/pmie/pmie_farm_check.service.in
src/pmlogger/GNUmakefile
src/pmlogger/pmlogger_farm.service.in
src/pmlogger/pmlogger_farm_check.service.in

The Before= lines in pmie_farm and pmlogger_farm files lacked
a link to the associated timer.  The BindsTo= lines had links
to the unrelated primary pmlogger/pmie_check timers.
Finally, remove a hard-coded path from these .in files, which
was inconsistent with the rest of the systemd files setup.

pmlogger, pmie scripts: fix Before= lines in systemd files

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec
src/pmie/pmie.service.in
src/pmie/pmie_farm.service.in
src/pmlogger/pmlogger.service.in
src/pmlogger/pmlogger_farm.service.in

This change most importantly introduces the Wants= line Mark
(and Jan earlier, indirectly) proposed to make pmlogger_farm
handling function as end-users will expect when manipulating
the pmlogger.service.  Ditto for pmie.
There's also several cleanups of things that are inconsistent
and just plain wrong or missing, particularly in spec files.
This supercedes PR #1492 and PR #1489.
This resolves Red Hat BZ #2027753.

Resolve inconsistencies in new 'farm' and other systemd units

---

src/pmie/pmie_farm_check.timer
src/pmlogger/pmlogger_farm_check.timer

When the farm systemd timers were introduced the check interval
was drastically reduced from half hourly to 5 minutely.  There
wasn't any discussion about rationales for this and its now not
consistent (does not dovetail at all) with the primary pmlogger
and pmie service.  If startup takes a long time (large farms or
slow networks) these will likely overlap constantly, and timing
should be such that we work with the primary services in mind.
Reset to half hourly for these checks, and lets revisit this in
the new year when the other systemd changes are being proposed.
Related to https://github.com/performancecopilot/pcp/pull/1495

Resolve inconsistencies in new 'farm' systemd timers

---

man/man1/pmproxy.1
qa/1458
src/libpcp_web/src/load.c
src/libpcp_web/src/query.c
src/libpcp_web/src/schema.c
src/libpcp_web/src/search.c
src/libpcp_web/src/slots.c
src/pmproxy/pmproxy.conf
src/pmproxy/src/pmproxy.c
src/pmsearch/pmsearch.c
src/pmseries/pmseries.c

Exercised by existing QA test 1458 via CI platforms with no Redis
(test is currently failing there due to this issue).
Related to https://github.com/performancecopilot/pcp/pull/1491

libpcp_web: honour config settings that disable redis completely

---

src/pmlogconf/pmlogconf.c
src/pmlogconf/util.c
src/pmlogconf/util.h

No functional change, all existing regression tests pass.
Related to Red Hat BZ #1973833.

pmlogconf: switch to the bulk pmLookupDescs(3) interface

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec
src/pmie/GNUmakefile
src/pmie/pmie.service.in
src/pmie/pmie_farm.service.in
src/pmie/pmie_farm_check.service.in
src/pmlogger/GNUmakefile
src/pmlogger/pmlogger.service.in
src/pmlogger/pmlogger_farm.service.in
src/pmlogger/pmlogger_farm_check.service.in

Several attempts to allow the pmlogger and new pmlogger_farm
services to exist both dependently and independently haven't
been able to solve the problem of the pmlogger_farm services
and timers starting reliably when we need them to.  This has
caused various backwards-compatibility regressions not least
of which is ansible-pcp and the metrics role.
Simplify things by enforcing a hard link between these now -
when pmlogger is enabled/started so is pmlogger_farm.  Using
the same systemd mechanisms we have used reliably to ensure
pmlogger_check and pmlogger_daily are linked to pmlogger, we
now have reliable farm services once more.  The farm-versus-
primary cgroup separation is still maintained however.
While here, I saw the TODO note re lacking cron-back-compat
support - I've implemented …

pmlogger/pmie farms: give up on soft link to pmlogger/pmie

---

qa/455
src/pmdas/rsyslog/pmdarsyslog.1
src/pmdas/rsyslog/pmdarsyslog.pl

This commit only addresses fetching the existing metrics from the more recent `impstats` output format.
The statistics for `omelasticsearch` have changed drastically, while 2 additional statistics for queues have been added, `discarded.full` and `discarded.nf`.  This commit does NOT attempt to add new PCP metrics for those changes.
The man page for `pmdarsyslog(1)` has been updated to reference the new "modern" rsyslog configuration format, and the `qa/455` test has been expanded to cover the supported metrics.

Fix rsyslog pmda to work with modern output

---

src/pmdas/elasticsearch/pmdaelasticsearch.python

Fixes #1511 in part.
This corrects a bug with the `_cluster/state` API being invoked at the wrong time (broken `if` condition), uses the `_nodes` API instead of the `_cluster/state` API to determine the master node, and also uses the names of the nodes instead of their IDs.
Further, we perform a bit of refactoring based on `pylint` feedback, and apply some helpful formatting and tableization which made it easier to find problems in the metric defintions.
Finally we added a number of additional metrics in four separate commits to make it easier to see the progression of additions.
It would be great to find a way to only call the `_nodes` and `_stats/search` APIs once, instead of twice, though.

Fix elasticsearch pmda

---

src/pmie/GNUmakefile
src/pmie/pmie_farm_check.service.in
src/pmlogger/GNUmakefile
src/pmlogger/pmlogger_farm_check.service.in

Older versions of systemd do not support type=exec but the pmie
and pmlogger farm check services were using it unconditionally.
Update these to use the technique used by the non-farm service
variants.
Related to https://github.com/performancecopilot/pcp/issues/1514

systemd units: pmlogger and pmie farm conditional use of type=exec

---

src/pmproxy/src/series.c

bugfix: pmseries_load_work() will use baton->loading.data, but no one set it to baton explicitly and will segmentfaly.

bugfix: pmseries_load_work() will use baton->loading.data, but no one set it to baton explicitly and will segmentfalt

---

src/pmdas/linux/pmda.c

There was a wrong conversion of tty metrics between 32bits and 64bits
values, causing these metrics to be always zero on s390x platform due
to big-endian architecture. This commit fixes the conversion.
Covered by qa/665.

Fix of tty metrics on s390x platform

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec

Ordering of removal of systemd services, particularly the farms,
was causing systemctl warnings on rpm package removal.  Resolves
that and also uses fewer systemd commands to handle our services
now.
Resolves Red Hat BZ #2048024

packaging: update rpm specs to solve systemd warnings

---

src/pmlogger/pmlogger.defaults
src/pmlogger/pmlogger.zeroconf
src/pmlogger/pmlogger_check.sh

In 2c17ba0cc16f58de511dff1e3122096d60c50bb0, zeroconf provided
defaults (/usr/share/pcp/zeroconf/pmlogger, which was actually
/etc/sysconf/pmlogger_zeroconf at the time of the change) were prioritized over
user configuration (/etc/sysconf/pmlogger). This lead to regression in clients
which edited the user configuration and expected the changes to be given
priority over zeroconf configuration. This was identified at least in
ansible-pcp[1].
Undo the changes in this commit so that the final priority is as follows:
User configuration (/etc/sysconfig/pmlogger)
(priority over)
Zeroconf defaults (/usr/share/pcp/zeroconf/pmlogger)
(priority over)
Code defaults (pmlogger.c)
Links:
1) https://github.com/performancecopilot/pcp/pull/1462#issuecomment-1022714960
Tests:
- Install pcp. Ensure pmlogger …

pmlogger: zeroconf: Prioritize user configuration over zeroconf

---

debian/libpcp3-dev.install
man/man3/pmparseinterval.3
qa/1060
qa/316
qa/316.out
qa/src/.gitignore
qa/src/GNUlocaldefs
qa/src/parsehighresinterval.c
src/include/pcp/pmapi.h
src/libpcp/src/exports.in
src/libpcp/src/rtime.c
src/libpcp/src/tv.c

Add a new pmParseHighResInterval(3) interface into libpcp.
Resolves https://github.com/performancecopilot/pcp/issues/1375

libpcp: support high resolution interval time parsing

---

debian/libpcp3-dev.install
man/man3/pmparsetimewindow.3
man/man3i/__pmconverttime.3
man/man3i/__pmparsetime.3
qa/src/churnctx.c
qa/src/mark-bug.c
qa/src/pmsocks_objstyle.c
qa/src/rtimetest.c
qa/src/timeshift.c
src/include/pcp/libpcp.h
src/include/pcp/pmapi.h
src/libpcp/src/exports.in
src/libpcp/src/getopt.c
src/libpcp/src/logutil.c
src/libpcp/src/rtime.c
src/libpcp_web/src/query.c
src/libpcp_web/src/query_parser.y
src/pmchart/main.cpp
src/pmchart/recorddialog.cpp
src/pmdumptext/pmdumptext.cpp
src/pmie/src/pmie.c
src/pmlogcheck/pmlogcheck.c
src/pmlogger/src/pmlogger.c
src/pmlogsummary/pmlogsummary.c
src/pmval/pmval.c
src/pmview/main.cpp

Fix the sentinel time_t value used in several places to denote
end of time using sizeof(time_t) from configure.ac - no longer
assuming it is fixed at sizeof(int).  A new macro is added for
convenience (PM_MAX_TIME_T).
__pmParseTime and __pmConvertTime gain high resolution variants
which are used internally within the lower resolution versions.
This is a general pattern that seems to work best for all these
time conversions.

libpcp: time_t sentinel fix, add time parsers using timespecs

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec

This ensures that the pcp-selinux package and all it's dependencies are
not pulled into containers and other systems that do not use SELinux.
https://fedoraproject.org/wiki/SELinux/IndependentPolicy#Adding_dependency_to_the_spec_file_of_corresponding_package
This rpm syntax is called "boolean dependencies" and is supported since rpm 4.13 (>= RHEL 8).
https://rpm-software-management.github.io/rpm/manual/boolean_dependencies.html
Co-authored-by: Vit Mojzis <vmojzis@redhat.com>
Resolves: rhbz#2050838

selinux: switch to conditional dependency

---

man/man1/pmval.1
qa/443.out
qa/src/exertz.c
qa/src/xlog.c
src/dbpmda/src/dso.c
src/include/pcp/libpcp.h
src/include/pcp/pmapi.h
src/libpcp/src/GNUmakefile
src/libpcp/src/check-statics
src/libpcp/src/config.c
src/libpcp/src/connectlocal.c
src/libpcp/src/exports.in
src/libpcp/src/getopt.c
src/libpcp/src/getopt2.c
src/libpcp/src/getopt3.c
src/libpcp/src/internal.h
src/libpcp/src/logutil.c
src/libpcp/src/tv.c
src/libpcp_fault/src/GNUmakefile
src/libpcp_static/src/GNUmakefile
src/pmcd/src/config.c
src/pmval/pmval.c
src/pmval/pmval.h
src/python/pmapi.c

Provide new APIs to access the v3 log labels start timestamp
in high resolution form, as well as optional zoneinfo field,
in the form of pmGetHighResArchiveLabel(3).  The context end
of archive timestamp is made available in high resolution too
via a new pmGetHighResArchiveEnd routine.
Update the pmGetOptions routine to support a v3 ABI such that
PMAPI client tools can opt-in to working with nanosecond time
throughout.  pmval is converted as a proof of concept.
Resolves https://github.com/performancecopilot/pcp/issues/1372
Resolves https://github.com/performancecopilot/pcp/issues/1374
Resolves https://github.com/performancecopilot/pcp/issues/1377

libpcp: high resolution log label and time window APIs

---

.pylintrc
scripts/man-lint
src/pcp/atop/pcp-atop.1
src/pcp/dstat/pcp-dstat.py
src/pcp/mpstat/pcp-mpstat.py
src/pcp2influxdb/pcp2influxdb.py
src/pcp2zabbix/pcp2zabbix.py
src/pmdas/bcc/modules/biotop.python
src/pmdas/bcc/modules/ucalls.python
src/pmdas/bcc/modules/ustat.python
src/pmdas/lmsensors/pmdalmsensors.python
src/pmdas/mssql/pmdamssql.python
src/pmdas/openmetrics/pmdaopenmetrics.python
src/pmdas/openvswitch/pmdaopenvswitch.python
src/pmdas/rabbitmq/pmdarabbitmq.python
src/python/pcp/pmapi.py
src/python/pcp/pmconfig.py

Contains a few syntax updates to make the Python code more 'pythonic', otherwise no functional change.

ci: fix pylint and mandoc linter warnings

---

man/man3/pmwebapi.3
qa/1697
qa/1697.out
qa/group
src/libpcp_web/src/query.c
src/pmproxy/src/http.c
src/pmproxy/src/http.h
src/pmproxy/src/series.c

Most pmseries REST API methods accept a comma-separated list of series
ids. Each series id is 40 bytes, therefore requesting data for many
series at once can generate a query string which exceeds the maximum
size of an URL.
This commit allows to optionally submit the request parameters in the
body of the HTTP request.
Breaking change warning: Previously it was possible to submit the `expr` parameter for `/series/load` and `/series/query` in the response body, and the `series` parameter as a newline-separated list of series ids. This functionality wasn't documented (correct me if I'm wrong), so afaics it should be fine to replace it with accepting the request body for all current REST API methods in the standardized urlencoding format.
fyi, corresponding grafana-pcp PR: …

pmproxy: allow request parameters to be sent in the request body

---

src/pmdas/bpf/.gitignore
src/pmdas/bpf/bpf.c
src/pmdas/bpf/modules/biolatency.c
src/pmdas/bpf/modules/runqlat.c

Every bpf PMDA module gets two parameters passed in the init function: `init(dict *cfg, char *module_name)`
`cfg` is the global configuration object (with contents of `bpf.conf`) and `module_name` is for example `biolatency.so`.
This PR `free`s the configuration object at shutdown, and the `module_name` after calling `init()` of the module.
imho that's inconsistent, and I'm now very happy with it - however, what's an elegant way to keep references to the `module_name` of each module and `free` it in `bpf_shutdown`? One option would be to create a linked list of these pointers, but I'm sure there is a better option ... Maybe just pass the memory allocated by `pmdaCacheStore` to the `init()` function? Doesn't seem very neat either.

pmdabpf: resolve memory leaks, destroy bpf skeleton object at shutdown

---

configure

- introduces extra handling for macosx 11.* and 12.*.  Old configure script has a setting which assumes x86 for all systems and uses "-arch x86_64" for the compiler - that's no longer true as 11.* and later also support aarch64/Apple silicon
- Current gcc from brew (the most common mac os x package system for opensource soft) has a GCC-11 build which does not know "-no-cpp-precomp", so with this fix we do not use -no-cpp-precomp on 11.* and 12.*
Note: this is not fixing PCP build on current Mac OS X/apple silicon completely, but it's a required piece in the right direction.

Fix macosx autoconfig setup

---

src/include/pcp.conf.in

This path is /etc/sysconfig and it's used on Red Hat/Fedora and
SUSE systems. Adjust the comment to accurately reflect that.

pcp.conf.in: Fix comment on standard sysconfig path

---

src/libpcp/src/fetchgroup.c

Looking into some pcp-ss issues I immediately encountered a
noticable elapsed time difference between executing just ss
versus pcp-ss.  It turned out it was due to fetchgroup code
not really understanding how the underlying indom APIs work
and repeatedly refreshing shared indoms (all metrics in the
pcp-ss tool actually share one indom) once for every metric
that happens to use that indom - i.e. many times per fetch.
These changes resulted in a 5x speedup in pcp-ss and it now
completes instantly as expected.  Additionally, we use alot
less memory now for the many-metrics-sharing-an-indom case.

libpcp: optimize indom handling in fetchgroup code

---

src/pmdas/linux_proc/cgroups.c

Jan Kurik encountered this issue when running the regression
testsuite (especially qa/359) on non-x86_64 architectures.
Something must've changed in the toolchain recently on these
platforms since we've not seen this before, but this bug has
been in our code for some time.  It works everywhere else by
good fortune, when there just happen to be NULLs after these
cgroups CPU parsing data structures.
Resolves Red Hat BZ #2081262.

pmdaproc: fix cgroup cpu metrics refresh structures

---

src/pcp/dstat/pcp-dstat.py
src/pmdas/elasticsearch/pmdaelasticsearch.python
src/pmdas/haproxy/pmdahaproxy.python
src/python/pcp/pmconfig.py

a couple of minor Python fixes:
* don't modify the dict while iterating over it
* variables should be declared before the try/except block; in the `except` block, don't access variables declared in the `try` block
* don't shadow the `error` variable when nesting try/except blocks

chore: fix pylint errors

---

qa/1931
qa/common.bpf

Fixes: 2d9476cb0 ("qa/1931: pmdabpf: execsnoop")

pmdabpf: check libbpf version before running any qa

---

build/ci/ci-run.py

Fixes the following error in the GitHub Action VM:
error running container: error from /usr/bin/crun creating container for [/bin/sh -c dnf install -y systemd sudo glibc-langpack-en]: sd-bus call: Connection reset by peer
https://github.community/t/error-running-container-error-from-usr-bin-crun-creating-container-for-bin-sh-c-dnf-update-y-nobest-sd-bus-call-connection-reset-by-peer-1994/261522
https://github.com/containers/buildah/issues/3887

ci: unset XDG_RUNTIME_DIR when invoking podman

---

src/pcp/pidstat/pcp-pidstat.py

Note that this PR is layered on PR #1585, where the `DRY out ...` commit lives.

Correct operation of `pidstat -p ALL|SELF`

---

src/pmlogger/GNUmakefile
src/pmlogger/pmlogger_check.sh
src/pmlogger/pmlogger_farm.defaults

Provide a mechanism whereby the farm loggers can be configured.
There has been reluctance in the past to sharing configuration
of the local primary logger, so these are now done separately.
Makes sense to me as the primary pmlogger may need to use more
frequent sampling, may not want to allow remote pmlc, etc.
Resolves Red Hat BZ #2101574

pmlogger_farm: add default configuration file for farm loggers

---

qa/1936
qa/1936.out
qa/group
src/pmclient/pmclient.c
src/pmclient/pmclient_fg.c
src/pmdas/mmv/mmvdump.c

Since the pmclient implementations are shipped as demo
programs, we shouldn't be making any use of libpcp.h -
this is unavailable via /usr/include/pcp for 3rd party
code.  Providing a local timeval_sleep routine gets us
there as this was the only double-underscore API being
used.

pmclient: remove reliance on libpcp.h for timed sleep

---

src/include/pcp/pmapi.h
src/libpcp/src/exports.in
src/libpcp/src/fetch.c
src/libpcp_web/src/load.c

Run pmFetchArchive() in a worker thread instead of the main thread because it uses blocking (synchronous) I/O calls.
This way the libuv loop does not get blocked, and queued Redis requests can be sent out while the worker thread is reading PCP archives. As a side effect, this also breaks the recursion as mentioned in #1605.
I think this is a better solution than #1605 for the same problem. It wasn't actually much new code, mainly moving existing code around. On my system, with pcp-zeroconf (10s logging interval) it takes about 1:30 minutes to load one archive (i.e. one day of metrics) into Redis (ignoring the proc.* metrics, as done in #1632). Without this commit, it segfaults due to the recursion, as mentioned in #1605 (it does work with archives in the `qa` directory though, afaics they …

libpcp_web: run pmFetchArchive() in a worker thread

---

qa/1211
qa/1211.out
src/pmseries/pmseries.c

Tighten the checks around what makes up a series identifier,
so that we don't misclassify legitimate queries as SIDs.
Related to https://github.com/performancecopilot/pcp/pull/1638

pmseries: fix assumption that any 40-character string is a SID

---

qa/1900.out
qa/common.bpf
src/pmdas/bpf/bpf.c

Resolves problems in the way the cluster and indom cache
(pmdaCache) operations were being used.  Firstly, due to
a mix up in the first parameter passed to the interfaces
used for persistence we were not actually persisting the
cluster/indom identifiers, despite best intentions to do
so.
Second, we must reserve the first two indom identifiers
(0 and 1) for the internal cache indoms - guarantee this
now through force-setting this before loading anything.
Finally, the QA tests were susceptible to indeterminism
in the situation where an existing setup has persisted
different BPF script identifiers to those used by tests.

pmdabpf: fix persistence of indom and cluster identifiers

---

qa/1900.out
qa/common.bpf

Note: The order in which bpf PMDA modules get added to the cluster cache
does not depend on the order in bpf.conf, but on the dictGetIterator()
iterator (iterating over the sections in bpf.conf).

qa: fix indom cache path in qa/1900

---

src/pmdas/openvswitch/pmdaopenvswitch.python

OVS coverage stats provide detail view into OpenFlow counters and drops.
This is required by pmie OVS rules that will be added in next commit.
The logs of pmie rules will be consumed by RedHat Insights tool further.
Signed-off-by: Veda Barrenkala <vedabarrenkala@gmail.com>

pmdas/openvswitch: add support to parse coverage stats

---

qa/1214
qa/1360
qa/triaged
src/libpcp_web/src/query.c

In the situation where we are calling a function based on an
expanded fabricted SID, we need to pass the userdata rather
than the baton pointer, as this is holding the baton in this
special case situation.  If not we may attempt dereferencing
an invalid pointer in the high level API calling code, such
as pmproxy, when handling error conditions (pmseries_log).
This resolves a crash when handling query division, but logic
errors remain to be sorted out on that code path (fix is WIP).
Related to https://github.com/performancecopilot/pcp/issues/1636

libpcp_web: ensure a valid baton is passed to query functions

---

src/pmdas/linux_proc/help_text.h

This fixes qa/662 on Ubuntu 18.04

procpmda: replace non-ascii apostrophe with ascii apostrophe in psinfo.cguest_time helptext

---

qa/1602
qa/triaged
src/libpcp_web/src/slots.c

The buffer can contain multiple Redis requests (Redis pipelining).
Previously, if the buffer contained multiple Redis requests, redisSlotsRequest was called with multiple Redis requests.
This triggered an assertion in hiredis code, because only one reply per request is expected, but in this case it received multiple replies.
This fixes qa/1214.

libpcp_web: Redis proxying: support Redis pipelining

---

src/pmdas/smart/smart_stats.c

The smartctl output uses a dot as a thousands separator when the system
is configured with a German locale. The input parsing code didn't handle
this case correctly.
This commit runs LC_ALL=C smartctl, i.e. resetting the locale to a
fixed locale, irrespective of the user's configured locale.
To avoid pitfalls like this in the future, it would be better if the PMDA reads the JSON output of `smartctl` (`-j` flag).

pmdasmart: set LC_ALL=C before running smartctl

---

src/libpcp/src/check-statics

Using `/` as separator in `sed` fails when `$obj` contains that character, as is the case for `deps/jsonsl/jsonsl.o`. I propose using `!` as an alternative.

src/libpcp/src/check-statics: fix regexp error with objects in subdirectories

---

src/pmproxy/src/series.c
src/pmproxy/src/server.c

This resolves multiple race conditions when the client closes the connection before the REST API is sending the entire response.
Case 1: Client sends request, Redis is queried, client closes connection due to timeout and client struct gets freed, Redis reply arrives and is getting sent to the already free'd client. Added locks in `pmseries_request_done`/`on_pmseries_done`.
Case 2: client_write checks if the client is still opened, and then calls uv_callback_fire which calls on_write_callback in a later loop iteration. Meanwhile, the client could be closed. Solved by adding another client_is_closed check in on_write_callback.
Case 3: Guard client struct while client_write/uv_callback_fire and on_write_callback. Client connection could be closed, and the client free'd meanwhile.
I only …

libpcp_web: guard client struct during callbacks

---

src/pmdas/bpf/modules/bashreadline.c
src/pmdas/bpf/modules/execsnoop.c
src/pmdas/bpf/modules/exitsnoop.c
src/pmdas/bpf/modules/fsslower.c
src/pmdas/bpf/modules/mountsnoop.c
src/pmdas/bpf/modules/oomkill.c
src/pmdas/bpf/modules/opensnoop.c
src/pmdas/bpf/modules/statsnoop.c
src/pmdas/bpf/modules/tcpconnect.c
src/pmdas/bpf/modules/tcpconnlat.c

After noticing delays when sampling bpf.* metrics, we found the multiple calls to perf_buffer__poll with a small-number-of-milliseconds timeout were all adding up.  After discussions with Andreas, Jason and Sohaib we believe it is safe to set no timeout on this call, such that it returns immediately when called (whether values are available or not).
This change brings a 1-2sec pmdabpf sample time (with several modules enabled) down to around 10-20msec.

pmdabpf: set perf_buffer__poll timeout to 0

---

src/pcp/dstat/pcp-dstat.1
src/pcp/dstat/pcp-dstat.py

After a number of complaints about the "N missed ticks" reporting from dstat from users on very large systems with many disks, this introduces a command line argument to optionally suppress it.
In the cases we've seen, its been confirmed that the increased sample time is spent in the kernel with the large device count - not something we can do anything about anyway.
This change has been tested by artificially inducing the failure mode as I have no local systems showing this behaviour live.  We cannot use archives for this either as we do not do sub-sampling for historical data in pcp-dstat.
Resolves Red Hat BZ #2083897

pcp-dstat: add --nomissed command line option for large systems

---

qa/1604
qa/1604.out
qa/admin/package-lists/Fedora+36+x86_64
qa/admin/package-lists/Fedora+37+x86_64
qa/admin/package-lists/Ubuntu+20.04+x86_64
qa/admin/package-lists/Ubuntu+22.04+x86_64
qa/group
src/libpcp_web/src/query.c

If the start timestamp is before the first sample of a series, or the series has gaps, the goal timestamp will lag behind the next timestamp, and therefore the logic will always select the next sample.
This commit resets the goal timestamp if it lags behind.
As mentioned in the description, this is mainly occurring if the `start=` parameter is set to a timestamp before the first sample of a series - a common case when analyzing archives with the `quay.io/performancecopilot/archive-analysis` container. If that's the case, pmproxy sends all samples (because the `goal` timestamp always lags behind), effectively ignoring the `interval=` parameter, resulting in much larger reponse sizes. But it can also occur if there are gaps in a series.
Tests with a (customer) archive show that this PR …

pmseries: fix sampling when start < first sample or series has gaps

---

qa/1985
qa/1985.out
qa/1986
qa/1986.out
qa/group
src/libpcp_web/src/webgroup.c
src/pmfind/source.c

Resolve libpcp_web handling in any cases with no MMV metrics being updated but still using webgroups (pmfind use case). New regression tests 1985 and 1986 are added to exercise the fix - which uncovered memory leaks primarily during shutdown through their use of valgrind.  These cases are also fixed.
Resolves Red Hat bugzilla #2135314

pmfind, libpcp_web: MMV and shutdown memory management fixes

---

src/pmdas/snmp/GNUmakefile

When running ./Install of the agent, the following line is printed in
/var/log/pcp/pmcd/snmp.log.
```
Log for pmdasnmp on pcp-netsnmp started Tue Oct 18 22:45:23 2022
opening /var/lib/pcp/pmdas/snmp/snmp.conf No such file or directory at /var/lib/pcp/pmdas/snmp/pmdasnmp.pl line 90.
```
As a result, pmdasnmp.pl cannot read its configuration file though it is "./Install"ed.

 pmdas/snmp: install the agent specific configuration file to PMDATMPDIR 

---

src/pmieconf/filesys/localdefs
src/pmieconf/filesys/vfs_files

Signed-off-by: Rahul Srivastava <rasrivas@redhat.com>
New `vfs_files` PMIE rule.

New PMIE rule vfs_files

---

src/pcp/dstat/pcp-dstat.py
src/pcp/dstat/plugins/net

When using `dstat --net-packets` with more network interfaces (defined by `-N`), both terminal and CSV outputs are corrupted, e.g.
This patch fixes this.
The output is the same (up to general differences) as with the original no-pcp `dstat` command.

dstat: fix columns for --net-packets with multiple network interfaces

---

src/pcp/pidstat/pcp-pidstat.py
src/pcp/ps/pcp-ps.py

Pcp ps and pcp pidstat give broken pipe errors while their output is the pipe to head.
It is because when the head is done reading data it stops prematurely the pipe, which needs to be handled in python as an IOexpection and terminate the program gracefully.

Pcp ps and pcp pidstat give broken pipe errors while output is piped to head

---

qa/1191.out
qa/1221.out
qa/1342
qa/1727
qa/1727.out
qa/openmetrics/samples/vmware_exporter.txt
src/pmdas/openmetrics/pmdaopenmetrics.python

Its possible pmdaopenmetrics is fed garbage accidentally, e.g. in the case where a /metrics end point is not made visible and an HTTP error response is returned (misconfiguration).
Failure to safeguard this results in the generation of diagnostics in the openmetrics PMDA log file at an alarming rate until all available filesystem space is completely consumed.  It can also result in bogus metric names being exposed to PMAPI clients.
This commit both adds new safeguards and scales back diagnostic noise from the agent.  In some places it switches to more appropriate APIs for the level of logging being performed (esp. debug messages).
Resolves Red Hat BZ #2139325

pmdaopenmetrics: validate given names before using them for metrics

---

qa/798.out.32
qa/798.out.64
qa/nfsclient/mountstats-el8.7-rdma.qa
src/pmdas/nfsclient/pmdanfsclient.python

This bug fix kindly brought to you by the good folk at Penn State Uni. Regression test update by myself but the real fix came from others.
Resolves Red Hat BZ #2150889

pmdanfsclient: fix srcport handling for rdma and udp mounts

---

configure.ac

Avoid calling the undeclared exit function.  Include <string.h> for strcmp.  C99 removed implicit function declarations from the language, and future compilers are likely to reject them by default.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC

configure.ac: Fixes for improved C99 compatibility

---

src/pmdas/statsd/README.md
src/pmdas/statsd/pmdastatsd.1
src/pmdas/statsd/src/aggregator-metric-labels.c
src/pmdas/statsd/src/aggregator-metrics.c
src/pmdas/statsd/src/parser-basic.c
src/pmdas/statsd/src/parser-ragel.c.in
src/pmdas/statsd/src/parser-ragel.rl

I wanted to create some nice FSM visualizations, since `ragel` allows generating Graphviz dot files. Thats when I learned that the parser was more or less an abomination-ish. I refactored it. Since the Ragel version is much easier to maintain, considering I can visualize the FSM, I wonder if there is even a point to having two parsers at all.
See below images for comparison (error/default transitions omitted):
BEFORE:
AFTER:
I added some logging as well, but since it checks for verbosity level each time at runtime, I wonder if thats a good thing?

statsd: ragel parser refactor

---

src/pcp/mpstat/pcp-mpstat.py

Error handling for the current value ,user_time and so on function has been added. It has been observed that when the custom pcp conf has been installed,the first archive created by the the pcp-zeroconf gives an problem with pcp-mpstat uitlity.

pcp-mpstat: Error handling for the current values

---

configure
configure.ac

If QTDIR is empty, the search path for qmake/qtchooser will start with /bin. On FC37, there is a /bin/qmake for QT6.

configure.ac: Use QTDIR search path only when given

---

configure
configure.ac
qa/1475
qa/1810
src/pmdas/bpf/GNUmakefile
src/pmdas/bpf/modules/GNUmakefile

This aims to resolve recent fallout on Fedora36 which, although a recent Fedora, does not have the symbols we need for latest pmdabpf modules.
This is an alternative approach to #1728 which keeps our pmdabpf modules using the system libbpf at runtime.

build: require libbpf 1.0 for mountsnoop and oomkill bpf modules

---

build/rpm/redhat.spec
configure
configure.ac
debian/fixcontrol

Recent updates to the vendored bcc code resulted in a newer version of libbpf-tools/compat.c merged which uses bpf_map__set_autocreate. This is only available in libbpf 0.8.0 and later and quite a few of the shipped modules are affected as a result.
This resolves a series of CI problems observed in the f36 BPF tests.

build: raise the minimum libbpf version to 0.8.0

---

.github/workflows/qa.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

build: update actions set-output handling based on githubs advice

---

src/pmdas/bcc/Upgrade
src/pmdas/kvm/Upgrade
src/pmdas/mssql/Upgrade
src/pmdas/openmetrics/Upgrade
src/pmdas/postgresql/Upgrade

It was observed that pmcd.conf inode modification times were updated on every restart of pmcd.  Turns out its because of the PMDA Upgrade scripts, where some were using 'sed -i' to affect a no-op change to the contents.  We're now take more care ensuring sed is only done when the contents of the file are definitely going to be modified.
Resolves Red Hat BZ #2166819.

rc scripts: ensure pmcd.conf not rewritten unnecessarily

---

qa/1709.out
qa/statsd/src/cases/03.py
src/pmdas/statsd/src/aggregator-metrics.c
src/pmdas/statsd/src/pmdastatsd.c

The blocklisted metric names weren't being matched properly so they werent actually blocklisted - for some reason they didn't end up being mapped to PCP metrics, so outwardly only incorrect thing about the ordeal were the internal stats metrics which didn't add up which is how I found out about this. Not sure what I was thinking when I was writing that code 4 years ago.

fix(statsd): internal stats and blocklisted metric names alignment

---

src/pmdas/hacluster/help

the field ha_cluster.pacemaker.nodes.status.dc actually tracks whether the node is the DC in the cluster or not.

Update help with proper description of DC status

---

src/pmieconf/.gitignore
src/pmieconf/GNUmakefile
src/pmieconf/testing/localdefs
src/pmieconf/testing/test_actions

Problem with using primary is that it is automatically enabled as part of the primary pmie startup and thats not whats needed for this diagnostic rule.
Resolves Red Hat BZ #2223348

pmieconf: move test_action from primary into a separate group

---

src/selinux/pcp.te

Refactoring in core selinux policy has impacted on pmproxy.
Resolves Red Hat BZ #2223568

selinux: add policy updates for pmproxy (io_uring,ipc_lock)

---

configure
configure.ac

This removes ambiguity that can cause applications using PCP python APIs to fail when users have unusual settings for their PATH or are using a python venv, for example.
Resolves Red Hat BZ #2227011

build: default to using a path-prefixed PCP_PYTHON_PROG

---

qa/1567
qa/1567.out
src/pmieconf/global/pcp_actions
src/pmieconf/pmie_webhook

The pmieconf webhook action was initially created for Event Driven Ansible (EDA); two issues have been resolved related
- using the JSON key "values" conflicts with something deep down in EDA that also interprets this JSON.  Use "message", which is more descriptive of the content anyway.
- there is no easily accessible hostname JSON key - add one via the usual %h pmie action string expansion.
Related to Red Hat BZ #2185803

pmieconf: update webhook action for better EDA integration

---

qa/1940
qa/1940.out
qa/group
src/pmlogconf/pmlogconf.c
src/pmlogconf/pmrepconf.c

The fsync during pmlogconf probe was originally added to
attempt to improve robustness.  However, it can have the
opposite effect - on a busy system (like after a package
upgrade across the OS), and during boot, it may induce a
slowdown that brings systemd service timeouts into play,
since its run during pmlogger service start.
It's hypothesized this is the root cause of BZ 2229441 -
a detailed valgrind-based forensic analysis has found no
possible cause within pmlogconf itself there.
Related to Fedora BZ 2229441.

pmlogconf: remove latency-inducing fsync on config write

---

qa/admin/package-lists/Debian+12.1+x86_64

I ran the list-packages script in the qa/admin directory on a Debian 12.1 virtual machine. The output was a list of packages that could be added to the qa/admin/package-lists/Debian+12.1+x86_64. This PR adds those packages.

Add packages to Debian 12.1 package-lists

---

.github/workflows/release.yml

This partially addresses #1771 by uploading tarballs of release artifacts for each release platform. This is not a replacement for a proper repository, but at least makes the packages accessible.

Add tarball upload to release workflow

---

src/pcp/buddyinfo/pcp-buddyinfo.py

python2 doesn't support f-string formatting
so changed it to the '%' string formatting so that it wroks with both python2 and python3

Fixed pcp-buddyinfo key issue with python2

---

man/man1/pmlogredact.1
man/man1/pmlogreduce.1
man/man1/pmlogrewrite.1
src/pmlogredact/GNUmakefile
src/pmlogreduce/GNUmakefile
src/pmlogrewrite/GNUmakefile

Several pmlog*tools have been traditionally installed into the (internal) PCP_BINADM_DIR.  Move these to /usr/bin and maintain the earlier path via symlinks as has been done in the past to ensure we don't break existing installations - this makes it easier for people to find these as sometimes we do want to run them directly/interactively too, and not exclusively via the automated pmlogger scripts.
Affects pmlogredact(1), pmlogreduce(1) and pmlogrewrite(1).

build: install some pmlogtools onto the default PATH

---

src/pmdas/haproxy/connect

From qa/1110 on rawhide
> $PCP_VAR_DIR/pmdas/haproxy/connect:60: SyntaxWarning: invalid escape sequence '\&'
Python 3.12 is producing errors on invalid escape sequences embedded in strings on rawhide - use double-backslash which seems to be the original intention here.

pmdahaproxy: fix connect script handling of string quoting

---

qa/1973.out
src/pcp/zoneinfo/pcp-zoneinfo.py

An earlier attempt missed a couple of locations where unsorted nodes and zones could occur, affecting output.
Fixes qa/1973.

pcp-zoneinfo: ensure determinism in pcp-zoneinfo output

---

src/pmdas/gfs2/GNUmakefile

Correct permissions to 755 instead of 775 in makefile for GFS2 PMDA.

pmdagfs2: Correct permissions in makefile (v2)

---

build/containers/archive-analysis/Dockerfile

Updates the base image for the fedora container from 36 to 38 as 36 is out of support.

Update fedora container to 38

---

qa/1973.out
src/pcp/zoneinfo/pcp-zoneinfo.py

The requirement of __print_old_version_values is because the older version of PCP metrics is giving data for movable zones also. For eg:- In an older version
$ pminfo -f mem.zoneinfo.nr_vmscan_write
mem.zoneinfo.nr_vmscan_write
inst [0 or "DMA::node0"] value 0
inst [1 or "DMA32::node0"] value 0
inst [2 or "Normal::node0"] value 0
inst [3 or "Movable::node0"] value 0
inst [4 or "Device::node0"] value 0
$ pcp --version
pcp version 4.3.2
$
but with the latest version
$ pminfo -f mem.zoneinfo.nr_vmscan_write
mem.zoneinfo.nr_vmscan_write
inst [0 or "node0"] value 0
$ pcp --version
pcp version 6.1.1
$
So to make it consistent we have implemented new print function

pcp-zoneinfo:Fixing the issue where pcp-zoneinfo utility will fail with older version of pcp

---

src/selinux/pcp.te

With the 65b9e0bdceb ("Implement proper anon_inode support") selinux-policy commit, individual SELinux types are used for each anon_inode type, so domains using any of them need corresponding allow rules.

Allow pcp-pmproxy read and write to the io_uring api

---

man/man1/pmseries.1
src/libpcp_web/src/config.c

======== Commit message ========
~~~
Extending utility of PCP_* environment variables to be generally
usable to override settings detected via libpcp_web config.c
Introduces canonical form of config options as:
"PCP_<SECTION|GROUP>_<OPTION|KEY>"
where dots '.' are represented as underscores '_'.
Example usage:
$ export PCP_PMSERIERS_STREAM_MAXLEN=424242
$ pmseries --load <archive> -Dlibweb
...
pmIniFileParse set pmseries.stream.maxlen = 424242
Primary motivation was to create an easy and convenient way to
to adjust configuration inside the archive-analysis container.
~~~
========= Extra info ===========
The archive analysis container uses `pmseries --load` to add the archive data into the Redis DB. However it always passes the optional MAXLEN parameter to Redis XADD command (see …

libpcp_web: implement config override by canonical env vars

---

src/pmdas/denki/denki.c

Coverity scan reports a pmdadenki string termination issue - switch to using pmsprintf(3), and use it consistently in a second similar location, to ensure valid string construction.

pmdadenki: ensure copied env var string termination (covscan)

---

src/pmdas/linux/pmda.c

Drop several callbacks in the Linux PMDA which can pass directly through to the libpcp_pmda implementation now; these days we have no dynamic metrics in this PMDA - it does get copied into new PMDAs that folk create though, when pmdalinux is used as a reference.

pmdalinux: remove callbacks relating to dynamic metrics

---

src/pcp/atop/deviate.c

Improve code resiliency in the presence of NUMA nodes appearing after the initial sample(s).

pcp-atop: resolve segv encountered on a multi-node NUMA system

---

qa/1543
qa/1543.out
src/include/builddefs.in
src/pmproxy/src/GNUmakefile
src/pmproxy/src/http.c
src/pmproxy/src/http.h
src/pmproxy/src/server.c
src/pmproxy/src/server.h

Add http compression to the REST API for grafana-pcp where large transfers have been observed with pmseries queries. This implementation supports zlib compression only so far. Additionally, several new http metrics are added to pmproxy showing compression effectiveness.
Resolves #1685

pmproxy: support http compression

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec

Drop of i386/i686 builds from Fedora to avoid conflicts in installed RPMs. Alignment with
https://fedoraproject.org/wiki/Changes/EncourageI686LeafRemoval 
Resolves: bz#2248841

Proposed drop of i386/i686 architectures from build

---

CODE_OF_CONDUCT.md
README.md

This is a formalisation - via the ['Contributor Covenant'](https://www.contributor-covenant.org/) - of discussions around commit adc53b72f7

docs: add an explicit code-of-conduct for PCP and a README link

---

src/pcp/geolocate/pcp-geolocate.py

Avoids "TypeError: the JSON object must be str, not 'bytes'" with (at least) python 3.5 and 2.7.

pcp-geolocate: make it work with older versions of python

---

src/pmns/pmnsmerge.c

Evidently this routine may be called on to compare an object to itself which was then observed to result in an infinite loop.  Thanks Florian!
Resolves Fedora BZ #2251744

pmnsmerge: be more defensive in qsort comparison routine

---

.github/workflows/main.yml
build/containers/pcp/Dockerfile

The github action to build and publish the container will no longer run in forked repositories. Additionally, the container has been updated from fedora 36 to fedora 38.

Skip container build on forked repository and update to fedora 38

---

src/pcp/atop/showlinux.c
src/pmlogsize/data.c
src/pmlogsize/meta.c

Two more cases, based on analysis of rawhide CI failures.

Further qsort compare tweaks

---

src/pcp/ss/pcp-ss.py

Cleanup of remained code for unix and raw sockets causing `pcp-ss` to crash, generating a traceback.
This pull request fixes crash of  `pcp-ss` when it is run with `-t` or `-u` option:
```
Netid  State  Recv-Q Send-Q        Local Address:Port Peer Address:Port          Process
udp   ESTAB         0     0      10.0.185.202%eth0:68 10.0.187.254:67          
File "/usr/libexec/pcp/bin/pcp-ss", line 374, in <module>
ss.report()
File "/usr/libexec/pcp/bin/pcp-ss", line 299, in report
if not self.filter_netid(inst) or not self.filter_listening(inst):
File "/usr/libexec/pcp/bin/pcp-ss", line 256, in filter_netid
elif self.args.unix and netid == "unix":
AttributeError: 'Namespace' object has no attribute 'unix'
```

Fixed crash of pcp-ss when using -t/-u option

---

configure
configure.ac
src/pmdas/postgresql/pmdapostgresql.python

Python PostgreSQL connector psycopg2 has a successor psycopg3 that is actually packaged as psycopg as the Python library name.
This change allows building it with both and expects the API of both being the same.

Support psycopg3 as well

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec
qa/admin/other-packages/manifest
qa/admin/package-lists/CentOS+Stream9+x86_64
qa/admin/package-lists/Fedora+36+x86_64
qa/admin/package-lists/Fedora+37+x86_64
qa/admin/package-lists/Fedora+38+x86_64
qa/admin/package-lists/Fedora+39+x86_64
qa/admin/package-lists/Fedora+40+x86_64
qa/admin/package-lists/openSUSE+15.5+x86_64
qa/admin/package-lists/openSUSE+15.6+x86_64

Fedora rawhide has recently removed this package, so this resolves the CI fallout as well as removing a historical build dep.

build: drop dependency on bpftool as local version used nowadays

---

src/pmdas/linux/ipc.c

They have always been saved but looks the restore was missed.

pmdalinux: restore IPC indoms from disk on first access

---

src/python/pcp/pmapi.py

Fix for `day of year out of range` on 2024-01-01, due to self.tm_yday - 1, which returns `[2024, 1, 1, 2, 3, 0, 0, -1, 0]`. The range for tm_yday should be [1, 366]. Related RH case #03734598.
https://docs.python.org/3.6/library/time.html#time.struct_time
```
File "/usr/libexec/pcp/bin/pcp-mpstat", line 710, in <module>
sts = manager.run()
File "/usr/lib64/python3.9/site-packages/pcp/pmcc.py", line 687, in run
self._printer.report(self)
File "/usr/libexec/pcp/bin/pcp-mpstat", line 661, in report
self.print_machine_info(group, manager)
File "/usr/libexec/pcp/bin/pcp-mpstat", line 615, in print_machine_info
time_string = time.strftime("%x", timestamp.struct_time())
ValueError: day of year out of range
Linux  5.14.0-362.18.1.el9_3.x86_64 …
```

pmapi.py : fix for struct_time() day of year out of range on yyyy-01-01

---

src/pmdas/linux/ipc.c

This reverts commit d6e61bdcb8ba14b1e8824961fda81ea78481f466.

Revert "pmdalinux: restore IPC indoms from disk on first access"

---

vendor/github.com/iovisor/bcc/libbpf-tools/.gitmodules

Add submodule for vendor/github.com/iovisor/bcc/libbpf-tools/blazesym to avoid issues with: git submodule update 
Add submodule for _vendor/github.com/iovisor/bcc/libbpf-tools/blazesym_ to avoid issues with: _git submodule update --init --recursive._
Wondering about blazesym though and if there is some cleanup needed here. It is a rust module that only seems to be referenced by _vendor/github.com/iovisor/bcc/libbpf-tools/opensnoop.c._. The patch also removes
_vendor/github.com/iovisor/bcc/libbpf-tools/{blazesym,bpftool)_ as **git submodule update --init --recursive** complains otherwise. bpftool is actually populated in _vendor/github.com/libbpf/bpftool_

Add submodule for blazesym

---

src/pmlogconf/pmrepconf.c

Directly using metric names as pmrep metric identifiers causes an issue for metrics named with pmrep keywords (like 'type' in filesys.type) as pmrep interprets this in unintended ways. Fix this (and QA tests 1681, 1682) by using an internal name where dots are removed.

pmrepconf: use a pmrep-internal representation for each metric

---

.github/workflows/ci.yml
.github/workflows/qa.yml
.github/workflows/release.yml
build/ci/platforms/fedora40-container.yml

With the recent change of fedora rawhide becoming fedora 41, the github actions are now missing fedora 40. This patch handles adding back fedora 40 testing and removes fedora 37 testing as that is EOL.

add fedora 40 container testing

---

build/containers/archive-analysis/Dockerfile
build/containers/pcp/Dockerfile

Fedora has moved its primary repository for container images to Quay.io. This commit reflects the relocation.

Fix Fedora base image location

---

src/pcp/dstat/plugins/topio

It seems simple typo. It should be sum of read and write.
top = rate(proc.io.rchar) + rate(proc.io.wchar)
closes #1913

dstat top-io.top should be calculated rchar+wchar.

---

configure
configure.ac

Subtleties of the pmResult handling result in confusion from gcc -Warray-bounds checks - disable it now as its causing QA failures on rawhide when PMDA sample is built from source.

qa: disable array bounds warnings as this causes qa failures

---

qa/1131
qa/1131.out
qa/1589.out
qa/1827
qa/1827.out
src/pcp2openmetrics/GNUmakefile
src/pcp2openmetrics/pcp2openmetrics.1
src/pcp2openmetrics/pcp2openmetrics.py
src/pcp2openmetrics/pythonserver.py

Add tool pcp2openmetrics to support conversion of pcp metrics to open metric format. 
Updated relevant QA tests to test basic functionality of tool as well as HTTP transfer function. 
Updated pcp2json QA test 1589 to use a pythonserver instead of nc to test HTTP functionality.

Addition of pcp2openmetrics tool 

---

configure
configure.ac

Configure scripts use pmdabpf_arch to refer to architecture directory of iovisor/bcc/libbpf-tools, which hold kernel vmlinux.h. For RISC-V, the unique directory name is 'riscv'. We need to sed uname's value riscv64 etc. to adapt this.

riscv: config pmdabpf_arch value

---

man/man1/pmcheck.1
src/pmcheck/checkproc.sh

The script agents are not installed executable for reasons, so loosen the pmcheck executable-agent-check to be regular file based instead.
Fix a typo on the man page while there.

pmcheck: allow for perl/python script agent checks

---

qa/1992
src/pmdas/uwsgi/pmdauwsgi.python

Make the ussgi PMDA more resilient in the presence of no values available, currently this trips an exception in the fetch code.
Similarly, the QA test 1992 needs additional handling for this case as the Install script (correctly) generates warnings about the missing values.

pmdauwsgi: fix failure when no uwsgi values available

---

qa/1491.out
qa/913
qa/913.out
src/pmdas/redis/GNUmakefile
src/pmdas/redis/redis.pmcheck

@kmcdonell here's my first attempt at a pmcheck script, for Redis metrics.
Couple of areas of uncertainty.  I wasn't sure about the protocol for _chk_svc 'state' argument - that one seems to call 'exit' very aggressively (always), which is a problem here because I have other environmental aspects to check too.  I also noticed the use of a local variable called 'exit' in the shell lib code, figured this will end in tears so renamed it to __exit for clarity.  Wondering if all variables in this common file should be updated to use this convention instead of the mixed bag we have currently?
Anyway, please have a look - this seems to do the right thing now for me locally.

pmcheck: add service and metric checks for the redis PMDA

---

src/pmdas/uwsgi/pmdauwsgi.python

The f-format style string formatting wasn't available in earlier versions of python, so switch a log call to a simpler interface. Also reduce verbosity of the agent by default as that log() call is on a frequently used (fetch) code path.

pmdauwsgi: support older versions of python (3.5), reduce logging

---

src/pmdas/linux_zfs/zfs_utils.c

Over time different ZFS metrics files have been used in procfs, this is now causing QA failures due to a verbose diagnostic; as this is an expected situation no longer warn unless debugging.

pmdazfs: quieten diagnostics on missing files, causes QA issues

---

src/pcp/atop/atopsar.c

If local doesn't match the recorded archive timezone, we can get confused in pcp-atopsar when detecting day rollover.  We need to use the libpcp time handling routines in this case - make it so and this should tackle the CI qa/1493 failure.

pcp-atopsar: fix reporting of new day header for alternate TZ

---

src/pmdas/uwsgi/uwsgi.pmcheck

Without which we issue sh errors when PMDA is not installed.
Resolves Red Hat #RHEL-32381

pmdauwsgi: short-circuit handling of pmcheck failure

---

qa/1131
qa/1827
src/python/pcp/pmapi.py

Resolves an issue reporting the HELP line in pcp2openmetrics.

python: pass help text result as string not bytes

---

qa/1684
qa/1684.out
qa/group
qa/src/GNUlocaldefs
qa/src/test_pcp_derived.python
src/python/pcp/pmapi.py

Add test qa/1684 to exercise derived metrics handling in the python wrapper using a test_pcp_derived.python helper utility.
Resolves: #1963

python API: fix return value from pmLoadDerivedConfig

---

src/pcp/dstat/pcp-dstat.py

Recent libpcp changes in derived metrics verifications have meant the pcp-dstat kludge using event.missed as time metric expression no longer functions.  A simpler approach there is to use constant expressions rather than a metric name, and this workaround solves the problem.

pcp-dstat: stop using a nested derived metric in time plugins

---

qa/193
qa/src/test_pcp_sockets.python
src/libpcp/src/pdu.c
src/pmcd/src/client.c
src/pmcd/src/pmcd.c

There have been cases of pmcd.log filling root filesystems with the diagnostics on failure/refusal to accept client connections so now we rate limit these to once-per-minute (with the counter for dropped messages also being logged).
While testing this several cases of verbose socket diagnostics from libpcp/pduread.c __pmGetPDU code were also encountered - these are made conditional via pmDebug.pdu (as in __pmXmitPDU).
Relates to Red Hat bug RHEL-34586
Relates to Github issue #1533

pmcd: rate-limit connection failure logging in case of bursts

---

qa/1992
src/pmdas/uwsgi/pmdauwsgi.python

Testing against a sample uWSGI server application from Sam, this now seems to be resolved.  Minor changes to improve the help text, handling of long-running global counters, and the naming of worker instances.
Resolves Github issue #1964

pmdauwsgi: improve handling of transient uWSGI servers

---

qa/1131
qa/1131.out
qa/1827
qa/1827.out
src/pcp2openmetrics/pcp2openmetrics.1
src/pcp2openmetrics/pcp2openmetrics.py

Updated pcp2openmetrics tool to fix issues: RHEL-39159, RHEL-39132,  RHEL-32983, RHEL-39293.
Added command line option to exclude # PCP 5 comment line Updated output to follow openmetrics format to include _total metric name ending Omitted blank line after each metric output to adhere to prometheus openmetrics parser Added # EOF line to end of text dump to adhere to prometheus openmetrics parser
Updated relevent qa for pcp2openmetric changes

Updated pcp2openmetrics tool to fix issues

---

configure
configure.ac

Some needed API were not available before 2.4.77, increasing the minimum version in configure.

libdrm: Increase minimum version to 2.4.77

---

man/man1/pmstat.1
qa/804.out
src/pmstat/pmstat.c
src/pmstat/pmstat.pmlogger

pmstat: include guest metrics in extra CPU stats

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec

Resolves Red Hat issue #RHEL-39491

build: add rpm dependency on /bin/ps from procps[-ng] packages

---

qa/1222
qa/364
src/pmdas/linux_proc/clusters.h
src/pmdas/linux_proc/help
src/pmdas/linux_proc/help_text.h
src/pmdas/linux_proc/pmda.c
src/pmdas/linux_proc/proc_dynamic.c
src/pmdas/linux_proc/proc_pid.c
src/pmdas/linux_proc/proc_pid.h
src/pmdas/linux_proc/root_proc

This is a first shot for new AMD GPU process metrics.
This patch collects information retrieved from `/proc/<pid>/fdinfo`.
The current implementation accumulates data for each process, walking through all file descriptors and looking for drm and amd entries.
A future patch may be considered to separate the data per drm client ID.

proc: add amdgpu support

---

src/pmdas/bpftrace/GNUmakefile
src/pmdas/bpftrace/Upgrade
src/pmdas/bpftrace/bpftrace/pmda.py

As observed in issue #2026 the bpftrace metrics agent sometimes takes multiple seconds to start up, depending on its persistent configuration and state of the system.
This commit switches it over to use the pmcd 'notready' protocol at startup, like openmetrics and bcc PMDAs do, to address this.
Resolves issue #2029

pmdabpftrace: use notready startup protocol with pmcd

---

qa/1291.out
src/pcp/atop/drawbar.c
src/pcp/atop/photosyst.c

Resolves a strange rendering of the atop bar-mode display when values went negative incorrectly.

pcp-atop: fix units conversion for ipc.shm metric values

---

src/libpcp/src/connectlocal.c

We can treat pmda_proc.so the same as pmda_linux.so in the local context auto-loading code paths since its in exactly the same boat when it comes to default pmcd.conf state.
This resolves a problem report where pcp-htop reports some kernel metrics but the per-process stats are missing, when its fallback-to-local-without-pmcd mode occurs.

libpcp: auto-load the proc PMDA in local context mode

---

src/libpcp_web/src/load.h
src/libpcp_web/src/webgroup.c

Resolves a race condition on client teardown when an unusually long-held connection reference interferes with the client state management during a timeout.  We have been unable to reproduce this through targetted testing programs, but this survived for a full day of testing on a machine that previously was reliably leaking file descriptors every once in a while, with no leaks anymore at all (according to pmcd.openfds and log file audits).
Resolves #1533

libpcp_web: fix a race in webgroup context teardown on timeout

---

qa/1900
qa/triaged

The qa/1900 test makes use of libbpf.  When libbpf probes the linux kernel to check which features are available one of the probes does not fully initialize all the members of the attr struct. Adding suppression entries to qa/valgrind-suppress to catch those specific cases.  An upstream issue has been filed on libbpf to get this addressed:
https://github.com/libbpf/libbpf/issues/845

qa/valgrind-suppress: external libbpf.so does not fully initialize attr

---

qa/1900

If the libbpf debuginfo is not installed, valgrind returns a backtrace of hexadecimal numbers. Those numbers do not match the symbolic functions names used in qa/1900 valgrind suppression file.  Limiting the backtrace matching in the valgrind suppress file to just the syscall function to avoid failures when the libbpf debuginfo is not installed.

qa/1900: Eliminate the need for libbpf debuginfo

---

debian/pcp-conf.install
src/derived/openmetrics.conf

Addition of two files to support new derived metric: addition of files for new openmetrics derived metric: openmetrics.grafana.go_memstats_last_gc_since_start_time_seconds.

addition of files for new openmetrics derived metric: openmetrics.grafana.go_memstats_last_gc_since_start_time_seconds

---

qa/1988.out
src/pcp/meminfo/pcp-meminfo.py

changed timestamp format as well to print date along with time
Signed-off-by: sagar sagar <sagar.sagar@oracle.com>

pcp-meminfo: added timestamp string to make it similar to other utility

---

src/pmdas/openmetrics/GNUmakefile
src/pmdas/openmetrics/vllm.url
src/pmlogconf/openmetrics/localdefs
src/pmlogconf/openmetrics/vllm

Exports the following metrics when vLLM is monitored: https://docs.vllm.ai/en/latest/serving/metrics.html

pmdaopenmetrics: add vLLM metrics support by default

---

src/pmdas/statsd/src/aggregator-metric-counter.c
src/pmdas/statsd/src/aggregator-metric-duration.c
src/pmdas/statsd/src/aggregator-metric-gauge.c
src/pmdas/statsd/src/aggregator-metric-labels.c
src/pmdas/statsd/src/aggregator-metrics.c
src/pmdas/statsd/src/aggregator-metrics.h
src/pmdas/statsd/src/pmda-callbacks.c

Because of uninitialized "committed" flag of internal representation of statsd metric in aggregator-metrics.c `int create_metric(struct agent_config* config, struct statsd_datagram* datagram, struct metric** out)`, counterpart pmdaMetric* could have been created for it in pmda-callbacks.c "create_pcp_metric `static void create_pcp_metric(char* key, struct metric* item, pmdaExt* pmda)`, cause it may have passed the check at pmda-callbacks.c `static void map_metric(char* key, struct metric* item, void* pmda)`.
Internal representation of the statsd metric is the "struct metric* item" argument.
Processing a statsd metric happens in multiple steps, relevant for this is part of thread responsible for aggregation:
add_metric, process_labeled_datagram, remove_metric and mark_metric_as_comitted …

fix(statsd): prevent uncommitted metrics from being mapped to PCP

---

src/pmdas/statsd/src/pmda-callbacks.c

Likely related #2062.
This is likely it, no race conditions, just me not being able to count well. I am kind of surprised that it took such large metric counts
> It seems tome the rehash was slowly happening at a time some other thread updated the hash table (the for (m = 0; m < pmda->e_nmetrics; m++) { was processing 4992th metric out of 5091)?
for it to segfault when it indexed out of bounds in pmdaRehash. Especially cause across multiple passes roughly speaking even after half of that number you would start reaching into memory I didn't allocate.

fix(statsd): keep correct track of pmns mapped metric count

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec
debian/pcp-zeroconf.postinst

When the pcp-zeroconf package install creates config.default for pmie (rather than updating it) ensure correct pcp:pcp ownership.
Resolves Red Hat issue RHEL-59366

build: ensure pmie config.default created with correct ownership

---

src/pmdas/linux/pmda.c

Nikhil Jain reported and diagnosed a NaN value from tmpfs.full on his system, this commit adds protection for several places where a division-by-zero could occur in the Linux PMDA.

pmdalinux: ensure divide-by-zero cannot happen with tmpfs.full

---

qa/common

Current releases of Fedora have tighter default settings for home directory permissions, which is tripping common script warning code when running QA tests; e.g.
Warning: parent directory /home/nathans (mode:drwx------.) not world readable and searchable
AFAICT this sseems to be too strict however and checking for owner read/exec suffices.

qa: relax the checks on parent directories permissions

---

qa/1595

Test 1595 fails  on systems with PAGESIZE != 4096 (typically i.e. ppc64le architecture).
This fix enforces the PAGESIZE for the test.

Fix of test 1595 for systems with PAGESIZE != 4096

---

src/libpcp/src/logmeta.c

libpcp: fix 64-bit big endian v3 archive timestamp decoding

---

src/selinux/pcp.fc

Resolves Red Hat issue RHEL-61885.

selinux: ensure farm pmlogger/pmie processes labelled correctly

---

qa/1770
qa/1770.out
qa/group
src/libpcp/src/context.c
src/pmdas/linux_proc/GNUmakefile
src/pmdas/linux_proc/access.conf
src/pmdas/linux_proc/contexts.c
src/pmdas/linux_proc/contexts.h
src/pmdas/linux_proc/pmda.c
src/pmdas/linux_proc/pmdaproc.1

Allows authenticated users to access the proc metric values, through the new /etc/pcp/proc/access.conf configuration file.
Resolves issue #2089

pmdaproc: add an access control mechanism for remote sampling

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec

Change pcp-zeroconf on RHEL 10 and later to match Fedora, where state from /usr/lib/systemd/system-preset/90-default.preset is used to determine service enabled state centrally for sysadmins rather than hard-coding this in the PCP spec file.
Resolves Red Hat issue RHEL-22723

systemd: defer to system-preset for pmcd/pmie/pmlogger autostart

---

qa/1130
qa/1130.out
src/pcp2elasticsearch/pcp2elasticsearch.py

Elasticsearch 7.X removed the concept of mapping types (initially this was depreciated in Elasticsearch 6.X).
Change over to support dynamic mapping by making use of the updated 'POST {server}/{index}/_doc' index API with auto-generated ids by default.
Users can still use the the search type '-p pcp-metric' command line argument on launch to make use of the original pcp-metric mapping name for environments with Elasticsearch 5.X and 6.X, ('POST {server}/{index}/{search_type}' API).
Note: These older versions are considered EOL by Elastic.
This fix addresses github issue #1998.

pcp2elasticsearch: support dynamic mapping

---

src/selinux/pcp.te

A comprehensive fix for all the problems caused by the lockdown SELinux class was rejected by Linus and for the lack of a better option, the consensus upstream was to just remove the class entirely and stop checking anything in the lockdown hook.
This commit is a follow-up to selinux-policy commit 12f821c731b2 ("Remove the lockdown-class rules from the policy").

Remove all references to the lockdown class from SELinux policy

---

configure.ac

Two tests in `configure.ac` should not rely on whether the compiler emitted warnings, but should instead rely on whether the compilation failed. Unintended warnings (triggered by certain combination of CFLAGS) emitted by compiler will disrupt the test result, resulting in FTBFS.
For the `scandir()` test, with some combination of CFLAGS, the compiler may emit some warnings, failing the test, but in reality the `scandir()` call must use `const struct dirent *` for the callbacks.

Fix unreliable tests in `configure.ac`

---

qa/1368.out
qa/1747
qa/1747.out
qa/group
src/libpcp/src/logmeta.c
src/pmlogger/src/callback.c

Resolves Red Hat bug RHEL-67227
Resolves https://github.com/performancecopilot/pcp/issues/2115 Resolves https://github.com/performancecopilot/grafana-pcp/issues/203

pmlogger, libpcp: fix handling of dynamic instance domain labels

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec
debian/pcp-zeroconf.postinst
src/pmdas/dm/dmthin.data_high_util.pmie
src/pmdas/dm/dmthin.metadata_high_util.pmie

Instead of making dmthin enablement "special" in terms of its pmieconf configuration and pcp-zeroconf, just default enable it (whenever the PMDA is installed) as this simplify things.
Resolves Red Hat bug RHEL-78187

pmdadm, pmieconf: default to enabling the dmthin pmie rules

---

qa/1770
qa/1770.out
src/include/pcp/pmda.h
src/libpcp/src/accounts.c
src/libpcp/src/secureserver.c
src/pmcd/src/dopdus.c
src/pmdas/linux_proc/contexts.c

Allows authenticated users to access the proc metric values even when there is no local account for the users name, via the /etc/pcp/proc/access.conf configuration file.
Related issue #2089

pmcd, pmdaproc: allow non-local username connection attributes

---

src/pmdas/redis/pmdaredis.1

The redis pmda man page currently has two identical sections explaining how to uninstall the pmda. This change drops the first of the two.

Fix pmda redis man page

---

docs/specs/openapi.yaml
man/man3/pmwebapi.3
qa/1543
qa/1543.out
src/libpcp_web/src/webgroup.c

The names parameter for pmwebapi get metrics operation pulls in all the names in the performance metric tree that match its comma separate list.  There may be cases where particular individual metrics that are found during the search should be excluded from the results.  For example one may want to exclude specific metrics that have instances for all the process running on the system, but include all the other related metrics in that area of the performance metric name tree.  Rather than enumerating the names in the names parameter one could just name the node in the tree that contains all the names and then use the filter parameter to exclude the unwanted metrics.

Add filter parameter for the pmwebapi openmetrics 

---

build/rpm/redhat.spec

Since the minimum library requirement is available in RHEL 9, enable the amdgpu pmda.

build: Enable amdgpu pmda for rhel 9

---

build/containers/archive-analysis/root/usr/bin/archive-import.py

Improvements to the time window calculations in preparation for Sam's dashboard updating code.  Firstly, the switch from .index (optional) to .meta (mandatory) for archive file detection had the unanticipated side-effect of failing to detect compressed archives more often since the index is often not compressed.  This is now addressed by handling compression (any) suffixes following .meta in the filenames.  Second, archive importing can take awhile for large archives so we do Grafana setup in an initial quick pass over the archives before starting that time consuming secondary phase of loading now.  This allows us to get the Grafana dashboard time window configured as early as possible and likely well before the metrics data is available.
Small code cleanups as well, like adding type …

containers: updates to the archive-analysis container time windowing

---

qa/1543.out
src/libpcp_web/src/webgroup.c

Testing showed that globbing matching was being used for the exact match filtering.  Corrected the code to use exact matching when selected and updated qa/1543 to have the correct output when using exact match for filtering.

libpcp_web, qa: Fix the selection and testing of exact match filtering

---

man/man3/pmfetchgroup.3
src/libpcp/src/fetchgroup.c

Existing QA and C (pmclient_fg) and Python (pmrep et al) clients all work as before, the next commit will make the Python clients to use the feature and add appropriate QA.
Related to issue #2175

pmfg: allow for not preserving discrete metric values

---

debian/GNUmakefile

For the official debian unstable uploads we need to use a fixed debian/control that never changes, regenerating it during the build is apparently not allowed.
Resolves Debian bug #1102289

build: only regenerate debian/rules for Makepkgs builds

---

src/selinux/pcp.if
src/selinux/pcp.te

Access to /proc/pressure recently became selinux policy protected so we need to allow pcp_pmcd_t to access that as it contains important system level metrics.
Resolves Red Hat bugzilla #2358326.

selinux: add permissions allowing proc_psi_t access

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec

These were added originally at the request of our QE folk, but now they've requested to drop these as its causing some unexpected (distro-build-related, not PCP) fallout.
Related to Red Hat issue RHELMISC-10534

build: drop sub-package deps in the testsuite rpm

---

qa/1976
qa/1976.out
qa/group
src/pmdas/openmetrics/pmdaopenmetrics.python

added logic to support metric removal in pmdaopenmetrics.
A bug was discovered during development: the PMDA
did not support metric re-addition. So, logic was
added to address that scenario. Additionally, QA test 1976 was added to the testsuite.

pmdaopenmetrics metric removal

---

src/pcp/iostat/pcp-iostat.py

```
sagar@localhost:~/Desktop/pcp/upstream/src/pcp/iostat$ pcp iostat | head -5
sda             0.00    0.00    0.00   0.00     0.00     0.00    0.000    0.000    0.00    0.00    0.00    0.00
sda             0.00    0.00    0.00   0.00     0.00     0.00    0.000    0.000    0.00    0.00    0.00    0.00
sda             0.00    0.00    0.00   5.98     0.00    43.89    7.333    0.006    1.00    0.00    1.00    0.30
sda             0.00    0.00    0.00   0.00     0.00     0.00    0.000    0.000    0.00    0.00    0.00    0.00
File "/usr/libexec/pcp/bin/pcp-iostat", line 457, in <module>
sts = manager.run()
File "/usr/local/lib64/python3.6/site-packages/pcp/pmcc.py", line 687, in run
self._printer.report(self)
File "/usr/libexec/pcp/bin/pcp-iostat", line 309, …
```

pcp-iostat: fixed broken pipe issue in pcp-iostat utility.

---

src/selinux/pcp.te

selinux: additional policy needed for pcp_pmie_t using ps(1)

---

build/containers/archive-analysis/root/usr/bin/archive-import.py

Resolves an issue Ken reported running tests in the QA farm, which is due to use of an interface from more-recent-python: https://github.com/python/cpython/pull/91973

pmseries_import: use a datetime UTC interface from python3.6

---

src/pmdas/podman/podman.c
src/pmdas/podman/podman.h

Newer versions of the podman API JSON result present container name and command as an array, rather than a key with string value.  This tweaks the code to accommodate this, cleaning up string handling in general while there, and corrects the image name key parsing.
Resolves issue #2194.

pmdapodman: fix container name/command handling with latest podman

---

man/man1/pmproxy.1
qa/1608.out
qa/780.out
src/pmproxy/pmproxy.conf
src/pmproxy/src/http.c

Creates a new, optional [http] section in the pmproxy configuration file, where the following variables can be fine-tuned manually:
- chunksize (chunked transfer encoding buffer size, defaults to the server system page size);
- Access-Control-Allow-Headers (headers accepted from clients);
- Access-Control-Max-Age (set client maximum preflight request page age value, in seconds).
The previous global 'chunksize' setting is moved within [http] in a backwards-compatible way, such that the old name is honoured if it was present before the new setting.

pmproxy: allow configuration of previously hard-coded HTTP settings

---

src/include/pcp/config.h.in
src/include/pcp/config32.h
src/include/pcp/config64.h
src/include/pcp/configsz.h.in
src/libpcp3/src/include/pcp/config.h.in
src/libpcp3/src/include/pcp/config32.h
src/libpcp3/src/include/pcp/config64.h
src/libpcp3/src/include/pcp/configsz.h.in

Recently (last year) added PM_PAD_RESULT and PM_PAD_TIMESPEC macro values have 32/64 bit sensitivity so need to reside in the configsz.h.in file rather than config.h.in - this allows us to ship non-conflicting header files with these macros.
Resolves Red Hat bug RHEL-93186.

build: fix multilib installs for pcp-libs-devel packages

---

src/pcp/htop/GNUmakefile

.c and .h files are soft-linked before being compiled. Under heavy load or a build with a high CPU count, the compilation can start before header files are softlinked, resulting in a build error: 
```
| pcp-htop.c:13:10: fatal error: CommandLine.h: No such file or directory
|    13 | #include "CommandLine.h"
|       |          ^~~~~~~~~~~~~~~
```
Fix this by adding the make dependency between object files and the headers.

pcp-htop: fix header build race condition

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec

pcp-zeroconf rpm: use systemd presets to drive service start

---

src/pmdas/openmetrics/pmdaopenmetrics.python

Switch from using stat(2) ctime in seconds to mtime in nanoseconds on the openmetrics PMDA in an attempt to resolve a failure on some of the QA farm machines.
This only affects the case where file-based metrics are sourced - not the more usual cases of a REST API or script-based metrics.

pmdaopenmetrics: use fine-grained timestamp for a stat-based guard

---

qa/common.check

If a system has both Redis and Valkey available, the check for the key server needs to select the correct service to query.

Fix of version check for a keyserver

---

src/pmdas/openmetrics/pmdaopenmetrics.python

Improvements to metric removal feature.
Added control metrics instance metric
removal.
PMDA also now supports refresh after an
existing config entry is modified
Resolves RHEL-54039

pmdaopenmetrics metric removal bug fix

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec

Use the same approch as pcp-zeroconf to ensure mandatory PMDAs for testing are auto-installed and ready to go.

build: ensure sample and simple PMDAs installed with testsuite

---

src/selinux/pcp.te

On Fedora running Linux 6.15 kernels started seeing AVCs reported by RHBZ2371004:
type=AVC msg=audit(N): avc:  denied  { perfmon } for  pid=PID comm="ps" capability=38  scontext=system_u:system_r:pcp_pmlogger_t:s0 tcontext=system_u:system_r:pcp_pmlogger_t:s0 tclass=capability2 permissive=0
Added a pcp.te entry to address these AVCs.

src/selinux/pcp.te: Handle pmlogger perfmon AVCs

---

src/libpcp_web/src/discover.c
src/libpcp_web/src/util.c

Ken noticed 32-bit QA VMs were failing test 1617 - turned out the timestamp handling logic was still not quite right there due to a mishandling of __pmResult internals.
While there I noticed some odd sub-sec diagnostics, fixed.

libpcp_web: fix pmproxy 32-bit host handling in pmlogpush

---

CHANGELOG
qa/1415.out
qa/646.out
qa/990.out
src/include/pcp/mmv_stats.h
src/libpcp_mmv/src/exports
src/libpcp_mmv/src/mmv_stats.c
src/pmdas/mmv/mmvdump.c
src/pmdas/mmv/src/mmv.c

Exporting InDom help text appears to have been missing in the PMDA forever, but its there now.  Extensions to pmproxy (next commit) need more dynamic instance domain handling - this has been implemented via a mmap resetting mechanism, which allows for a more dynamic instance domain experience including empty sets.

pmdammv: support for empty indoms and export indom help text

---

qa/1620
qa/1620.out
qa/1621
qa/1621.out
qa/group
src/include/pcp/pmwebapi.h
src/libpcp_web/src/exports
src/libpcp_web/src/loggroup.c
src/libpcp_web/src/webgroup.c
src/pmlogger/src/pmlogger.c
src/pmlogger/src/remote.c
src/pmproxy/src/http.c
src/pmproxy/src/http.h
src/pmproxy/src/keys.c
src/pmproxy/src/logger.c
src/pmproxy/src/pcp.c
src/pmproxy/src/secure.c
src/pmproxy/src/server.c
src/pmproxy/src/server.h

To support the daily logging scripts requirements, pmproxy will now respond to SIGHUP by closing all active loggers.  Additionally when a conflicing (same minute) remote archive push path is required, we now use the -NN suffix handling in pmproxy (up to 100 alternates).

pmlogger, pmproxy: logger push SIGHUP and robustness improvements

---

qa/admin/package-lists/Fedora+43+x86_64

auditd is fixed in the audit-4.1.0-3 build, let's enable it for the F43 test environment (this is a partial revert of the pull request #2235).

qa: Enable auditd installation in F43 test env.

---

docs/specs/openapi.yaml
man/man3/pmwebapi.3
qa/1543
qa/1543.out
qa/1695
qa/1695.out
src/pmproxy/src/GNUmakefile
src/pmproxy/src/http.c
src/pmproxy/src/http.h
src/pmproxy/src/openmetrics.c
src/pmproxy/src/openmetrics.h
src/pmproxy/src/opentelemetry.c
src/pmproxy/src/opentelemetry.h
src/pmproxy/src/webapi.c

Access this functionality through the Accept HTTP header, which specifies the clients preference for output content-type, e.g.:
Docs and QA to follow, committing this early for discussion and comparion points for pcp2opentelemetry and pmdaopentelemetry.
Resolves Red Hat issue RHEL-85456

pmproxy: add OpenTelemetry output format for /metrics REST API

---

qa/1397.out
src/pmdas/smart/pmda.c
src/pmdas/smart/smart_stats.c

Fix potential TOCTOU issue when collecting drive UUID in PMDA.
Also fix QA/1397 output with spurious space at end of help text for one metrics.

pmda.smart Fix potiential UUID collection TOCTOU and QA Fix

---

qa/1397.out
src/pmdas/smart/smart_stats.c

Ensure the smart.info.uuid and smart.wwid.info.uuid metrics use the env variable path for fake root when QA testing.
Update QA/1397 output to reflect these changes.

pmdasmart: Ensure info.uuid metrics use fake root when QA testing

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec
qa/1131
qa/1131.out
qa/1589
qa/1977
qa/1977.out
qa/common.python
qa/group
src/GNUmakefile
src/pcp2opentelemetry/GNUmakefile
src/pcp2opentelemetry/pcp2opentelemetry.1
src/pcp2opentelemetry/pcp2opentelemetry.py

Supports translation of pcp metrics into opentelemetry format. Supports opentelemetry protocol http json.
Updated relevent qa tests; added one new one (1977) to test pcp2opentelemetry http functionality.
Added man page and makefile. Includes updates and
changes from review.

Addition of pcp2opentelemetry tool

---

src/pmdas/openmetrics/GNUmakefile
src/pmdas/openmetrics/ceph.url
src/pmdas/openmetrics/dcgm.url

Adds important scrapers for technologies underlying major open source and Red Hat projects (esp. Kubernetes, OpenShift).

pmdaopenmetrics: add default exporter ports for Ceph and DCGM

---

build/containers/archive-analysis/root/usr/bin/archive-import.py

As noted in #2277, the url printed to the console when running the archive-analysis container no longer works. Directly linking the dashboard is not possible as the url changes frequently. Instead, the link is now to the dashboards tab in grafana, where the archive-analysis dashboard can be easily accessed.

containers: fix broken url in archive-analysis container

---

build/mac/GNUmakefile
build/mac/io.pcp.pmie.plist
build/mac/io.pcp.pmlogger.plist
build/mac/io.pcp.pmproxy.plist

Also switch from logging plist output in /tmp to somewhere with more appropriate directory permissions for logs.

macos: add plist files for pmproxy, pmie and pmlogger

---

qa/1611
qa/1615
qa/1617
qa/1620
src/include/pcp.conf.in
src/libpcp_web/src/loggroup.c
src/pmlogger/pmlogger_daily.sh
src/pmlogger/pmlogger_janitor.sh

Allow more end-user control over where the pmlogger push archives will end up, along the lines of the PCP_ARCHIVE_DIR variable for regular pmlogger instances.

pmproxy: use PCP_REMOTE_ARCHIVE_DIR instead of PCP_LOG_DIR/pmproxy

---

src/python/GNUmakefile
src/python/setup.py

This change tweaks the Python make file so as to re-link the generated `.so` files. 
Prior to this, the `pmrep` command would fail with:
```
pcp@pcps-Virtual-Machine pcp % pmrep
File "/usr/local/bin/pmrep", line 40, in <module>
from pcp import pmapi, pmi, pmconfig
File "/opt/homebrew/lib/python3.13/site-packages/pcp/pmapi.py", line 104, in <module>
import cpmapi as c_api
ImportError: dlopen(/opt/homebrew/lib/python3.13/site-packages/cpmapi.cpython-313-darwin.so, 0x0002): Library not loaded: libpcp.4.dylib
Referenced from: <AFA4F539-0CDD-386F-BD06-4973ECA04FB6> /opt/homebrew/lib/python3.13/site-packages/cpmapi.cpython-313-darwin.so
Reason: tried: 'libpcp.4.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibpcp.4.dylib' (no such file), …
```

Osxbuild pythonextensions

---

qa/1611
qa/1615
qa/1617
qa/1620
src/libpcp_web/src/loggroup.c

One location was overlooked on an error path in handling the switch from PCP_LOG_DIR/pmproxy to PCP_REMOTE_ARCHIVE_DIR - fixed here and adjust several tests to detect this breakage (race condition).

pmproxy, libpcp_web: ensure correct path used for conflict resolution

---

src/pmdas/bpftrace/bpftrace/process_manager.py
src/pmdas/bpftrace/bpftrace/service.py

Unlike earlier versions, Python 3.14 asyncio.get_running_loop() throws an RuntimeError if there is no running event loop. To simplify code the setup and handling of the event loop has been moved completely inside the ProcessManager class.  The event loop is now explicity started.  These changes allow the bpftrace PMDA to work with Python 3.14, 11 of the 12 pmda.pftrace tests pass with this patch.  The failure in 1703 appears to have an unrelated issue which causes a coredump.

pmdabpftrace: Adjust event loop code to work with Python 3.14

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec
debian/control.pcp

A colleague encountered a "corrupt archive" - turned out it was an archive copied from one container to another and the second had PCP but didn't have zstd installed:
```
__pmProcessPipe: child pid=530309 execvp(zstd, ...) failed pmrep: Corrupted record in a PCP archive
```
Which is somewhat cryptic; took me a little while to figure out the root cause, despite it being in the error message - the "corrupted record" bit distracted me I guess.
This commit makes zstd a hard dependency because I think we will see more of this scenario now on (remote) replay hosts since we choose to use this form of compression more often, in recent releases.

build: add zstd package as a hard dependency

---

qa/admin/list-packages

When retrieving the list of packages,
the output of commands like yum sometimes assumes the English only. 
Therefore, set the LANG Environment.
Fixes: #2338

Fix locale-dependent behavior

---

qa/src/chk_memleak.c

Fix for [https://github.com/performancecopilot/pcp/security/code-scanning/376](https://github.com/performancecopilot/pcp/security/code-scanning/376)
To fix the problem, we must ensure the subtraction occurs in a signed type context, or (preferably) change the logic to a direct unsigned comparison without subtraction. Instead of comparing `(memusage - first_memusage) > 0`, compare simply `memusage > first_memusage`, which is safer and avoids underflow. This change does not alter functionality, since `'a - b > 0'` is equivalent to `'a > b'` in unsigned arithmetic (except when underflowed), but is clearer and would not trigger static analysis warnings.
Edit the block in qa/src/chk_memleak.c at line 121:
- Replace `if (memusage - first_memusage > 0) {` with `if (memusage > first_memusage) {` …

Fix for code scanning alert no. 376: Unsigned difference expression compared to zero

---

src/pmdas/rocestat/pmdarocestat.python

ibdev2netdev can be installed in multiple locations. 
For example, ibdev2netdev is installed either in /usr/sbin or /usr/bin on RHEL8.
```
$ sudo yum provides ibdev2netdev
mlnx-ofa_kernel-24.10-OFED.24.10.3.2.5.1.rhel8u6.x86_64 : Infiniband HCA Driver
Repo        : @System
Matched from:
Filename    : /usr/sbin/ibdev2netdev
rdma-core-37.2-1.el8.x86_64 : RDMA core userspace libraries and daemons
Repo        : rocky86-baseos
Matched from:
Filename    : /usr/bin/ibdev2netdev
```
We avoid hard-coding an absolute path and
simply invoke it by name so that PATH resolution can handle it.

rocestat PMDA: fix invalid path on RHEL8

---

src/pmieconf/rules.c

There are minor memory leaks in read_rule() if the duplicate rule names are encountered. Make sure the allocated memory is freed if this is encountered.
Fixes CID 454664
Fixes CID 454667

src/pmieconf/pmieconf.c: Eliminate minor memory leaks [Coverity]

---

build/rpm/pcp.spec.in
build/rpm/redhat.spec
src/pmdas/hdb/hdb.conf
src/pmdas/hdb/pmdahdb.python

Make config parameters in hdb.conf optional, with exception of username and password.
Replace LooseVersion module with packaging.version module as the LooseVersion is not available in RHEL and is considered as obsolete.

Improvements of hdb pmda

---

man/man1/dkvis.1
man/man1/mpvis.1
man/man1/pcpintro.1
man/man1/pmdapipe.1
man/man1/pmdashping.1
man/man1/pmdaweblog.1
man/man1/pmhostname.1
man/man1/pmie.1
man/man1/pminfo.1
man/man1/pmlogbasename.1
man/man1/pmlogcheck.1
man/man1/pmlogextract.1
man/man1/pmlogger.1
man/man1/pmlogrewrite.1
man/man1/pmproxy.1
man/man1/pmtime.1
man/man1/pmview.1
man/man3/pmgetoptions.3
man/man3/pmmergelabels.3
man/man3/pmregisterderived.3
man/man3/pmwebapi.3
man/man3i/__pmaf.3
man/man5/LOGARCHIVE.5
man/man5/mmv.5
scripts/man-lint
src/include/builddefs.in
src/pmdas/hdb/pmdahdb.1
src/pmdas/opentelemetry/pmdaopentelemetry.1

On macOS there are several man pages producing warnings that can be seen when man(1) is run for these installed pages.
This adds a CI checking for these warnings.  Fixes to follow.

build: extend man page linting to check for runtime errors
